### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by danielsalles** [webpack-contrib/file-loader#101]
I do not know where I can is missing it. I do not know if it's a bug, or if any of my fault.
I'm trying to add the bootstrap icons, but I can not load svg files, and t, woff and others.

`    loaders: [
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" },
    ],`

I installed file-loader and url-loader as dev in my npm.

Error:

ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
Module parse failed: /home/daniel/manga-online/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss 6:4261-4364 6:4387-4490
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main

ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
Module parse failed: /home/daniel/manga-online/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss 6:4680-4784
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main

ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
Module parse failed: /home/daniel/manga-online/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss 6:4542-4647
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main

ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
Module parse failed: /home/daniel/manga-online/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss 6:4816-4919
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-7eb508b8!./~/sass-loader!./src/assets/sass/app.scss
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main

**Comment by raptoria** [comment]
+1 I have the same problem..

**Comment by michael-ciniawsky** [comment]
@danielsalles Still got this regression ? if please provide more info about your current config

**Comment by danielsalles** [comment]
@michael-ciniawsky I solved this problem already. What has happened is that the configuration mode of the vuejs is a bit different from that usually taught. The part where you put the loaders is different. I do not remember the exact solution now, but it's very simple to solve.

**Comment by michael-ciniawsky** [comment]
@danielsalles Open a new issue if still any regressions regarding `file-loader` 😛  Closing this one
