### ISSUE TITLE
`Error: Cannot find module "."`, if dynamic "name" parameter is used

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/file-loader#105]
I cannot explain this. Say I use `html-webpack-plugin` like [this](https://github.com/ampedandwired/html-webpack-plugin/blob/master/migration.md#isomorph-apps):

```
module.exports = function(templateParams) {
  return '<html>..</html>';
};
```

Now I want to use `file-loader`. Maybe like this:

```
module.exports = function(templateParams) {
  return `<!DOCTYPE html>
<html>
<body>
  <script src="${require('file-loader!./de_DE/foo.js')}"></script>
</body>
</html>
`;
};
```

This works. Let us rewrite it to this:
```
module.exports = function(templateParams) {
  return `<!DOCTYPE html>
<html>
<body>
  <script src="${require('file-loader?name=de_DE/foo.js!./de_DE/foo.js')}"></script>
</body>
</html>
`;
};
```

Works, too. Another rewrite:
```
module.exports = function(templateParams) {
  const locale = 'de_DE';
  return `<!DOCTYPE html>
<html>
<body>
  <script src="${require(`file-loader?name=de_DE/foo.js!./${locale}/foo.js`)}"></script>
</body>
</html>
`;
};
```

Still works. But now this:
```
module.exports = function(templateParams) {
  const locale = 'de_DE';
  return `<!DOCTYPE html>
<html>
<body>
  <script src="${require(`file-loader?name=${locale}/foo.js!./${locale}/foo.js`)}"></script>
</body>
</html>
`;
};
```

```
ERROR in Template execution failed: Error: Cannot find module "."
```

I have _no_ idea why this happens. I guess this file is somehow "preprocessed" by webpack?

If I use `DefinePlugin` to inject `locale` with `process.env` it works:
```
module.exports = function(templateParams) {
  return `<!DOCTYPE html>
<html>
<body>
  <script src="${require(`file-loader?name=${process.env.locale}/foo.js!./${process.env.locale}/foo.js`)}"></script>
</body>
</html>
`;
};
```

**Comment by SpaceK33z** [comment]
Could you try removing the backticks from the `require` statement? I heard there were some issues with that.

**Comment by donaldpipowitch** [comment]
Tried that, too. Same result. :(

**Comment by SpaceK33z** [comment]
Okay, a workaround could be to add the loader config in your webpack config instead. You could match on `test: /foo\.js/`.

**Comment by evilebottnawi** [comment]
@donaldpipowitch Is the problem still there? If yes please create minimum reproducible test repo, thanks!

**Comment by panta82** [comment]
I have the same issue with the new create-react-app setup.

I try to load image dynamically, based on a config file.
This used to work before, with a webpack 1.x setup.

Here's the minimal repro: https://github.com/panta82/requireissue
