### ISSUE TITLE
Latest changes are not published in public npm registry

### ISSUE THREAD

**Issue by roastlechon** [webpack-contrib/file-loader#106]
0.9.0 is not the latest anymore since index.js has been changed. Will the latest changes on index.js be reflected as another version in public npm registry?

**Comment by roastlechon** [comment]
@mobitar

**Comment by JalAzimi** [comment]
@roastlechon 
SpaceK33z on #81:
> I'll release a new version when we release webpack v2 (since I want to release it with #99 as well).

**Comment by roastlechon** [comment]
Thanks did not see the PR comments

**Comment by gravitycode** [comment]
While the webpack 2 release is being launched, can we upload the library with the latest changes to the public npm repository? This creates a lot of confusion and headaches.

**Comment by TheLarkInn** [comment]
CC @webpack-contrib/admin-team

**Comment by d3viant0ne** [comment]
I'll take care of it

**Comment by BTMPL** [comment]
Think this can be closed now, thanks @TheLarkInn @d3viant0ne

**Comment by d3viant0ne** [comment]
No problem :)
