### ISSUE TITLE
publicPath function problem and advice

### ISSUE THREAD

**Issue by zhouleiF** [webpack-contrib/file-loader#109]
# Problem
The publicPath function write in webpack.config invaild as JSON.stringify can not transfer the value typeOf Function.

     {

         test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,

         loader: 'file',

         query: {

               limit: 10000,

               name: '[path][name].[hash:7].[ext]',

               "publicPath": function(url) {

                    return url.replace(/src/, 'build')

              }

         }
     }

The publicPath can not work

# Advice
We can pass string to publicPath, it's a function transfer to string 
and so the original coding should change , the `config.publicPath` should transfer to Function using `eval` before operate this variate.
    
# The last
I hope this problem can be resolved , because the work what I am doing now need to set the outPath depend by the original path of files

# Thanks

**Comment by puneetar** [comment]
Do we have any updates on this issue ?

**Comment by michael-ciniawsky** [comment]
### `webpack =< v1.0.0` && `file-loader =< v1.0.0`

**webpack.config.js**
```js
var config = {
  module: {
    loaders: [
      {
        test: /\.png$/,
        loader: 'file-loader'
      }
    ]
  },
  fileLoader: {
     publicPath: (url) => url.replace(this, that) 
  }
}
```

### `webpack >= v2.0.0`

**webpack.config.js**
```js
const config = {
  module: {
    rules: [
      {
        test: /\.png$/,
        use: { 
          loader: 'file-loader',
          options: {
             ident: 'file' // <= keep {Function} reference when stringified
             publicPath: (url) => url.replace(this, that)
          }
        }
      }
    ]
  }
}
```
