### ISSUE TITLE
Output to a directory based on `entry`

### ISSUE THREAD

**Issue by chrishutchinson** [webpack-contrib/file-loader#114]
Hey,

I'm currently running Webpack `2.2.0-rc.2`.

My app has multiple entry points, and depending on which one the `require()`'d image was found, I'd like to output it to an different location, based on the name of the entry point. For example my app structured as follows in the `./app` directory:

    | app
      | one
      | - index.js # requires ../static/image-one.png
      | two
      | - index.js # requires ../static/image-two.png
      | three
      | - index.js # requires ../static/image-three.png
      | static
      | - image-one.png
      | - image-two.png
      ` - image-three.png

And I want to see this in the `./dist` directory after running Webpack.

    | dist
      | one
      ` - bundle.js
        | static
        ` - [hash-of-image-one].png
      | two
      ` - bundle.js
        | static
        ` - [hash-of-image-two].png
      | three
      ` - bundle.js
        | static
        ` - [hash-of-image-three].png

My loader config for images is as follows:

    {
      test: /\.(png|jpg|jpeg|svg|gif)$/,
      include: [
        path.resolve(__dirname, '../app/static')
      ],
      use: [
        {
          loader: 'file-loader',
          options: {
            name: './static/[hash].[ext]',
          }
        }
      ]
    }

What I'd like to do is, in the `options` object for `file-loader`, pass the name property as something like:

    name: './[entryName]/static/[hash].[ext]',

However `[entryName]` doesn't exist, and `[name]` only references the name of the image I'm loading, not the name of the entry point that eventually required in the image.

I'm happy for the same image required twice in two different entry points to be duplicated into two different output directories, as that suits my eventual needs.

At present I'm only able to create a top-level `static` directory in `./dist`, rather than one nested in each output directory, which doesn't allow me the flexibility I need.

Thanks for your help!

**Comment by eromano** [comment]
Hi guys, I am interested in this functionality as well but seems not to be a really common scenario but some thumbs up from January has been added.  
is someone already working on this feature request?
any possible workaround in the meantime?

**Comment by michael-ciniawsky** [comment]
@eromano Nope but I will triage this soon, if you have an idea how to and want to give it a try feel free to send PR for further discussion 😛

**Comment by ThomasSoloist** [comment]
@michael-ciniawsky I have read all the document of webpack's API, and it seems we can't get the entry name directly. Or even can't get which module required this file. Maybe we need to send a feature request to the webpack.

<img width="389" alt="qq20170414-095357 2x" src="https://cloud.githubusercontent.com/assets/12109558/25030691/4c03ab02-20f9-11e7-9011-757e8da7437c.png">

**Comment by eromano** [comment]
Someone was proposing this piece of code in order to get it but I don't know if it works
```javascript
var findEntry = function( mod ) {
    console.log(mod.reasons);
    if (mod && mod.reasons.length > 0) {
        return findEntry( mod.reasons[0].module )
    }

    console.log(mod.reasons[0]);

    return mod.resource
}

 findEntry(this._module);

```

**Comment by damianobarbati** [comment]
Any solution for this?
How can we link file-loader to output files in a folder relative to entry folder in multiple entries configuration?

```
    entry: {
        'visitor/app': './apps/visitor/index.js',
        'visitor/vendor': ['lodash'],
        'user/app': './apps/user/index.js',
        'user/vendor': ['redux'],
    },
    output: {
        filename: `build/[name].${process.env.NODE_ENV === 'development' ? '' : '[chunkhash].'}min.js`,
        chunkFilename: `build/[name].${process.env.NODE_ENV === 'development' ? '' : '[chunkhash].'}min.js`,
        publicPath: '/',
    },

        },{
            test: /\.(jpg|jpeg|png|gif|svg)$/i,
            use: [{
                loader: 'file-loader',
                options: {
                    limit: 10000,
                    name: 'build/assets/images/[name]-[hash].[ext]',
                }
            }]

```

**Comment by luchunhui** [comment]
@eromano  I think that this issue is very useful in project，because not of all project are used spa，some of project is some of entries and some of output.Like this project directory：
```
.
├── dist
│   ├── VIP
│   │   ├── VIP.5c78c.css
│   │   ├── VIP.5c78c.js
│   │   └── index.html
│   │   ├── images
                   └── vip1.453534.png
                   └── vip2.765776.png
│   └── test
│       ├── index.html
│       ├── test.5c78c.css
│       └── test.5c78c.js
│   │   ├── images
                   └── test1.344535.png
                   └── test2.453569.png
├── package.json
├── pages
│   ├── VIP
│   │   ├── html
                   └── VIP.html
│   │   ├── images
                   └── vip1.png
                   └── vip2.png
│   │   ├── index.js
│   │   ├── js
│   │   │   └── vip1.js
│   │   └── sass
│   │       └── index.scss
│   └── test
│       ├── html
│       │   └── test.html
│       ├── images
                   └── test1.png
                   └── test2.png
│       ├── index.js
│       ├── js
│       │   └── test.js
│       └── sass
│           └── test.scss
├── postcss.config.js
└── webpack.config.js
```
Or how can I get the name of each folder, and I tried the regular filtration path, but without success, I don't understand 'file - loader' in '[n]' regular verification method, don't know how to use this method

**Comment by Bob-Thomas** [comment]
Not sure if you're still looking for an answer but I also stumbled upon this problem.
I ended up using the customInterpolateName property.
My path looked like `/var/www/project/moduleA/assets/`
To extract the module name from my path so I placed my [path] between some symbols like ;;
`;[path]/;assets` the url becomes `;/var/www/project/moduleA/;assets/`
and just replaced everything between ;; to my module name that i could extract from the path like
`url.replace(/;.+;/, url.match(/;.+project(\w+).*;/)[1]` which turns the url into `moduleA/assets`
my loader I used was 
```
      {
        test: /\.(woff|woff2|ttf|eot|svg|jpg|png|mp4)$/,
        loader: 'url-loader?limit=5000&name=./;[path];/media/[hash].[ext]'
      },
```


```
    new webpack.LoaderOptionsPlugin({
      options: {
        customInterpolateName: (url) => {
          url = url.replace((regex to match on the url), 'replace it with something');
          return url;
        }
      }
    })
```

**Comment by himerus** [comment]
Still looking for a proper resolution to this issue. I'm unsure why this was closed. 

The last 'solution' is a bit hacky IMHO, and not what I'd consider recommending for anyone wanting to implement a similar structure. 

What is the 'recommended' method to accomplish what the OP asked?

**Comment by airtoxin** [comment]
I'm solved this by multi-compiler options.
https://stackoverflow.com/a/38132106/2014050

**Comment by MasterB** [comment]
He @airtoxin thx for this link. It works for me!

**Comment by HouCoder** [comment]
I solved this problem with `outputPath` option.

Here is my project structure.

Source folder.
```
➜  landing-pages git:(master) ✗ tree src
src
├── components
│   └── ga.html
└── pages
    ├── jp
    │   ├── index.html
    │   └── index.js
    └── us
        ├── images
        │   └── background-image.jpg
        ├── index.html
        ├── index.js
        └── index.scss
```

Here is the generated folder structure, the `images` folder is perfectly inside the correct parent folder(us folder).

```
dist
├── jp
│   ├── app.d76101afaadb85baa17a.js
│   └── index.html
└── us
    ├── app.5a9a8488.css
    ├── app.d76101afaadb85baa17a.js
    ├── images
    │   └── background-image.6050de48ef658e261ab33664d455e6f1.jpg
    └── index.html
```
My webpack entry names are perfectly matched with folder names under `src/pages` folder, so I can use a custom function to get the correct entry name based on relative path:

```js
// Use this to make file-loader output to the correct target folder based on entry name.
// Not ideal but does the trick, hope file-loader will support this featur in the future.
// https://github.com/webpack-contrib/file-loader/issues/114
outputPath: (url, resourcePath, context) => {
    // Get entry name from relative path.
    const relativePath = path.relative(context, resourcePath);

    // https://regex101.com/r/qW6RnN/1
    const entryName = relativePath.match(/^src\/pages\/([a-zA-Z0-9-_.]*)/)[1];

    return `/${entryName}${url}`;
},

name: '/images/[name].[hash].[ext]',
```

Hope it's useful for you.

**Comment by gauravkakkar87** [comment]
@HouCoder I need to do the similar kind of configuration for a project, can you help or share your webpack config file. I tried above code, but not sure where it should go.

**Comment by skjnldsv** [comment]
Here's what I'm using, works fine!

``` js
	entry: {
		'socialsharing_diaspora':	path.join(__dirname, 'socialsharing_diaspora/src', 'main.js'),
		'socialsharing_email':		path.join(__dirname, 'socialsharing_email/src', 'main.js'),
		'socialsharing_facebook':	path.join(__dirname, 'socialsharing_facebook/src', 'main.js'),
		'socialsharing_twitter':	path.join(__dirname, 'socialsharing_twitter/src', 'main.js')
	},
	output: {
		path: path.resolve(__dirname),
		publicPath: '/js/',
		filename: '[name]/js/[name].js'
	},
```

``` js
    socialsharing_diaspora/js/socialsharing_diaspora.js  82.2 KiB       0  [emitted]        socialsharing_diaspora
socialsharing_diaspora/js/socialsharing_diaspora.js.map   390 KiB       0  [emitted] [dev]  socialsharing_diaspora
          socialsharing_email/js/socialsharing_email.js  82.2 KiB       1  [emitted]        socialsharing_email
      socialsharing_email/js/socialsharing_email.js.map   390 KiB       1  [emitted] [dev]  socialsharing_email
    socialsharing_facebook/js/socialsharing_facebook.js  82.2 KiB       2  [emitted]        socialsharing_facebook
socialsharing_facebook/js/socialsharing_facebook.js.map   390 KiB       2  [emitted] [dev]  socialsharing_facebook
      socialsharing_twitter/js/socialsharing_twitter.js  82.2 KiB       3  [emitted]        socialsharing_twitter
  socialsharing_twitter/js/socialsharing_twitter.js.map   390 KiB       3  [emitted] [dev]  socialsharing_twitter

```
