### ISSUE TITLE
Question: Is it possible to minify/optimize the required/loaded file in some way when they are copied using file-loader?

### ISSUE THREAD

**Issue by kabirbaidhya** [webpack-contrib/file-loader#119]
For instance currently when I do `require('./something.html'` in my code and configure `file-loader` something like this: 
```
    module: {
        rules: [
            {test: /\.html$/, loader: 'file-loader', options: {name: '[name].[hash].html'}
        },
    }
```
What this does is just copy the original files to the `dist/` directory and replaces the `require` calls to this file with the generated filename instead. Which works. 

**But I'm wondering if it's possible to further process the file in someway like further minification or optimization of the file using any other loaders?** 

Is there any workaround to do this with `file-loader`? 

I tried something like this but it doesn't seem to work. It's not minified.

```
{test: /\.html$/, use: [
                {loader: 'raw-loader'},
                {loader: 'html-minify-loader'},
                {loader: 'file-loader'}
            ]},
```
Let me know if anybody has done it in anyway.

**Comment by SpaceK33z** [comment]
Our [issue template](https://raw.githubusercontent.com/webpack-contrib/file-loader/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).

**Comment by kabirbaidhya** [comment]
That makes sense. I've posted this in stackoverflow [here](https://stackoverflow.com/questions/41875636/minification-optimization-of-the-files-required-using-the-webpack-file-loader-h).

**Comment by kabirbaidhya** [comment]
Just in case, if anyone runs into this issue you may want to use this plugin [`webpack-file-preprocessor-plugin`](https://github.com/kabirbaidhya/webpack-file-preprocessor-plugin)

**This is a very lightweight webpack plugin that allows you to pre-process files or assets loaded using `file-loader` before they're finally emitted.**

As this is a very generic plugin you can use it to do any kind of custom pre-processing to assets just before they're finally emitted by webpack.

This example demonstrates how you can use this plugin to minify the html assets loaded using [`file-loader`](https://github.com/webpack-contrib/file-loader).

```javascript
    const webpack = require('webpack');
    const WebpackFilePreprocessorPlugin = require('webpack-file-preprocessor-plugin');
    const minifyHtml = require('html-minifier').minify;
    
    module.exports = {
        entry: {
            app: './index.js'
        },
        output: {
            path: './public/dist',
            publicPath: '/dist/',
            filename: '[name].bundle.js'
        },
        module: {
            rules: [
                {
                    test: /\.html$/,
                    use: {
                        loader: 'file-loader', 
                        options: {
                            name: 'tmpl/[hash].html'
                        }
                    }
                }
            ]
        },
        plugins: [
            new WebpackFilePreprocessorPlugin({
                // Prints processed assets if set to true (default: false)
                debug: true,
                // RegExp pattern to filter assets for pre-processing.
                pattern: /\.html$/,
                // Do your processing in this process function.
                process: (source) => minifyHtml(source.toString())
            })
        ]
    };
```

Check this [`webpack-file-preprocessor-plugin`](https://github.com/kabirbaidhya/webpack-file-preprocessor-plugin) for more information.
