### ISSUE TITLE
[path] returns full absolute path, can we have a little more control or relative ?

### ISSUE THREAD

**Issue by appsolutegeek** [webpack-contrib/file-loader#124]
Hi,

I am importing a image using require from /src/client/info/app-1/assets/images/backgroup.jpg

Problem is that this file is now being copied to my dist folder as /src/client/info/app-1/.... etc

I want to be able to copy it to /dist/app-1/.... etc which is where my index.html is.

I am using

```
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file-loader?name=[path][name].[hash].[ext]'
      },
```

So of course the [path] is returning the full path, but this path isn't fixed, is there  a way to use a relative [path] or manipulate the [path] on the fly by removing /src/client/info from the url ?

if I remove the [path] it ends up in the root which isn't what I am looking for either.

A little confused, any help really appreciated

Thanks

**Comment by BTMPL** [comment]
Can this not be solved by removing `[path]` and using `outputPath` (+`publicPath` if needed)?

**Comment by appsolutegeek** [comment]
Thanks @BTMPL , but I cant hard code the app-1, is this is dynamic and will change. It would be great if i could do a SubString :-)

I also found I can pass in the querystring "context" but the problem here is that i can do a "../../" but this doesn't from the right hand side.

The [path] is exactly what I need but its padded with some things I wish to remove..

**Comment by BTMPL** [comment]
@appsolutegeek I had a similar problem, where the emitted files would be placed in a directory with a random name (for cache busting purposes) and the bundle would be placed in a different location that the app base URL. To solve that I just made the app accept `assetsUrl` as a param (with redux store hydration) and I add it  before the relative image url.

```
const image = require('image.jpg');
// later on
render() {
  return <img src={this.props.assetsUrl + image} alt="" />
}
```

**Comment by appsolutegeek** [comment]
Thanks @BTMPL, yep thats probably not my case though.

**Comment by whezdcm** [comment]
got the same problem today.
solved it like this:

```
{
	test: /\.(png|jpg|gif|svg)$/,
	loader: 'file-loader',
	options: {
		**context: path.resolve(__dirname, "./src/client/info"),**
		name: '[path][name].[ext]?[hash]'
	}
}
```

seems like file-loader used 'context' as root of the 'path' witch can be override by options

P.S. use webpack2 .  hope helpful.

**Comment by whezdcm** [comment]
got the same problem today.
solved it like this:

```
{
	test: /\.(png|jpg|gif|svg)$/,
	loader: 'file-loader',
	options: {
		**context: path.resolve(__dirname, "./src/client/info"),**
		name: '[path][name].[ext]?[hash]'
	}
}
```

seems like file-loader used 'context' as root of the 'path' witch can be override by options

P.S. use webpack2 .  hope helpful.

**Comment by appsolutegeek** [comment]
Nice!!!!, This seems to work! :-)
Great! Thanks.
