### ISSUE TITLE
Using file-loader with __webpack_public_path__?

### ISSUE THREAD

**Issue by reywright** [webpack-contrib/file-loader#125]
Using the latest version of file-loader. The following works for me:

```file-loader?name=img/[name].[ext]&emitFile=false&publicPath=/xyz/```

Because the publicPath for my application can vary wildly, I can't hardcode the publicPath in the webpack config. I'd like if the file-loader used `__webpack_public_path__` or had some option like [webpack_public_path] or basically any hook I could use to be able to let my backend specify what the publicPath is.

Any ideas? Is this something I can get around for now? I feel like this is either a bug, or a feature, or a question... I don't know enough to say.

**Comment by reywright** [comment]
Hmmm I'm using redux / webpack.
 ```
 'js/app.js': [
    "es5-shim",
    "es5-shim/es5-sham",
    './redux/public-path',
    "bootstrap-loader/extractStyles",
     "font-awesome-loader!./font-awesome.config.js",
     './redux/public-path',
     './redux/app'
],
```

This doesn't work, and putting the declaration inside app.js also doesn't work.

**Comment by lili21** [comment]
I think what you need is outputPath.

**Comment by lili21** [comment]
`file-loader` will use `__webpack_public_path__` by default. so You don't need to set publicPath for `file-loader`

**Comment by lili21** [comment]
@reywright https://github.com/webpack/webpack/issues/2776

**Comment by lili21** [comment]
actually, the `publicPath` config will override `__webpack_public_path__`. I guess that's the problem. @reywright

**Comment by reywright** [comment]
@lili21 what I'm saying is I need to specify the publicPath **because** the publicPath doesn't work otherwise. I've seen those threads you're talking about... I'll try them again but I remember trying them already.

**Comment by lili21** [comment]
I thought what you need is `__webpack_public_path__` , then why you need `publicPath` ?

**Comment by reywright** [comment]
I don't. I'm only using it because __webpack_public_path__ isn't working

**Comment by lili21** [comment]
update to latest version . and It will work.

**Comment by novemberborn** [comment]
I think this is due to https://github.com/webpack/webpack/issues/3265#issuecomment-306435580.
