### ISSUE TITLE
fileLoader option in webpack config object for webpack 2 is not allowed

### ISSUE THREAD

**Issue by KingMario** [webpack-contrib/file-loader#126]
In webapck 2,  the default option `fileLoader` in webpack config object is not allowed. `should NOT have additional properties` exception will be thrown.

In webpack 1, it works:
```
webpackConfig = {
  // entry, output, module ...
  fileLoader: {
    publicPath: function (url) {
      return `{{ "${url.replace(new RegExp(`^${config.build.assetsSubDirectory}/assets/`), '')}" | asset_url }}`
    }
  }
}
```
Here the publicPath callback function is used for shopify theme backend template.

For webpack 2, one can use `loader` with publicPath callback function, but it may have potential conflict with other loaders.

I just pulled PR #127, which will allow dot-separated path such as `loader.fileLoader` as the key for additional options for file-loader. With the original default `fileLoader` remains, and the same options fetching with non-dot-separated path, the change will not break any existing configuration.

**Comment by michael-ciniawsky** [comment]
Discussion moved to #127
