### ISSUE TITLE
Use loderUtils.getOptions instead of loaderUtils.parseQuery

### ISSUE THREAD

**Issue by bensampaio** [webpack-contrib/file-loader#128]
The `loaderUtils.parseQuery` function was deprecated. For that reason, I constantly get the following warning when I run webpack 2: `DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56`. Can you update?

**Comment by d3viant0ne** [comment]
@bensampaio - Most of the loaders suffered the same issue. I'm working through them ( 20 or so to do ). I'll have this fixed and out in about an hour.

**Comment by d3viant0ne** [comment]
@bensampaio - `v0.10.1` has been published to npm

**Comment by bensampaio** [comment]
Awesome, thanks a lot!
