### ISSUE TITLE
SVG MIME Type problems

### ISSUE THREAD

**Issue by andosteinmetz** [webpack-contrib/file-loader#131]
I've been working on a site using file-loader to handle images referenced in Vue templates. Everything was working fine until I tested on mobile (iPhone), and suddenly, many of my SVGs weren't loading. On closer inspection, the ones that weren't loading were the ones being served from my webpack distribution folder. If I moved them to a 'normal' directory, they appeared correctly. 

The problem was that these images were being served without a MIME-type in the headers, which is known to cause issues on mobile safari. I changed my config to use the url-loader for SVGs (which should be fine for my purposes) and my icons are appearing on mobile, so I suspect this has something to do with file-loader, though I'm not sure how file loader would be stripping the headers.

Here's my config:
https://gist.github.com/andosteinmetz/1a5a8f0ab849bc08b27b32d2e12c1a0a

Thank you!

**Comment by michael-ciniawsky** [comment]
@andosteinmetz The `url-loader` looks up the MIME Type while the `file-loader` doesn't 😛 Could you provide more info on your about your setup please (`webpack.config.js`) ?
