### ISSUE TITLE
Stop file-loader from emitting a bundle

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [webpack-contrib/file-loader#132]
Im using file-loader in conjuction with pug-html-loader and require.context() to convert a folder of pug templates into separate html files. In my webpack.config.js i have these entry points:
```javascript
entry: {
	'js/bundle.js': './js/.app.js',
	...
	'.delete': './pug/.pug.js' //the output bundle for this is unneeded
}
```
this references a .pug.js file that just has this in it:
```javascript
// require all pug templates
var pugs = require.context('./', true, /\.pug$/)
pugs.keys().forEach(pugs)
```
and this is my loader for pug 
```javascript
{
	test: /\.pug$/,
	include: path.resolve(__dirname, "../pug"),
	use: [
		"file-loader?name=[path][name].html&context=./source/pug",
		{
			loader: "pug-html-loader",
			options: {
				pretty:true,
				exports:false,
				data: {foo:"BAR"}
			}
		}
	]
}
```
the issue is the entry point `'.delete': './pug/.pug.js'` creates an empty .delete file in my output directory, as well as all the html templates in the correct location.

is there any way i can stop the pug entry point from emitting an output bundle as well as the separate html files that it should be generating?

**Comment by michael-ciniawsky** [comment]
First of all why ? 😛  If you just want to convert templates a task runner like Grunt, Gulp is *way* easier to use for this then webpack, which is a *[JS] Bundler*. Please elaborate more on what you are trying to achieve maybe I'm missing something here :). webpack needs at least one JS entry and will output a bundle at the end

**Comment by matthewjumpsoffbuildings** [comment]
I appreciate that you can use other packages to do this, but I like not having to bring in the whole gulp ecosystem on top of webpack. Between webpack loaders and gulp plugins the projects dependencies can balloon quickly.

My current setup works fine overall, and right now my build scripts are just `rm`ing the unneeded pug bundle output. Its not a major issue, itd just be nice to have the option

**Comment by matthewjumpsoffbuildings** [comment]
because i need an entry point for the pug loading. `.pug.js` is the entry point, it contains that `require.context()` which is what looks in the pug folder for any `.pug` files.

what happens is, the `require.context()` in `.pug.js` calls all the `.pug` files in the source `pug` folder, and then outputs each of them into the output folder rendered as `.html`.

I have to give the pug entry point a name, just like the SASS and JS entry points have a name. but that name is whats used for generating the unnecessary output bundle (`.delete`), and in my current build script i run `rm .delete` after builds

I cant see any other way to trigger the pug loading without having a separate entry point for the pug? I dont want it to be part of my JS or CSS bundles/entry points

**Comment by matthewjumpsoffbuildings** [comment]
btw the `.delete` bundle contains almost nothing. just a few lines of webpack module code, and some comments marking where the html output was extracted from it (by file-loader) to be put into separate html files

**Comment by michael-ciniawsky** [comment]
I'm afraid you will need to `delete` this extra bundle manually, but I ask in the @slack to double check 😛
