### ISSUE TITLE
query add publicPath?

### ISSUE THREAD

**Issue by coderwin** [webpack-contrib/file-loader#133]
I want to use the publicPath for the list
* js: j.cdn.com.cn
* img: i.cdn.com.cn
* css: c.cdn.com.cn
```
    if (typeof query.publicPath === 'undefined') {
        return "module.exports = __webpack_public_path__ + " + JSON.stringify(url) + ";";
    } else {
        url = (query.publicPath || '') + url;
        return "module.exports = " + JSON.stringify(url) + ";";
    }
````

**Comment by michael-ciniawsky** [comment]
@coderwin Please provide more info about your current setup (`webpack.config.js`), but I'm uncertain if this is possible (multiple publicPath). Why not `cdn.com.cn/js` `cdn.com.cn/css`, `cdn.com.cn/img` ?

**Comment by coderwin** [comment]
@michael-ciniawsky 
Domain divergence，there are too many static resources(js/css/img)
