### ISSUE TITLE
Document the argument outputPath

### ISSUE THREAD

**Issue by serut** [webpack-contrib/file-loader#134]
Hello and thanks for this awesome package,
I just upgrade my app from webpack 1 to 2 and I loosed some time to fix image render threw `webpack-dev-server` 

**What is the current behavior?**
I though that the `outputPath` was a relative path to the folder where this plugin will save my files, from where the `webpack.config` file is. And that's not the case. The file will be moved to `output.path` (webpack config key) + your `outputPath`. 

**What is my expectation?**
As an end user, I don't want to guess what is the behaviour of yours arguments. Can you explain on your README what is the purpose of each arguments ?

**Comment by michael-ciniawsky** [comment]
@serut Mind to spin up a quick PR about this 😛 ?

**Comment by serut** [comment]
If I was sure to be to able to explain it, would be glad to create the PR, but that's not the case ...

**Comment by michael-ciniawsky** [comment]
@serut kk I will address it then when I have time, but it's no problem in case the first attempt isn't 💯 though 😛
