### ISSUE TITLE
How to use file-loader?

### ISSUE THREAD

**Issue by joetidee** [webpack-contrib/file-loader#137]
Looking at the documentation it is not obvious how to use static images. For example:

My images are stored in /public/assets/img

In one of my application pages (/src/somePage.js) I am creating the src attribute for an image dynamically:

let imgSrc = "public/assets/img/" + imageId + ".jpg";

<img src={imgSrc} />

When viewing in the browser, the images cannot be found.

**Comment by michael-ciniawsky** [comment]
@joetidee Please provide more info about your current setup (file tree, `webpack.config.js`)
