### ISSUE TITLE
Loader options plugin for webpack 2 causes file names to become a random hash

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack-contrib/file-loader#138]
Webpack: 2.2.1
File-loader: 0.10.1

Using the "loader options" object causes file loader to ignore the naming structure given to the query.
Example:

```
                   loader: 'file?name=assets/images/[name].[ext]'
```
The above works as expected, outputing the files into `/assets/images` and the name remains the same i.e. `hello.png` stays `hello.png`

However:
```
               {
                  loader: 'file',
                  options: {
                     query: {
                        name: 'assets/images/[name].[ext]'
                     }
                  }
               },
```
Using this does not produce the desired results. It outputs ALL the assets into the root compilation directory `/` and renames every asset into `[hash].[ext]` like `bb842ac002ae76a8ac73a978de184da0.png`

This appears to be a bug.

**Comment by FranzSkuffka** [comment]
I have the same issue.
```
      {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: 'file-loader?name=../[path]/../[name].[ext]',
        options: { context: '/'}
      }
```

**Comment by fmakdemir** [comment]
I have the same problem and it seems like it can't load options field and since default name is `[hash].[ext]` all files are written as hashes on Webpack2.
It tries to load from `this.options` and when I checked it had no `fileLoader` property which the file-loader expects it to have.

**Comment by FranzSkuffka** [comment]
Thank you, @fmakdemir.
However I was not combing it with query options though.

**Comment by fmakdemir** [comment]
@FranzSkuffka you wrote `loader: 'file-loader?name=../[path]/../[name].[ext]'` alongside `options` that is mixing them :) Part after `?` is the query options and you also have `options` property set. `file-loader` ignores query options when both are present from what I could find.

**Comment by nucklearproject** [comment]
Same Issue...
Deleting or comments "options" work,   

"file-loader": "^0.10.1",
"webpack": "^2.2.1",
"webpack-dev-server": "^2.2.0-rc.0"

`{
        test: /\.(png|jpg)$/,
        use: [{
       
          loader: 'file-loader?name=img/[name].[ext]',
         //loader: 'file-loader',

/*  options: {
              query: {
                        name: 'img/[name].[ext]'
                     }
          } */
        }]
      },`

**Comment by michael-ciniawsky** [comment]
@IAMtheIAM 

**webpack.config.js**
```js
{
    loader: 'file-loader',
    options: {
       name: 'assets/images/[name].[ext]'
    }
},
```

@FranzSkuffka 

**webpack.config.js**
```js
  {
    test: /\.(eot|svg|ttf|woff|woff2)$/,
    use: {
       loader: 'file-loader'
       options: {
            context: '/', // check if '/' => './'
            name: '../[path]/../[name].[ext]', // check the various '../'
      }
}
```

@nucklearproject 
**webpack.config.js**
```js
  {
    test: /\.(png|jpg)$/,
    use: {
       loader: 'file-loader',
       options: {
            name: 'img/[name].[ext]', // check the path
      }
}
```

Reopen if still regressions 😛

**Comment by fmakdemir** [comment]
@michael-ciniawsky wouldn't it be better to put an example config with some explanations or fix for using query options along with loader options? I had to dig to source codes to find out why it was acting weird..

**Comment by michael-ciniawsky** [comment]
@fmakdemir Yeah... 😛  I'm on a README overhaul journey for most of the loaders here, so soon...

**Comment by fmakdemir** [comment]
😄 I support you whole heartedly.
