### ISSUE TITLE
Can I get module name in filename template placeholders?

### ISSUE THREAD

**Issue by ThomasSoloist** [webpack-contrib/file-loader#144]
I set up webpack's entry property like:

```javascript
{
    entry:{
        about:"path/to/index.js"
    }
}
```

In index.js, I use html-loader to require html files, And use extract-loader & file-loader to out put html files, such as 

```javascript
require('html/homepage.html');
//NOTICE that the html file name is different to the entry module's name.
//And I need this html file name will same as the entry module name, it will be 'about.html'.
```

And I want to use the module name (that set up in webpack's 'entry' property) to out put the html files.

maybe it will like：file-loader?name=[module].[ext]!extract-loader!html-loader, and output is "about.html"

So that it will be: module entry js file auto stand for a same name html file.

Thanks for your time.

And my English is awful, so I made a picture so that can make it easier to understand.

Thanks.

![artboard](https://cloud.githubusercontent.com/assets/12109558/24701614/a5f1552e-1a2d-11e7-91b5-76ecdb58067f.png)

**Comment by michael-ciniawsky** [comment]
@ThomasSoloist  Did you try `file-loader?name=[name].[ext]!extract-loader!html-loader` ?

`[module]` => `[name]`

**Comment by ThomasSoloist** [comment]
@michael-ciniawsky I have set the loader in webpack such as `file-loader?name=[name].[ext]!extract-loader!html-loader`, if I have a 'homepage.html' then it will output 'homepage.html', and it works fine.

But I need the html file name is same as the webpack entry module name when output. Like I require the html file in the entry of 'about' module, then the html file will output with the name of 'about.html'.

Can file-loader do that?

Thanks.

**Comment by ThomasSoloist** [comment]
@michael-ciniawsky Eh, I have find a same feature request in issue #114 (https://github.com/webpack-contrib/file-loader/issues/114) that we all need to output the files or folders with the name based on entry modules. Should I close this issue? Thank you again.

**Comment by michael-ciniawsky** [comment]
@ThomasSoloist Yep I will triage this at #114 then :), please feel free to join discussion there
