### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by grvcoelho** [webpack-contrib/file-loader#147]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
If I use file-loader to transpile `.js` files, sourcemaps are not added to the individual files but only to the main bundle file (using `source-map-loader`).

**If this is a feature request, what is motivation or use case for changing the behavior?**

It would be nice to have source-maps support on files that passes through file-loader

**Comment by michael-ciniawsky** [comment]
Why are you loading `.js`files via file-loader ? 😛 Just `import/require()` them :) webpack has buildin JS support (it only runs on JS), for other files it highly depends, if the file is parsable and provides source location info to generate the maps. HTML/SVG could have sourcemaps in theory for e.g but no browser devtools actually would support them (JS/CSS only).PNG/GIF/FONTS on the otherhand do not (to my knowledge). In any case sourcemap support for `file-loader` doesn't really make sense nor would it be easily achievable. Why do you need sourcemaps for assets?

**Comment by raxim1** [comment]
To make an entry on webpack.config.js does not solve the issue, that i would like to load new Worker("jsfile") - at that time the web worker has been transpiled to js from ts

**Comment by raxim1** [comment]
worker-loader is not working anyway
