### ISSUE TITLE
output images are in parent folder when useRelativePath option is true

### ISSUE THREAD

**Issue by nopantsmonkey** [webpack-contrib/file-loader#149]
My webpack file
```
import CleanWebpackPlugin from 'clean-webpack-plugin';
import StyleLintPlugin from 'stylelint-webpack-plugin';
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import combineLoaders from 'webpack-combine-loaders';
import {modulesRoot, root, staticRoot} from './helpers';

const projectRootPath = root('.');
const modulesPath = modulesRoot();
const buildPath = staticRoot();

export default (env) => {
	let proMode = env.toLowerCase() !== 'production';

	return {
		devtool: proMode ? 'source-map' : 'eval',

		entry: {
			'css/web/home/styles': 'css/web/home/styles.pcss'
		},

		output: {
			path: buildPath,
			publicPath: buildPath,
			filename: proMode ? '[name].[chunkhash].css' : '[name].css',
			sourceMapFilename: proMode ? '[name].[chunkhash].map' : '[name].map'
		},

		resolve: {
			modules: [projectRootPath, modulesPath, root('images')],
			extensions: ['.pcss']
		},
		module: {
			rules: [
				{
					test: /\.(jpe?g|png|webp|svg|gif|cur)$/i,
					loader: 'file-loader',
					options: {
						name: '[path][name].[hash].[ext]',
						publicPath: '../../'
					}
				},
				{
					test: /\.pcss$/,
					loader: ExtractTextPlugin.extract({
						use: combineLoaders([
							{
								loader: 'css-loader',
								options: {
									importLoaders: 1,
									sourceMap: proMode,
									url: true
								}
							},
							{
								loader: 'postcss-loader',
								options: {
									sourceMap: proMode ? undefined : 'inline'
								}
							}
						])
					})
				}
			]
		},
		plugins: [
			...(env === 'watch' ? [] : [new CleanWebpackPlugin(['build'], {root: projectRootPath, verbose: true})]),
			new StyleLintPlugin({files: 'css/**/*.pcss'}),
			new ExtractTextPlugin({filename: (proMode ? '[name].[chunkhash].css' : '[name].css'), allChunks: true})
		],
		stats: {
			assets: true,
			children: false,
			chunks: true,
			chunkModules: true,
			chunkOrigins: true,
			colors: true,
			errors: true,
			errorDetails: false,
			hash: false,
			modules: false,
			reasons: false,
			source: true,
			timings: true,
			version: true,
			warnings: true
		},
		node: {
			global: true,
			crypto: 'empty',
			process: true,
			module: false,
			clearImmediate: false,
			setImmediate: false
		}
	};
};
```
My folder structure
```
|-
|----css/
|--------web/
|-------------home/
|-------------------style.pcss
|-------------app/
|-------------------app.pcss
|------------desktop/
|-------------------desktop.pcss
|----images/
|-------------home/
|-------------------image1.jpg
|-------------app/
|-------------------image2.jpg
|------------desktop/
|-------------------image3.jpg

`

when i am building my project with above config
my build folder structure is
```

|-
|----build/
|---------css/
|--------------web/
|-------------------home/
|-------------------------style.css
|-------------------app/
|-------------------------app.css
|--------------desktop/
|-----------------desktop.css
|---------images/
|--------------web/
|-------------------home/
|-------------------------image1.jpg
|-------------------app/
|-------------------------image2.jpg
|--------------desktop/
|-------------------------image3.jpg

`

but since i am specifying public path ('../../') 
background: url(../../image/desktop/image3.jpg) in my desktop.css are working correctly 

but web/home/style.css 
background: url(../../image/web/home/image1.jpg) in style.css is not correct (correct path should be ../../../image/desktop/image3.jpg)

then i tried 
```

				{
					test: /\.(jpe?g|png|webp|svg|gif|cur)$/i,
					loader: 'file-loader',
					options: {
						name: '[name].[hash].[ext]',
						useRelativePath: true,
						publicPath: url => url
					}
				}

```

then the css files are creating correct paths
for desktop background: url(../../image/desktop/image3.jpg)
for web/home background: url(../../image/web/home/image1.jpg)

but images folder is not in build directory 
desktop images are in the project's parent folder (../../)
and web/home images in  project's parent's parent folder (../../../)

**How to create images folder in build/ and have the same paths as with useRelativePath?**

**Comment by michael-ciniawsky** [comment]
@nopantsmonkey You can't use `.css` files as entry points, webpack entrys are JS only

**Comment by michael-ciniawsky** [comment]
and please  add the \``` around the code it's very hard to read atm :stuck_out_tongue:

**Comment by nopantsmonkey** [comment]
i 've created a repo for you with the issue 
and added both options that i am using with file-loader
please toggle options and check i 've also added some description with options

Commands
```
npm run build
npm run build:prod
```
Repo URL:
[file-loader-relative-path-issue](https://github.com/nopantsmonkey/file-loader-relative-path)

**Comment by michael-ciniawsky** [comment]
@nopantsmonkey kk i will take a look into it soon

**Comment by nopantsmonkey** [comment]
yes @adriancmiranda it is working as expected.
should i create a fork of file-loader with your changes or will this at any point get merged in this repo?

**Comment by michael-ciniawsky** [comment]
@nopantsmonkey If #150 contains this, it's likely to land soon :)

**Comment by nopantsmonkey** [comment]
should i close this issue now or you 'll close it after the release of file-loader with #150

**Comment by michael-ciniawsky** [comment]
@nopantsmonkey I will close it when #150 lands :)

**Comment by nopantsmonkey** [comment]
@adriancmiranda  i think there is some problem between the [repo](https://bitbucket.org/adriancmiranda/pr-file-loader/src/489f5e70002496b4098a283b1a794643ee0869e7/?at=file-loader-relative-path-issue) you asked me to verify and the code in #150 
because if i am changing the local file-loader in the above code with the file-loader of #150 [(adriancmiranda/file-loader)](https://github.com/adriancmiranda/file-loader) and renaming `textOutputPath: ''` with `cssOutputPath: ''` it is not creating the same urls as it was creating with the above code

images paths using above repo
`../../images/desktop/spacer.ed280a0ea3cc38f3cbbc747acfbef47d.gif`

images path with (adriancmiranda/file-loader:master)
`images/desktop/spacer.ed280a0ea3cc38f3cbbc747acfbef47d.gif`

**Comment by adriancmiranda** [comment]
@nopantsmonkey No, it's right, [line 18](https://github.com/adriancmiranda/file-loader/blob/master/index.js#L18) I changed the defaults to empty and I changed the [line 75](https://github.com/adriancmiranda/file-loader/blob/master/index.js#L75) too.
In master, we have two CSS files with a single output (most of the cases).
In yours, we have a multiple output path

So, I think in two ways of dealing with this case.
The first is using a multi-compiler for your webpack.config and another is ignoring [this](https://github.com/adriancmiranda/file-loader/blob/master/index.js#L75) statement with `undefined`, for example

**Comment by nopantsmonkey** [comment]
it is working for me with cssOutputPath: undefined

**Comment by doomsbuster** [comment]
I am running into similar challenge and no combination of flags seems to fix the issue. My setup is like this:

```
// Project folder structure
root-app-dir
  |_ public
      |_ style
  |_ui
     |_ images
        |_ science.jpg
     |_ styles
        |_main.less
```
My `file-loader` config is as below:
```
// webpack.config.js
{
	test: /\.(png|jpe?g|gif|svgz?)$/i,
	include: path.resolve(__dirname, 'ui/images'),
	use: {
		loader: 'file-loader',
		options: {
			useRelativePath: true
		}
	}
}
```
```
//public/style/main.less
.content-container {
	padding: 24px;
	background-image: url(../images/science.jpg);
	background-size: cover;
	background-position: fixed;
}
```

This copies the images directory under the `root-app-dir` instead of copying it to `public/images` directory. No combination of `outputPath`, `useRelativePath` or `context` seem to fix the issue. If i remove the `useRelativePath`, it creates images directory in correct location, but it changes the CSS rule to `background-image: url(images/science.jpg);` and the UI gets a 404 since the images directory is one level up.

**Comment by adriancmiranda** [comment]
@doomsbuster `loader: 'file-loader'` probably isn't the correct version 'cause [I'm waiting for a review yet](https://github.com/webpack-contrib/file-loader/pull/150#issuecomment-336943061).

**Comment by doomsbuster** [comment]
I am using ` "file-loader": "^0.11.1"` in my project.

**Comment by adriancmiranda** [comment]
@doomsbuster I mean, [this is the fixed version tested here at this thread](https://bitbucket.org/adriancmiranda/pr-file-loader/src/489f5e70002496b4098a283b1a794643ee0869e7/loaders/file-loader.js?at=file-loader-relative-path-issue&fileviewer=file-view-default). There's no merge for it yet.

**Comment by Cap32** [comment]
I have the same problem.

Here's my temporary solution inspired by https://github.com/webpack-contrib/file-loader/pull/150#issuecomment-339304260

```js
{
	test: /\.(png|jpe?g|gif|svgz?)$/i,
	include: resolve('src'),
	use: [
		
		// Don't emit file here, just override the url below
		{
			loader: 'file-loader',
			options: {
				useRelativePath: true,
				publicPath: '',
				name: '[name].[ext]',
				emitFile: false,
			},
		},

		// Just emit file here, the compiled url would be overridden
		{
			loader: 'file-loader',
			options: {
				publicPath: '',
				context: resolve('src'),
				name: `[path][name].[ext]`,
			},
		},
	],
},
```

It is ugly, but it works

**Comment by evilebottnawi** [comment]
Option `useRelativePath ` was removed. Why https://github.com/webpack-contrib/file-loader/issues/261#issuecomment-449007163

**Comment by BehnamCoding** [comment]
> I have the same problem.
> 
> Here's my temporary solution inspired by [#150 (comment)](https://github.com/webpack-contrib/file-loader/pull/150#issuecomment-339304260)
> 
> ```js
> {
> 	test: /\.(png|jpe?g|gif|svgz?)$/i,
> 	include: resolve('src'),
> 	use: [
> 		
> 		// Don't emit file here, just override the url below
> 		{
> 			loader: 'file-loader',
> 			options: {
> 				useRelativePath: true,
> 				publicPath: '',
> 				name: '[name].[ext]',
> 				emitFile: false,
> 			},
> 		},
> 
> 		// Just emit file here, the compiled url would be overridden
> 		{
> 			loader: 'file-loader',
> 			options: {
> 				publicPath: '',
> 				context: resolve('src'),
> 				name: `[path][name].[ext]`,
> 			},
> 		},
> 	],
> },
> ```
> 
> It is ugly, but it works
