### ISSUE TITLE
mp3 not found

### ISSUE THREAD

**Issue by LucasBassetti** [webpack-contrib/file-loader#151]
Hi,

I'm try to create a react component that use a mp3 file. I'm publish it as a npm package. So, when I install it in some application using `npm install myLib` I get an error `404 not found` in my mp3 file.

My webpack prod config:

```
const webpack = require('webpack');
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
  entry: path.resolve(__dirname, 'lib/index'),
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'myLib.js',
    publicPath: 'dist/',
    library: 'myLib',
    libraryTarget: 'umd',
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new webpack.optimize.UglifyJsPlugin({
      minimize: true,
      compress: false,
    }),
  ],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loaders: ['babel'],
      },
      {
        test: /\.mp3$/,
        loader: 'file-loader',
      },
    ],
  },
};
```

Example of how I'm calling the mp3 file in development environment (here works fine):

```
const notification = require('./notification.mp3');
const audioPlayer = new Audio(notification);
audioPlayer.play();
```

Result of webpack production build:

![image](https://cloud.githubusercontent.com/assets/1014326/25165463/0abe9514-24ad-11e7-9611-14d8a3fcb5a1.png)

More details:
* webpack: 1.13.0
* file-loader: 0.11.1
* node: 6.9.1

Anybody know how to solve this?

**Comment by evilebottnawi** [comment]
@LucasBassetti why your use `copy` plugin for this, your can use `require('./path/to/my.mp3')` (example i store files in `src/static` and have `src/app.js`, inside `src/app.js` i use `require(''./static/my.mp3)`)? Don't move manually files which use in require, it is can break path to files

**Comment by LucasBassetti** [comment]
The problem is that I need generate a npm package with the mp3 dependency, i. e., when I install my react package using `npm i myLib` and rendered with `<MyLib />` I need keep the dependency with my mp3 file.

**Comment by evilebottnawi** [comment]
@LucasBassetti I understand what exactly is being done wrong? I just do not understand why to use `CopyWebpackPlugin`, webpack hadles all, just use `var url = require('my.mp3')` and just insert your url

**Comment by michael-ciniawsky** [comment]
@LucasBassetti In this case you will need to reference the `.mp3` yourself aswell, webpack doesn't automatically load component assets from packages for you `import mp3 from 'path/to/package/path/to/file.mp3`. See [Resolve](https://webpack.js.org/configuration/resolve/) for possible options and maybe the webpack short hand `~` for `node_modules` works `import mp3 from `~package/path/file.mp3`

**Comment by LucasBassetti** [comment]
Alright! Thank you guys!

**Comment by michael-ciniawsky** [comment]
@LucasBassetti If still regressions feel free to reopen 😛

**Comment by LavaRiddle** [comment]
@LucasBassetti 

How did you resolve this in the end? 

I've got a very similar project - a react application that is being developed in a `module` folder, and for development purposes I have an `application` folder also at root level that is a separate small site running on an express server for the purposes of importing the react application from `module` and placing into a portion of the site for testing.

The react application in `module` is bundled into a dist with webpack. This module uses a small .mp3 file as notification sound as part of the application. 

Using webpacks file-loader it manages to get a copy of the file and place the hashed copy into the dist directory. 

When running the application in situ as an imported module. It can't seem to find the file as it's looking for the file in the root directory.

Did you experience something similar?

**Comment by shubham-harsh** [comment]
Hi,
I am trying the same thing and getting 404. can someone please guide me on how to fix this?

**Comment by shubham-harsh** [comment]
@LavaRiddle or @LucasBassetti can you guys please tell me how to fix this?
