### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by neal-eiger** [webpack-contrib/file-loader#154]
Hi, it would be helpful in the readme to give a small full example (for dev and prod) before discussing the finer points, for example using an angular 2 project something like:

```
webpack.config.js       // {test: /\.(jpg|png|gif)$/, use: 'file-loader?name=statics/[name].[ext]' },
src/index.html             // img src="statics/index_image.png"
src/app/app.template.html     // img src="statics/app_image.png"
src/app/app.component.ts     // import '../../assets/images/app_image.png'
src/assets/images/index_image.png
src/assets/images/app_image.png
```

**Comment by michael-ciniawsky** [comment]
Yep we work on README overhauls and standardization it's just WIP atm :). Please wrap the paths in \``` for better readability

**Comment by evilebottnawi** [comment]
Let's move this issue to https://github.com/webpack-contrib/file-loader/issues/152
