### ISSUE TITLE
OutputPath is joined with publicPath?

### ISSUE THREAD

**Issue by michaelmano** [webpack-contrib/file-loader#160]
I have set up file loader for fonts however its not working as I thought it would.
my output path is completely different from my public path so I thought by declaring the locations in parameters this would work. e.g.
```
{
  test: /\.(eot|svg|ttf|woff|woff2)$/,
  loader: 'file-loader?name=[name].[ext]&outputPath=fonts/&publicPath=__fonts/'
}
```
the SRC the css should be using is __fonts/name.ext and the files location should be in /fonts/name.ext

but this is not what is happening.
instead im getting
`src: url(__fonts/fonts/font-name.ttf);`

**Comment by ronar** [comment]
I've the same issue. When I point out the outputPath, the final file path gets concatenated with the public path. It shouldn't be happening.

```javascript
const image = require('../images/image.png');
```

My config:
```javascript
{
  test: /\.(png|jpe?g|gif|svg)$/,
  loader: 'file-loader?name=[hash].[ext]&outputPath=../assets/images/&publicPath=assets/images/'
}
```

I get this string `http://{server}/assets/images/../assets/images/image.png`. Which is definitely wrong.

**Comment by SachinVarghese** [comment]
I have the same issue. Am I not using it right? Can someone define the output Path and public Path keys?

**Comment by dirago** [comment]
Same error here, impossible to understand why

**Comment by dirago** [comment]
Waiting for the fix :

Instead of:

```
{
  test: /\.woff$|\.woff2?$|\.ttf$|\.eot$|\.otf$/,
    loader: 'file-loader',
    options: {
        name: '[name].[ext]',
        outputPath: 'public/fonts/',
        publicPath: '../fonts'
    },
},
```

What I did :

```
{
  test: /\.woff$|\.woff2?$|\.ttf$|\.eot$|\.otf$/,
    loader: 'file-loader',
    options: {
        name: 'public/fonts/[name].[ext]',
        publicPath: function(url) {
          return url.replace(/public/, '..')
        },
    },
},
```
It's kind of tricky, but it's actually works

**Comment by Coriou** [comment]
I also experience the same issue

**Comment by BennieCopeland** [comment]
Same issue, but this worked:
`'file-loader?name=[name].[hash].[ext]&outputPath=fonts/&publicPath=../'`

Directory structure is:
```
dist
- fonts
  - font-awesome.1234.woff
  - font-awesome.1234.eot
- css
  - styles.css
```

In my css, the path gets set to `../fonts/font-awesome.woff` and the files are output to the `fonts` directory under `dist`.

**Comment by michaelmano** [comment]
so my issue was more that the url is different from the directory structure. Im lucky that the only difference was the 2 underscores.. If someone has a site where the url is completely different from the directory structure this would be a big issue as here is my fix
`loader: 'file-loader?name=[name].[ext]&outputPath=lib/web/fonts/&publicPath=/__'`
so that the public path is now site.com/__lib/web/fonts/

**Comment by v99895** [comment]
Same error here, impossible to understand why too

**Comment by subramGrg** [comment]
i was having this same issue. however while scouring the internet came across this:

[Git commit](https://github.com/webpack-contrib/file-loader/pull/146/files?diff=unified)

that entails:

`outputPath: defines sub-dir relative to "dist" folder, in which all the image files whould be placed (if not specified all the image files will be placed directly in the "dist" folder)`

`publicPath: defines path which should be prefiex to outputPath inside the CSS files (if not specified it will default to "./dist" ... or whatever dir was specified in webpack "output" config)` 

What i dont understand is why isnt this on webpack's file-loader Git page? FYI: im still new to Github

**Comment by gurianov-p** [comment]
I have same error in 0.11.2, but version 0.10.0 works fine

**Comment by jimblue** [comment]
thanks @dirago your temporary solution works great. waiting for the fix too!

**Comment by nickhstr** [comment]
Same issue here. Downgraded to 0.10.1 and the issue is gone.

**Comment by ctrlaltdylan** [comment]
I wonder if this is related, but it seems that `output.publicPath` is not being respected by the file-loader.

I have an absolute path set on `output.publicPath` for `localhost:8080/static`. The bundle attempts to find the file-loaded assets at `localhost:3000/static`.

**Comment by RobinMob** [comment]
I've been searching for a solution for a while. I couldn't get webpack to get the correct path to my images in my '*.css' file. The solution using  "publicPath: function(url ..... " works great for me. 
Thank you @dirago 

My file structure is:
```
myProject/dev/
          |
          css/
          |---- base.scss
          |---- test.scss
          images/  
          |---- test.png
          js/
          |---- script.js

myProject/dist
          |
          css/
          |---- style.css
          images/
          |---- test.png
          js/
          |---- script.js
```

base.scss looking like this:
```
@import 'test';
```
test.scss looking like this:
```
.my-wrapper {
      .nested-div {
        background-image: url('../images/test.png');
        background-size: cover;
        .....
     }
}
```


My webpack.config.js is:

```
var webpack = require('webpack');
var path = require('path');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: {
        dist: [
            './dev/js/script.js'
        ]
    },
    output: {
        path: path.resolve(__dirname, './dist/'),
        filename: 'js/[name].js'
    },
    module: {
        rules: [
            {
                test: /\.s[ac]ss$/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader', 'sass-loader'],
                    fallback: 'style-loader'
                })
            },
            {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: 'images/[name].[ext]',
                            publicPath: function(url) {
                                return url.replace(/images/, './../images/');
                            }
                        }
                    }
                ]
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('css/[name].css')
    ]
```

I discovered both following solutions to my images path work:

solution with a publicPath function:

```
            {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: 'images/[name].[ext]',
                            publicPath: function(url) {
                                return url.replace(/images/, './../images/');
                            }
                        }
                    }
                ]
            }
```

solution with ouputPath and publicPath:

```
            {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                            outputPath: './images/',
                            publicPath: './.'
                        }
                    }
                ]
            }

```

I hope this extra info is helpfull

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/file-loader/pull/246

**Comment by vladadementieva** [comment]
@dirago, thanks a lot!

**Comment by ErikGMatos** [comment]
Thank you very much, solved my problem.
vwwwwww

**Comment by ErikGMatos** [comment]
@dirago  Thank you very much, solved my problem.
vwwwwww

**Comment by ErikGMatos** [comment]
@dirago  Thank you very much, solved my problem.
vlw!!!

**Comment by jayhill90** [comment]
> It's kind of tricky, but it's actually works

Worked great!
