### ISSUE TITLE
Unexpected character '�', when bundling fonts

### ISSUE THREAD

**Issue by james-prado** [webpack-contrib/file-loader#161]
I'm successfully bundling my css with webpack, however when I try to bundle fonts.scss which contains all my `@font-face` statements,  webpack throws me this strange error.

The error:
```
Uncaught Error: Module parse failed: electron-app/src/assets/fonts/roboto/Roboto-Thin.ttf Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
```

For reference my `@font-face` statements look like this (but with a few more fonts):
```
@font-face {
	font-family: 'Roboto';
	font-style: normal;
	font-weight: 100;
	src: url('./assets/fonts/roboto/Roboto-Thin.ttf');
}
```

webpack.config.js
```
module.exports = {
  devtool: "source-map",
  output: {
    publicPath: "http://localhost:8080/"
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: "babel-loader"
      },
      {
        test: /\.(css|scss)/,
        use: [
          { loader: "style-loader" },
          { loader: "css-loader" },
          { loader: "sass-loader" }
        ]
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
		loader: "file-loader"
      }
    ]
  }
};
```

My File Structure:
```
├── package.json
├── src
│   ├── app.js
│   ├── assets
│   │   └── fonts
│   │       └── roboto
│   │           ├── Roboto-Light.ttf
│   │           ├── Roboto-Medium.ttf
│   │           ├── Roboto-Regular.ttf
│   │           ├── Roboto-Thin.ttf
│   ├── components
│   │   ├── app.jsx
│   │   └── example.jsx
│   ├── index.html
│   ├── index.js
│   ├── index.scss
│   └── styles
│       ├── example.scss
│       └── fonts.scss
└── webpack.config.js
```

Link to the repo [here](https://github.com/james-prado/electron-react-app/tree/master)

Webpack v2.3.1,
NodeJS v6.10.2,
Electron v1.6.6,
File-loader v0.11.1

**Comment by evilebottnawi** [comment]
@james-prado try to update `css-loader`, `style-loader` and `sass-loader` to latest versoin

**Comment by james-prado** [comment]
All my loaders are on the latest version, 
css-loader v0.28.1,
style-loader v0.17.0
sass-loader v6.0.5

if it helps [here's](https://github.com/james-prado/electron-react-app/tree/master) a link to the repo

**Comment by james-prado** [comment]
Nevermind, seems I made a silly mistake and was importing a font I didnt have in my assets
