### ISSUE TITLE
Forwarding Data to other chained loaders

### ISSUE THREAD

**Issue by zouhir** [webpack-contrib/file-loader#164]
Hi, thanks all for this great loaders. I made [lqip-loader](https://github.com/zouhir/lqip-loader) for webpack and I am curious if `file-loader` ability to forward data (path) to other loaders could be supported. I'm happy to help and would be proud to contribute where I can.

### What I found challenging:

> `webpack.config.js`

```
"loaders": ["lqip-loader", "file-loader"]
```
> `lqip-loader`

inside my loader I get a `string` value from `file-loader` of `"module.exports = __... .jpg"` and to consume that in my loader I have to go through some string manipulation of regex and replacing which I felt could have been done differently.

Happy to know what kind of thoughts you have in order for developers to easily and safely chain after file loader.

Many thanks!

**Comment by evilebottnawi** [comment]
@zouhir Can use provide use case and which `string manipulation` your did? Maybe we can found other solution to this, thanks!

**Comment by zouhir** [comment]
@evilebottnawi thanks for getting back!

When I pipe my loader after `file-loader` I don't get a file path, instead I get something like:

```js
"module.exports = /assets/media/images/sky.jpg"
```

and to use it inside my loader I have to do something like:

- string trim white spaces
- string replace `module.exports` with ``
- string replace `"` with ``
- string replace `=` with ``

and then I'll end up with 

```js
"/assets/media/images/sky.jpg" 
```

which I wanted.

is there a way to pass data from file-loader to other loader where we get the file path without having to do all that string replace? the only reason I didn't keep it is because I thought it's probably not the right way to pass things after file-loader

I'm happy to collaborate further @evilebottnawi please let me know how can I make things clearer.

**Comment by evilebottnawi** [comment]
@zouhir why don't use only `lqip` `"loaders": ["lqip-loader"]`?

**Comment by lukeed** [comment]
I imagine that something like this is what @zouhir wants:

```js
module: {
  rules: [{
    test: /\.(jpg|png)$/,
    loader: 'file-loader!lqip-loader'
  }]
}
```

This way, `file-loader` should return its file paths (or files) so that other chained loaders may work with the same files. _FWIW, I don't know if this is what currently happens, but I would expect this to be the behavior._

I may be wrong/misunderstanding. Just trying to rephrase the question since there seems to be a disconnect here 😬

**Comment by michael-ciniawsky** [comment]
**file-loader**
```diff
- return `export default = ${publicPath};`;
+ this.callback(null, `export default = ${publicPath};`, null, { publicPath });
+ return;
```

**lqip-loader**
```js
export default function loader (src, map, meta) {
   ...
   console.log(meta.publicPath) // <=
}
```

@zouhir `lqip-loader` seems to be a pitching loader, could you elaborate on the dataflow a bit please and why `file-loader!lqip-loader` isn't sufficient :) ?

**Comment by zouhir** [comment]
@michael-ciniawsky you response seem to cover my issue 100%.

Returning the callback you just added in the snippet above rather than a string will solve the issue.

I prefer to have a proper flow and not a pitching loader, and be able to link with other loaders, especially `file-loader`. but I decided to hold on a bit to learn how can I pipe my loader after `file-loader` in a proper way, no other reason `lqip-loader` has to be a pitching loader.

would a PR with your snippet above be welcomed or it already exist?

many thanks to @evilebottnawi and @lukeed as well

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can we add option `export` (maybe best name) for this purpose?

**Comment by michael-ciniawsky** [comment]
@zouhir Yep, PR welcome of course 😛 

@evilebottnawi Why better as an extra option ? 🙃

**Comment by evilebottnawi** [comment]
@michael-ciniawsky hm, we will don't breaking something?

**Comment by michael-ciniawsky** [comment]
We need to check if `loader-runner` only returns the src param of the last loader or the whole callback in case the loader is the last in the chain yep. Otherwise an option is required, but this is nearly a deal breaker imho, since it adds 'unnecessary' complexity and isn't a generic enough usecase

**Comment by cduivis** [comment]
For our company we needed something similar only it's the reverse of what is mentioned here.
So we have adjusted [file-loader](https://github.com/NetMatch/file-loader) to 'pitch' the outputPath of the file towards all loaders next in the chain, so they in turn can use it if they want to (mainly to resolve relative paths). 
We also wrote an update on the [extract-loader](https://github.com/NetMatch/extract-loader) which then consumes this data to output relative paths instead of static paths.

I still want to do a final review of the code and remove some items before I'll make a PR.
I don't know if I should link it to this Issue as it may seem to be a slightly different one, but let me know.

**Comment by evilebottnawi** [comment]
@cduivis hm, PR welcome, maybe with code problem will be solved faster

**Comment by cduivis** [comment]
The PR is created : 
https://github.com/webpack-contrib/file-loader/pull/321

**Comment by evilebottnawi** [comment]
`file-loader` and `url-loader` will be deprecated after `webpack@5` release in favor `asset` module type https://webpack.js.org/guides/asset-modules/, so we can't accept features anymore, we will update docs how you can modify runtime and source to implement same logic for `asset` module type, sorry for delay, we have very many work, using regexp to get filename is good workaround right now
