### ISSUE TITLE
Add [id] placeholder support for name property

### ISSUE THREAD

**Issue by devrafalko** [webpack-contrib/file-loader#176]
Lets assume that I use `file-loader` this way:

```javascript
{
  test: /\.html$/,   
  loader: 'file-loader',
  options:{
    name: "[name].[ext]",
    outputPath: 'dist/'
}
```
When I have got 2 entry points of the same name, but in different directories, eg.
* `src/componentA/template.html` 
* `src/componentB/template.html`

and want to emit them as separate chunks to my `dist` folder, the one file **overwrites** another file and it is not desirable behaviour.

I can of course change name property for `name:[name][hash].[ext]` and it does the trick, but I just want to separate files of the same names, not to solve cache problems and what's more, if I emit eg. `.html` files as in the example and use `dev-server`, it emits new hashed `.html` file on every build *(when I edit html files)* what is not recommended as mentioned in this [webpack-dev-server issue](https://github.com/webpack/webpack-dev-server/issues/438).

The [id] placeholder indicating the number of the chunk would be the best way to get what I want. The `output.filename` and `extract-text-webpack-plugin` supports [id] for example. Would it be possible to add [id] placeholder support or maybe there's any other solution of my problem?

**Comment by michael-ciniawsky** [comment]
`[path]` ?

**Comment by evilebottnawi** [comment]
@devrafalko Thanks for issue! Duplicate https://github.com/webpack-contrib/file-loader/issues/114
