### ISSUE TITLE
Set specific path for file-loader to look for assets

### ISSUE THREAD

**Issue by jewbetcha** [webpack-contrib/file-loader#180]
I'm using `file-loader` along with `extract-loader` and `html-loader` to process images within some generated static HTML (Hugo is the generator).

The generated HTML and assets are all under a `public/` folder, the structure is:
```
webpack.config.js
public/
    index.html
    images/
    some-path/
    |   index.html
    |   another-path/
    |   |    index.html
```
etc. 

All images are referenced absolutely as `/images/image.png` from all HTML files. Some are at a path like `/images/foo/bar/image.png`.

I have successfully gotten Webpack to process all of the HTML files, but since the images all come with absolute paths it doesn't know where to find them in the context of my project root (at least with my current config). I have also successfully processed a single HTML file _and_ its images by altering the image paths of that single file, so I know the config _works_ in that regard. The image paths were hashed in HTML and the image filename was also hashed.

**Is there a way I can tell `file-loader` and Webpack where to find these images, without manually altering their path in the HTML?**

Here is my current config:

```javascript
           test: /\.(png|jpg|svg)$/, 
                use: [{
                    loader: "file-loader?outputPath=images/",
                    options:  {
                        limit: 10000,
                        emitFile: true,
                        useRelativePath: true
                    }
                }] 
            },
            {
                test: /\.html$/,
                use: [
                    "file-loader?name=[name].[ext]",
                    "extract-loader",
                    "html-loader?" + JSON.stringify({
                        attrs: ["img:src"]
                    })
                ]
            }
```

```javascript
output: {
        path: path.resolve(__dirname + '/public/'),
        publicPath: "./public/",
        filename: '[name].js'
    }
```

The entry is an object  glob containing all of the HTML under the `public/` folder.

I'm using `file-loader` v0.11.1 and Webpack v3

**Comment by AndreKR** [comment]
You can set `publicPath: ''` and at runtime set `__webpack_public_path__ = 'path/to/your/assets'`.

Note that currently you have to downgrade to file-loader 0.10.1 to make this work.

**Comment by TimVervers** [comment]
Hi @AndreKR, I'm having the same issue as @jewbetcha. I followed your advice and added publicpath to my webpack.config and set the public path inside my entry point file. Sadly, this wont work cause the CSS imports with the URL link inside them will load earlier then setting the __webpack_public_path__.

My stackoverflow post (initially for url-loader) https://stackoverflow.com/questions/46001976/webpack-url-loader-dynamic-public-path

Thanks in advance,

Tim

**Comment by AndreKR** [comment]
First double-check please that you are really using file-loader 0.10.1 and not something newer.

Then, what's in your `./src/admin.planningview.js`? If is contains something like
```
__webpack_public_path__ = 'path/to/your/assets';
require('base.css');
```
then it should work.

**Comment by poorpaddy** [comment]
@jewbetcha If you figured out the solution to this would you mind posting it in a comment please? Running into a similar issue where the home page is in root and image paths are `./img/` but subdirectory/routes have the same when they need to be `../img`.

**Comment by jewbetcha** [comment]
@poorpaddy I haven't figured it out 😭 I'm either missing something obvious, or this is just a thing Webpack isn't made for (working with assets that aren't built with JS frameworks)

**Comment by evilebottnawi** [comment]
Problem still exists? Somebody can create minimum example repo and description?

**Comment by DawidMmM** [comment]
Yes. The problem still exists, I got the same issue if I try to load images form subfolders. When i use ./img/ everything is fine but if I got an .html file in a subfolder to load images I need to use this ../img/ and it doesn't work.

**Comment by poorpaddy** [comment]
I managed to fix this by just using `./` as my root. However it is far from a perfect solution. In the end I ended up no longer bundling images in webpack and now serve them from CDN. It actually drastically improved build times and load times since I served the images thru a cache.

**Comment by mimi149** [comment]
I have the same problem and I recognize that webpack stores the images in the folder which are set in the config.output.path1 + path2, where path2 is in '[path2][name].[ext]' when setting the option for file-loader (path2 is the original location of the images). 

The browser tries to retrieve the images from another location such as app_url/path2, however. I have tried different configuration for webpack but failed. I don't know if someone could do that. 

My temporary solution is copying the images to the necessary folder after running webpack. I hope to hear a solution from someone else so that the browser retrieves the images where webpack stores in.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by fredyrivas** [comment]
@mimi149 I ended up using other way for handle images: 
https://github.com/webpack-contrib/copy-webpack-plugin
so I only use file-loader for fonts
