### ISSUE TITLE
`SyntaxError: Unexpected token export` after upgrading to 1.0.0

### ISSUE THREAD

**Issue by roblg** [webpack-contrib/file-loader#182]
We started seeing an issue this afternoon that corresponds with upgrading from 0.11.2 to 1.0.0:

```
16:05:44 [16:05:40] Starting 'webpack'...
16:05:44 
16:05:44 ERROR in ..../Style.less
16:05:44 Module build failed: /path/to/project/RED/node_modules/happypack/loader.js?id=css!<path>Style.less:118
16:05:44 	export default __webpack_public_path__ + "1e831508ee06c33633e492eb22e6e594.png";
16:05:44 	^^^^^^
16:05:44 SyntaxError: Unexpected token export
16:05:44     at Object.exports.runInThisContext (vm.js:76:16)
16:05:44     at Module._compile (module.js:542:28)
16:05:44     at Object.exec (/path/to/project/RED/node_modules/webpack-core/lib/NormalModuleMixin.js:88:7)
16:05:44     at Object.<anonymous> (/path/to/project/RED/node_modules/extract-text-webpack-plugin/loader.js:98:22)
16:05:44     at Compiler.<anonymous> (/path/to/project/RED/node_modules/webpack/lib/Compiler.js:214:10)
16:05:44     at /path/to/project/RED/node_modules/webpack/lib/Compiler.js:403:12
16:05:44     at Compiler.next (/path/to/project/RED/node_modules/tapable/lib/Tapable.js:67:11)
16:05:44     at Compiler.<anonymous> (/path/to/project/RED/node_modules/extract-text-webpack-plugin/loader.js:79:5)
16:05:44     at Compiler.next (/path/to/project/RED/node_modules/tapable/lib/Tapable.js:69:14)
16:05:44     at Compiler.<anonymous> (/path/to/project/RED/node_modules/webpack/lib/CachePlugin.js:40:4)
```

Downgrading to 0.11.2 resolves the issue. It's plausible that this is related to the ancient versions of webpack (1.x), extract-text-webpack-plugin (0.8.x), or less-loader or css-loader that we're using, but the file-loader is the thing that triggered the error, so I figured I'd start here. :)

edit: add: using node 6.9.1/npm3

**Comment by Kovensky** [comment]
The new file-loader will only work with webpack >= 2.0.

**Comment by d3viant0ne** [comment]
@roblg - imo it's going to be far easier to upgrade Webpack than try to get any Major version release coming out of `webpack-contrib` working with 1.x as nothing in contrib supports 1.x anymore. 

Given we are on three & well on the way to 4.x, I'd personally skip 2.x but to your original post there isn't much that can be done outside of pin to `0.11.2`

**Comment by roblg** [comment]
That makes sense. In our case, we were doing something silly (`*`) anyway, so a breakage was inevitable. We'll be upgrading to 3.x shortly. Hopefully the record of this issue helps someone else.

Thanks!
