### ISSUE TITLE
broken jpg

### ISSUE THREAD

**Issue by oliviertassinari** [webpack-contrib/file-loader#185]
I have noticed the following **regression** upgrading from `0.11.2` to `1.0.0`:
The **jpg output is no longer valid** when the plugin is handling an image.
I have noticed that behavior on Material-UI, [this can be used to **reproduce the issue**](https://github.com/callemall/material-ui/tree/v1-beta/docs).

**Comment by whitetrefoil** [comment]
Facing similar problem with PNG.

Original:
`89 50 4E 47 0D 0A 1A 0A ...`
Copied:
`EF BF BD 50 4E 47 0D 0A 1A 0A ...`

**Comment by evilebottnawi** [comment]
@oliviertassinari @whitetrefoil whown issue, PR https://github.com/webpack-contrib/file-loader/pull/183

**Comment by Dcatfly** [comment]
@evilebottnawi This bug still exists.

**Comment by evilebottnawi** [comment]
@Dcatfly Please provide you version `webpack` and `file-loader`, thanks!

**Comment by Dcatfly** [comment]
@evilebottnawi  webpack: 2.7.0, file-loader: 0.11.2
And console output file size is correct, but with the real folder file size is not the same.

**Comment by Dcatfly** [comment]
@evilebottnawi Oh, I found the source of the problem. Because I use happypack, remove happypack is OK. I am so sorry.
