### ISSUE TITLE
Why can't [name] be used to create a path in parameter 'name'

### ISSUE THREAD

**Issue by albertpeiro** [webpack-contrib/file-loader#187]
file-loader 0.11.2
Why does this:

```javascript
entry: {
  admin: [],
}
...
{
  test: /\.(jpe?g|png|gif|svg)$/,
  use: 'file-loader?&name=[name]/[name].[ext]'
},
```
Gives this output?
```output
image/image.png
```

I expect - just like in my css and the rest of the compile
```
admin/image.png
```
Is this a bug? how can I fix it. I need to subfolder the images into the right [name] folder dynamically

**Comment by michael-ciniawsky** [comment]
`[name]` is the placeholder for `path.basename(file)` (`filename`). Try with `options.context`and `[path]`, which is the file path placeholder relative to the context or simply `name=admin/[name].[ext]` if all images go into `admin/`

**Comment by albertpeiro** [comment]
Hi @michael-ciniawsky thanks very much for your help. My mistake was pretty obvious now I realise.

Still my doubt is:
Can I use at all the name of the chunk (entry point name)? I'm trying to build two apps into separate folders but they share code and I want them to share the loaders.

- `options.context` can't be used because since I have two entry points, it's the root of both.
- `[path]` it's not ideal since this means I will need to name the folder exactly as the source folder. Not a common pattern in webpack as far as I know.
`[chunk]` doesn't work

1) Can this be solved at all in the way I need - dynamically based on the chunk-name?
2) All lodaders and setups have worked with this pattern. Is it possible to expose the [chunk] in the loader at all?
3) As far as my research goes, I see the only solution is to use an include/exclude strategy and hardcode the chunk name. What are your thoughts?

Thank you very much in advance!

**Comment by prosim** [comment]
Have this exact same issue - any new thoughts here?

**Comment by micgro42** [comment]
@prosim This seems to be impossible on a fundamental level. The apparently correct approach (which worked for me, after several hours of searching) is to implement "multiple configurations".
Source: https://github.com/webpack/webpack/issues/6124#issuecomment-351647892
Doku: https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations

**Comment by prosim** [comment]
Yeah - I believe that's what I ended up doing. It was a unique situation so I don't expect many would have a similar need.
