### ISSUE TITLE
Some images not display

### ISSUE THREAD

**Issue by GMounir** [webpack-contrib/file-loader#188]
Please some help...
I'm using file-loader => 0.11.2
for example when i require image like this it is working e.g **img(src="./assets/images/one.jpg")**
when i take the image that is not display i include it inside the css it is working.

webpack.config.js:
{
 test: /\.(jpe?g|png|gif|svg)$/i,
  use: [
   'file-loader?name=[name].[ext]&outputPath=assets/images/&publicPath=../../',
   'image-webpack-loader'
 ]
}

**Comment by evilebottnawi** [comment]
@GMounir please provide minimum reproducible test repo, thanks!

**Comment by brianhelba** [comment]
@GMounir @evilebottnawi I suspect this is the issue fixed by https://github.com/webpack-contrib/file-loader/pull/183

**Comment by michael-ciniawsky** [comment]
@brianhelba Thx 

See @brianhelba Comment, feel free to reopen if still regressions
