### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rderandom** [webpack-contrib/file-loader#192]
Hi there. Could you please add the missing comma to:
```
 loader: 'file-loader' 
      options: {
```
at https://github.com/webpack-contrib/file-loader#name

Thank you very much and regards,
R.

**Comment by evilebottnawi** [comment]
@rderandom PR welcome, thanks :+1:

**Comment by rderandom** [comment]
Thank you for your awesome work and support. Kind regards,
R.
