### ISSUE TITLE
doesn't emit public folder

### ISSUE THREAD

**Issue by sebalaini** [webpack-contrib/file-loader#197]
I've installed file-loader and I configure it but it doesn't work, it doesn't emit a folder.

      {
        // IMAGE LOADER - FILE LOADER
        test: /\.(jpe?g|png|gif|svg)$/,
        include: [
          // take the images from img in src
          path.resolve(__dirname, "src/img/")
        ],
        use: [{
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              publicPath: './',
              outputPath: 'img/',
            }
        }]
      }

in dev with webpack dev-server it works and imports the img but in prod no.
I import the img with SCSS with this code:

body {
  background: url("/img/react.png") center center no-repeat;
}

This code works in "dev" but I need to put ../img for "prod" but I have some errors and I can't import the img.

Here the repo:
https://github.com/sebalaini/ReactWebpack

This is my specs:
Mac OS X 10.12.6
NODE V 8.4.0
WEBPACK 3.5.5
FILE LOADER 1.0.0

**Comment by evilebottnawi** [comment]
@sebalaini please downgrade `file-loader` to `0.11.2`, `1.0.0` still beta, fell free to reopen if you have problem(s), thank you!
