### ISSUE TITLE
npm could not install from node_modules/file-loader as it does not contain package.json

### ISSUE THREAD

**Issue by emiglobetrotting** [webpack-contrib/file-loader#201]
I'm new to webpack trying out the getting started guide, now at Asset management where I want to bundle image and this required me to install file-loader into node_modules as i have done to other modules like lodash, style-loader, and css-loader. But in attempt to install file-loader i am having the following error message
   
     could not install from node_modules/file-loader as it does not contain package.json

**Comment by evilebottnawi** [comment]
@emiglobetrotting please provide full steps installation, thank you!

**Comment by emiglobetrotting** [comment]
This is my full installation of webpack on C: directory after I have installed nodejs into C:\Programe Files
    
    mkdir webpack-demo && cd webpack-demo
    npm init -y
    npm install --save-dev webpack

Then I tried loading CSS and installed the following loaders

    npm install --save-dev style-loader css-loader

Which helps to load CSS for the Project below

    project

      webpack-demo
      |- package.json
      |- webpack.config.js
      |- /dist
         |- bundle.js
         |- index.html
      |- /src
         |- style.css
         |- index.js
      |- /node_modules

 ./dist/index.html

     <html>
       <head>
          <title>Asset Management</title>
       </head>
       <body>
          <script src="./bundle.js"></script>
       </body>
     </html>

webpack.config.js
     
     const path = require('path');
      module.exports = {
       entry: 'C:\webpack-demo\src\index.js',
       output: {
         filename: 'bundle.js',
         path: path.resolve(__dirname, 'dist')
       },
       module: {
         rules: [
           {
              test: /\.css$/,
              use: [
                'style-loader',
                'css-loader'
              ]
          }
        ]
      }
    };
 
./src/style.css

    .hello {
       color: red;
    }

./src/index.js

    import _ from 'lodash';
    import './style.css';

    function component() {
       var element = document.createElement('div');

      // Lodash, now imported by this script
       element.innerHTML = _.join(['Hello', 'webpack'], ' ');
       element.classList.add('hello');

       return element;
     }

      document.body.appendChild(component());

Ran
 
   ./node_modules/.bin/webpack --config /path/to/webpack.config.js //to generate bundle.js

Everything works. Now also I want to load image with this same project, where a file-loader needs to be installed into node_modules directory in my webpack-demo. 

The following command to install file-loader generates the aforementioned error that could not install node_modules/file-loader as it does not contain package.json
 
    npm install --save-dev file-loader

**Comment by evilebottnawi** [comment]
@emiglobetrotting do you have `file-loader` in your `module.rules`? Please provide full configuration webpack. Also do you have `file-loader` in `package.json`?

**Comment by emiglobetrotting** [comment]
yes i have file-loader in the package.json, but i haven't added it yet in the module.rules. the installation with npm is giving me the above mentioned error.

Had it been file-loader is successfully installed into node_modules i will have this

webpack.config.js

      const path = require('path');

      module.exports = {
        entry: './src/index.js',
        output: {
           filename: 'bundle.js',
           path: path.resolve(__dirname, 'dist')
        },
       module: {
           rules: [
              {
                  test: /\.css$/,
                  use: [
                    'style-loader',
                    'css-loader'
                  ]
             },
       {
        test: /\.(png|svg|jpg|gif)$/,
            use: [
              'file-loader'
            ]
         }
       ]
      }
     }

./src/style.css will be 

    .hello {
       color: red;
       background: url('./icon.png');
     }

./src/index.js will be 

      import _ from 'lodash';
      import './style.css';
     import Icon from './icon.png';

     function component() {
       var element = document.createElement('div');

       // Lodash, now imported by this script
      element.innerHTML = _.join(['Hello', 'webpack'], ' ');
      element.classList.add('hello');

      // Add the image to our existing div.
      var myIcon = new Image();
      myIcon.src = Icon;

      element.appendChild(myIcon);

      return element;
     }

     document.body.appendChild(component());

This is my package.json

    {
     "name": "webpack-demo",
     "version": "1.0.0",
     "main": "index.js",
     "scripts": {
       "test": "echo \"Error: no test specified\" && exit 1"
     },
     "keywords": [],
     "author": "",
     "license": "ISC",
     "devDependencies": {
       "css-loader": "^0.28.7",
       "file-loader": "file:node_modules/file-loader",
       "style-loader": "^0.18.2",
       "webpack": "^3.6.0"
     },
     "dependencies": {
       "lodash": "^4.17.4"
     },
     "description": ""
   }

**Comment by michael-ciniawsky** [comment]
```diff
- "file-loader": "file:node_modules/file-loader",
+ "file-loader": "^0.11.0",
```

**Comment by emiglobetrotting** [comment]
thanks, it works
