### ISSUE TITLE
Corrupted images emitted

### ISSUE THREAD

**Issue by slavafomin** [webpack-contrib/file-loader#205]
Hello!

Thank you for your hard work!

However, when I'm trying to use the `file-loader` to import JPG image, the corrupted file is emitted instead. I've set up a minimal repository here: https://github.com/slavafomin/webpack-file-loader-corrupts-images.

I'm not sure if I'm doing something wrong or if something is actually broken. I was just following the webpack getting started guide.

When comparing the two files with `hexdiff` I can say that entire file is partially overwritten and the corrupt file is ~ two times longer.

What could be the reason for this? Thanks!

**Comment by michael-ciniawsky** [comment]
Which version of `file-loader` are you using ? `>= v1.x.x` ? if that's the case revert to `=< 0.11.2` for now. There's a know bug in `v1.x.x` atm (#183)

**Comment by slavafomin** [comment]
All actual dependencies used are in the `yarn.lock` of the attached repository:
https://github.com/slavafomin/webpack-file-loader-corrupts-images/blob/master/yarn.lock

I'm using latest stable version of the `file-loader`, which is `1.1.0` as suggested in the getting started guide. I will try to install the suggested version and will get back to you.

**Comment by michael-ciniawsky** [comment]
Try `v1.1.3` (`@latest`) `npm i -D file-loader` or `npm i -D file-loader@0.11.2`, the getting started guide won't help you here :)

**Comment by slavafomin** [comment]
I've downgraded to `0.11.2` and I can confirm that it's working correctly.

This looks crazy as webpack is such a popular system and it's basic functionality is broken in STABLE branch, so any new user can't even complete the getting started guide. And there is no even a tiny notice about this anywhere. I can't even comprehend what a confusing experience this could be for a new users.

**Comment by slavafomin** [comment]
Oh, it looks like it's also working in latest `v1.1.3`, which was released couple of hours ago. But still, such a critical problem in stable branch looks frightening. Aren't there any tests for this?

**Comment by michael-ciniawsky** [comment]
There are but this particular issue originated from a build error during postinstall transpilation and therefore wasn't catched by the CI
