### ISSUE TITLE
1.1.0 invalid options

### ISSUE THREAD

**Issue by Yusoo** [webpack-contrib/file-loader#206]
`      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10240,
            },
          },
        ],
      }
`
An error occurred:
    File Loader Invalid Options
    options['limit'] should NOT have additional properties

**Comment by michael-ciniawsky** [comment]
Yep good catch, fix is here (#207)
