### ISSUE TITLE
Module build failed: Error: Cannot find module './options.json'

### ISSUE THREAD

**Issue by gwuhaolin** [webpack-contrib/file-loader#208]
version:file-loader@1.1.2

error stack:
```
ERROR in ./imgs/bg.jpeg
Module build failed: Error: Cannot find module './options.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules/file-loader/dist/index.js:21:16)
```

in file `node_modules/file-loader/dist/index.js:21:16` is:
```
var _options = require('./options.json');
```

`file-loader/dist/` dir struct:
```
node_modules/file-loader/dist
|-- cjs.js
`-- index.js
```

Is clearly that `node_modules/file-loader/dist/index.js` require no exit file `./options.json` lead to this error.

**Comment by gwuhaolin** [comment]
@d3viant0ne you do  action **chore(release): 1.1.2**, please check it

**Comment by nashaofu** [comment]
not find ``./options.json``, Please fix it as soon as possible，thanks

**Comment by gwuhaolin** [comment]
anyone jump into this error can use `"file-loader": "1.1.0"` to avoid temporary.
