### ISSUE TITLE
options.name should be string

### ISSUE THREAD

**Issue by danielg2002** [webpack-contrib/file-loader#215]
file-loader: 1.1.4
webpack: 3.6.0
npm: 5.3.0
node: 8.6.0
...
options: {
name: 'static/media/[name].[ext]',
}
....

**Module build failed: Validation Error
File Loader Invalid Options
options.name should be string**

**Comment by michael-ciniawsky** [comment]
Please show your full webpack.config.js

**Comment by danielg2002** [comment]
@michael-ciniawsky attached my webpack config.

Thanks,
Daniel

[webpack.config.dev.js.txt](https://github.com/webpack-contrib/file-loader/files/1356984/webpack.config.dev.js.txt)

**Comment by michael-ciniawsky** [comment]
@danielg2002 Please update to`url-loader` to `>= v0.6.1`. It has a bug to not allow additional properties and therefore seem to be failing on the additional name prop. Otherwise feel free to reopen the issue and we maybe need to disable the `type` check for `name` then. Also try a minimum example in case it is still failing, to ensure it isn't another config related bug

**Comment by danielg2002** [comment]
@michael-ciniawsky tried with url-loader v0.6.2 with same result

**Comment by d3viant0ne** [comment]
I'm doing something very similar for work & this is reproducible in 0.6.1 & not 0.6.2.

@danielg2002 - Double check that you don't have a package cached by npm / yarn as well as verifying what's in your lock file ( if you are using one )

**Comment by danielg2002** [comment]
@michael-ciniawsky 100% confirmed! 0.6.2 has the same issue.

package-lock.json (double checked also in node_modules directory)
"url-loader": {
            "version": "0.6.2",
            "resolved": "https://registry.npmjs.org/url-loader/-/url-loader-0.6.2.tgz",
            "integrity": "sha512-h3qf9TNn53BpuXTTcpC+UehiRrl0Cv45Yr/xWayApjw6G8Bg2dGke7rIwDQ39piciWCWrC+WiqLjOh3SUp9n0Q==",
            "dev": true,
            "requires": {
                "loader-utils": "1.1.0",
                "mime": "1.4.1",
                "schema-utils": "0.3.0"
            }
        }

**Comment by d3viant0ne** [comment]
@danielg2002 - I assume given you didn't link a repo that whatever you are working on isn't public.

Is that based off of create react app?

**Comment by danielg2002** [comment]
@michael-ciniawsky Exactly, is a private repo. Yes, was created using create react app.

Clearly the problem is the transfer of the value **option.name** from _url-loader_ to _file-loader_; in my _url-loader_, is a **function** and your _file-loader_ expect only a **string** type.

**Comment by d3viant0ne** [comment]
Yeah, that part I get. I just wanted to fork whatever that is so we can test the rest of the schema enforcement PR's against it + the angular-cli ( covers a vast majority of the use cases )
