### ISSUE TITLE
why adding outputPath inside the "url"?

### ISSUE THREAD

**Issue by crazyx13th** [webpack-contrib/file-loader#218]
"file-loader": "1.1.5",

this is my webpack-config
![grafik](https://user-images.githubusercontent.com/8912561/31885311-6299412c-b7f0-11e7-8937-b01efedd653d.png)

but in my output there is allways the outputPath inside?!
![grafik](https://user-images.githubusercontent.com/8912561/31885401-aaf5b8d8-b7f0-11e7-89df-8c7f9eff9d08.png)
 
Makes no sense for me :-( pls help! thx!!

Greetings
crazyx13th

**Comment by crazyx13th** [comment]
ok, this saves my day
https://github.com/webpack-contrib/file-loader/issues/160#issuecomment-306215576

**Comment by evilebottnawi** [comment]
@crazyx13th can we close issue?

**Comment by crazyx13th** [comment]
yeah, I think this is a "double" (sorry, find the solution too late)
