### ISSUE TITLE
outputPath is not work when useRelativePath is true

### ISSUE THREAD

**Issue by ganxunzou** [webpack-contrib/file-loader#219]
- env
```
"file-loader": "^1.1.5",
node:8.8.1
```
- question
```
{ test: /\.(eot|woff|woff2|svg|ttf|png|jpg|jpeg)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 100, 
              fallback: 'file-loader', // default
              name: '[name]-[hash:8].[ext]',
              publicPath: 'assets/',
              outputPath: '/imgs/',
              useRelativePath: false, // true : outputPath Failure
            },
          }],
      },
```
Above the code is work OK，but change `useRelativePath:true` , `outputPath` is not work

**Comment by michael-ciniawsky** [comment]
Please include Error Logs or try to describe in more detail **what**  doesn't work. Alternatively provide a test repo for reproduction

**Comment by qlqllu** [comment]
I you see the code, you can see the outputPath is overridden if useRelativePath is true, here is the talking about this:
https://github.com/webpack-contrib/file-loader/pull/222
