### ISSUE TITLE
Pass more information (file absolute path) into outputPath function so we can generate dynamic path

### ISSUE THREAD

**Issue by qlqllu** [webpack-contrib/file-loader#220]
For now, only the `url` is passed into the outputPath (https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L49). When I use relative URL in CSS, the image context is lost in outputPath function. It'd be better if you pass the absolute file path (https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L30), we can use this info to return more dynamic path.

**Comment by michael-ciniawsky** [comment]
Feel free to send a PR for discussion

**Comment by d3viant0ne** [comment]
Food for thought, the use of absolute paths in loaders is generally more trouble than it's worth.

**Comment by qlqllu** [comment]
@d3viant0ne Thanks for your advice, I do not use the absolute path as an output, I just use the path information to generate dynamic relative output

**Comment by qlqllu** [comment]
This is the PR: https://github.com/webpack-contrib/file-loader/pull/222

In addition to pass the full path, I mad one more change: Do not override the output path if user have set it. From my point of view, if the outputPath is not set, we can generate one depends on the url. But if user set it, we should use it.

**Comment by evilebottnawi** [comment]
Declined. Ref: https://github.com/webpack-contrib/file-loader/pull/222

**Comment by evilebottnawi** [comment]
Of sorry, my mistake

**Comment by evilebottnawi** [comment]
Declined. Ref: https://github.com/webpack-contrib/file-loader/pull/222#pullrequestreview-73595350
