### ISSUE TITLE
Multi entries bug when `useRelativePath`

### ISSUE THREAD

**Issue by Cap32** [webpack-contrib/file-loader#221]
## Env

- file-loader 1.1.5
- Node.js 8.6.0
- Webpack 3.8.1
- macOS 10.12.6

## Description

If multi entries imports the same file, and if their issuer contexts are different, and if `useRelativePath` is `true`, the compiled urls are wrong

Here's a test repo https://github.com/Cap32/file-loader-relative-path-bug

**Comment by fgustovo** [comment]
is there any solution or update about that ?

**Comment by michael-ciniawsky** [comment]
This is likely to be not fixable within `file-loader`, since the `assets` are deduped by `webpack` and whatever asset is being outputted may have the wrong path for an entry

**Comment by evilebottnawi** [comment]
@michael-ciniawsky let's leave open for tracking, i think it is fixable in loader

**Comment by evilebottnawi** [comment]
It is not fixable on `file-loader` side, sorry, avoid using `useRelativePath` it is not safe (and will be removed in next major release).
