### ISSUE TITLE
Inline generated file paths at import site

### ISSUE THREAD

**Issue by portpaw** [webpack-contrib/file-loader#223]
When you have a large number of `file-loader` imports in your app, the bloat caused by each file getting its own module wrapper can have a negative impact on your bundle size.

For the Trello web client (which has ~900 emojis being included by `file-loader`), we saw a difference of 30KB **gzipped** between bundles with the string literal file paths and an equivalent bundle with `require` calls for those file paths.

During my investigation, I split out the 900 `require` calls for the emojis into their own entry and tried bundling that separately. The difference between string literal file paths and `file-loader`-generated paths in this case was only 10KB gzipped. I think this is due to the bundler outputting all of the module wrappers next to each other in the output, allowing gzip to take advantage of that duplication and further compress the bundle. In the real world, these module wrappers are likely to be defined sporadically throughout the bundle. Happy to hear other theories on that.

So, if we had a way to get rid of the module wrapper entirely for files that are only imported once, and instead just inline the file path at the import site, we could potentially save a lot of bytes at a particular scale.

This:

```
G0eA:function(e,o,i){e.exports=i.p+"images/emoji/beginner.png"}
```

And this:

```
i("G0eA")
```

Becomes this:

```
i.p+"images/emoji/beginner.png"
```

That's a savings of 41 bytes per file imported, which comes out to 36KB for 900 files (someone check my math).

I'm not sure this issue can be solved in the loader itself, but might instead need to be some combination of the loader + a plugin to do the inlining. Thoughts?

**Comment by d3viant0ne** [comment]
So right out of the gate without putting a great deal of thought into this, I think you are right about not being able to solve this here given where / what file-loader is used for.

That said, it's a legit problem ( I loathe bundle bloat ) so we will find a way to work it out. Perhaps something a bit more purpose built, I'll give it some thought this evening.

**Comment by michael-ciniawsky** [comment]
Without verification (I need to test it), this may be resolvable by the [`ModuleConcatenationPlugin()`](https://webpack.js.org/plugins/module-concatenation-plugin/) (Scope Hoisting) which should hoist this barely useful wrappers **if** we could export a ESM, which isn't currently possible because `css-loader` resolves assets (`url()`) via `require` (legacy) 😞 .

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - There is discussion going on around the style chain changes, which as you said would resolve this.

We could in theory spin off an esm version of this loader that should work but it's not going to work for style related stuff atm. It's kind of a bandaid fix but it would be the safest approach to take given what we can't do right now.

**Comment by gerges** [comment]
Is it possible this could be built with a more generic optimization plugin (or just built in altogether) which traces the dependency graph, identifies leaf nodes, calculates the length in bytes of the module contents itself, as well as the know length of the wrapper and an invocation, compared the two values and if it had a positive impact on size inlined the module? (Doing that scan again until no inlines can be preformed)

I have an incredibly naive view of how webpack works, so if that doesn't make sense please ignore me 😋

**Comment by d3viant0ne** [comment]
`traces the dependency graph, identifies leaf nodes, calculates the length in bytes of the module contents itself`

Loaders perform an operation on a thing & return. The above, outside of being way out of scope for something like this sounds like a performance problem in the making.

Not to say that there isn't a legit need but that set of requirements is anything but generic & imo isn't something that should find itself in a general use plugin meant to return a relative url & file wrapped in a `require`.

**Comment by portpaw** [comment]
Was this fixed?

**Comment by michael-ciniawsky** [comment]
It's not possible to fix this with changes to `file-loader`, maybe the `ModuleConcatenationPlugin` once the export becomes an ES2015 Module (not possible atm) or one needs to write a Plugin to optimize the modules. `file-loader` gets a module and 'transforms' it, it's simply out-of-scope to do this on the loader level
