### ISSUE TITLE
files copying doesn't works

### ISSUE THREAD

**Issue by MichaelSemchenko** [webpack-contrib/file-loader#224]
### Issue description: 
I use a very simple webpack config:
```
module.exports = {
  context: __dirname + '/app',
  devtool: "inline-sourcemap",
  entry: {app: "./home.js"},
  output: {
    path: __dirname + "/dist",
    filename: "[name].js"
  },
  module: {
    rules: [
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        use: {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'images/',
            publicPath: 'images/'
          }
        }
      }
    ]
  },
};
```

and project structure
```
--app
----test.png
----home.js
```

### Expected behavior:
there 'home.js' and 'images' folder in /dist.

### Now: 
home.js in 'dist' folder only.

(I'm sorry if this is not a file-loader issue: I start to use webpack one day ago and not sure config is correct.)

### Environment:
webpack: v3.8.1 (I have the similar issue with webpack 2.x.x versions)
node: v8.1.2

**Comment by michael-ciniawsky** [comment]
Where is `test.png` currently placed, did you `import png from `./test.png` ?

**Comment by michael-ciniawsky** [comment]
Could you remove the `publicPath` and `outputPath` options temporarily, so `324156trf.png` should be emitted `dist/` ?

**Comment by MichaelSemchenko** [comment]
test.png placed in 'app/' folder:
```
project root
--app
----test.png
----home.js
```

When I type 
`import img from './test.png';` 
in home.js I get dist/images/test.png - it works.
Can you tell me please, is any way to do it without import via js? I want to keep js file clean of images, styles import etc. [but I'm not sure this is a correct webpack way]

**Comment by MichaelSemchenko** [comment]
**upd**.
yep, I see this is impossible, webpack works another way, sorry for a stupid question).
Solution with import works, thanks a lot!

**Comment by michael-ciniawsky** [comment]
`file-loader` > [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin) ||`file-manager-plugin` > npm/gulp/Grunt Task > place them in the `dist` from the beginning :)

**Comment by MichaelSemchenko** [comment]
btw is possible to import folder of images (with nested folders)?

**Comment by michael-ciniawsky** [comment]
Nope `file-loader` doesn't support globs  => `copy-webpack-plugin`

**Comment by stefan--** [comment]
@michael-ciniawsky would you please give an example of how the combination of the file-loader and copy-webpack-plugin looks like.
```
{
    test: /\.(jpe?g|gif|png|svg)$/i,
    use: [ { loader: "file-loader?hash=sha512&digest=hex&name=/assets/images/[hash].[ext]" } ]
}
```
This config puts the file in the `output.path` instead of `output.path/assets/images/`. I have also tried to find a way with `outputPath ` and `publicPath`, however, without success. Thanks
