### ISSUE TITLE
Nothing logged to terminal on rebuild.

### ISSUE THREAD

**Issue by HauntedSmores** [webpack-contrib/file-loader#225]
Im trying to simply import scss into my main.js file and extract it to a separate css file. All of this is working, as I change my src scss file, I see the extracted file in my dist folder with the correct code changes - The problem is that it doesnt trigger anything in the console. I should be seeing a rebuild every time, which Iv seen when using style-loader, css-loader, sass-loader together
Heres my config:

```
module.exports = {
  entry: './src/js/main.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [{
      test: /\.scss$/,
      use: [
          {
              loader: 'file-loader',
              options: {
                  name: '[name].css'
              }
          },
          "extract-loader",
          "css-loader",
          "sass-loader"
      ]
    }]
  }
};
```

**Comment by evilebottnawi** [comment]
@HauntedSmores can you create minimum reproducible test repo?

**Comment by mdmoreau** [comment]
Having the same issue here. It seems to rebuild/log fine if you exclude the name option however.

**Comment by evilebottnawi** [comment]
`file-loader` use `webpack` api. Look here https://webpack.js.org/configuration/stats/ to setup output information
