### ISSUE TITLE
Different behavior between server-side and client-side?

### ISSUE THREAD

**Issue by frozenfung** [webpack-contrib/file-loader#227]
Hey, guys

I use the latest version of file-loader (1.1.5) with my spa and encounter this issue.  I require a png image in my component for my og:image tag, but it acts differently between server-side and client-side. In server-side, it seems like that it requires the image in base64 format. But in client-side, it requires the image in relative path which is desired for me because of og:image tag does not support base64 format.

here is the website
https://www.cakeresume.com/search?locale=en

You can see the different format in og:image tag if you disable javascript in the browser console.

my webpack config: 

```
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader'
      },
      {
        test: /\.(png|jpg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader',
        options: {
          name: '[name]-[hash].[ext]',
        },
      },
    ],
  },
```

and the code I require image:
```
const defaultOgImage = require(`../../../images/TalentSearch/default_og_image.${locale}@2x.png`);
```

Here I use `require` instead of `import` because I want to load different image by different locale which is dynamic. Perhaps this is where this issue comes.

thanks.

p.s. I manage meta tags with react-helmet

**Comment by michael-ciniawsky** [comment]
Did you find solution in the meantime ? This definitely needs more info about your current setup and reproducible example at best. Upfront this is likely a issue in somewhere in you setup...
