### ISSUE TITLE
Old Bug came back (outputPath concat after publicPath)

### ISSUE THREAD

**Issue by amerllica** [webpack-contrib/file-loader#228]
[This Issue](https://github.com/webpack-contrib/file-loader/issues/160) was settled in 0.10.1 version, Just like [Nick](https://github.com/nickhstr) said the solution. but in the newest version the issue came back and the `outputPath` join after `publicPath`. please fix this bug again in the newer version.

thanks

**Comment by donkeizluv** [comment]
I also have this issue. outputPath always joins publicPath

**Comment by amerllica** [comment]
Unfortunately, the contributors must fix it but they don't care, I downgrade from 1.5.0 to 0.10.1 and it was fixed but I wrote the issue to fix in new version. But they don't care.

**Comment by mpriem** [comment]
Same issue here!!

**Comment by evilebottnawi** [comment]
@mpriem Can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/file-loader/issues/160. Thanks for everyone!

**Comment by evilebottnawi** [comment]
Sorry for delay in near future we will fix this (in next week if somebody don't PR before
)

**Comment by mpriem** [comment]
sorry @evilebottnawi .. I missed your replies .. too many mailboxes to manage :) .. will start monitoring #160
