### ISSUE TITLE
Weird Bug: file-loader conflict with cssnano

### ISSUE THREAD

**Issue by amerllica** [webpack-contrib/file-loader#229]
My project link is [THIS LINK](https://github.com/amerllica/postcss-config-on-webpack).
when I use `npm run build:dev` everything is ok but when use `npm run build:dist` , file-loader doesn't work, it seems that doesn't exist. Actually with second command I use `webpack.prod.js` config file for webpack build, and `cssnano` is loaded in LINE:65, and existence of `cssnano` cause to file-loader doesn't work.

When I comment from LINE:65 to LINE:70 and then run again `npm run build:dev` everything run properly.

**# existence of `cssnano` cause to file-loader doesn't work**

**Comment by michael-ciniawsky** [comment]
Use `css-loader`'s minimize option instead, why do you need `postcss-scss` as syntax parser, your `.pcss`  are valid CSS as it seems ? `postcss-scss`  main purpose is to 'parse'  `.scss/.sass` files for `stylelint` (Linting). This isn't a `file-loader` issue
