### ISSUE TITLE
[webpack v4.0.0-alpha.0] `this.context` => `this.rootContext` (Breaking Change)

### ISSUE THREAD

**Issue by dangodev** [webpack-contrib/file-loader#233]
(from [webpack#6064](https://github.com/webpack/webpack/issues/6064))

Running `webpack` with `4.0.0-alpha.0` results in the following error, one per file:

```
ERROR in ./assets/images/icons/search.svg
Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.loader (/Users/drew/Sites/my-site/node_modules/file-loader/dist/index.js:34:49)
 @ ./styles.sass 6:40863-40906
```

**Comment by michael-ciniawsky** [comment]
Could you please try the suggestion in https://github.com/webpack/webpack/issues/6064#issuecomment-349138756 using `rootContext`instead of `context` and provide the results/errors here ?

**Comment by dangodev** [comment]
@michael-ciniawsky Not sure if it’s what you asked, but I tried changing `context:` to `rootContext:` in the webpack config but that obviously resulted in a configuration error.

So then I assumed you meant file-loader, and I went to [index.js:34](https://github.com/webpack-contrib/file-loader/blob/f412b3e9f4c33f83bbc4fb25b2f9e902cc0dff19/src/index.js#L13) and made the following change:

```diff
-  const context = options.context || this.options.context;
+  const context = options.context;
```

And it successfully built and emitted files.

**Comment by michael-ciniawsky** [comment]
> Not sure if it’s what you asked, but I tried changing context: to rootContext: in the webpack config but that obviously resulted in a configuration error.

You mean `ValidationError` in particular here ? :) That's to be expected, but the change in question (`this.options.context` => `this.rootContext`) needs to be made elsewhere. Could you try 

```diff
-  const context = options.context || this.options.context;
+ const context = options.context || this.rootContext;
```

**Comment by dangodev** [comment]
@michael-ciniawsky Yup! That works for me—`this.rootContext` correctly returns the context. @TheLarkInn’s change in #234 seems to work for me.

**Comment by michael-ciniawsky** [comment]
@dangodev Thx for testing that out :)

**Comment by Wisedemic** [comment]
```
- var context = options.context || this.options.context;
+ const context = options.context || this.rootContext;
```

This error is still happening! The above code fixed it for me.

**Comment by lechu1985** [comment]
@michael-ciniawsky Confirming info from @Wisedemic .
I've encountered this issue while upgrading webpack.

Used versions:
file-loader: 1.1.5
Webpack 4.16.1
Webpack CLI:  3.1.0
