### ISSUE TITLE
Files are not copied to outputPath

### ISSUE THREAD

**Issue by nkrh** [webpack-contrib/file-loader#247]
### Version
**1.1.6**

### Options
```
{
  name: '[name].[ext]',
  outputPath: './plugin/test/dist/',
  useRelativePath: true
}
```
### URL
`./placeholder.png`

### Expected output
The `placeholder.png` is copied to `./plugin/test/dist` and its url doesn't change. 

Currently it copied to `./` **NOT** `./plugin/test/dist/` and the url doesn't change. I think file-loader does not respect `outputPath` when `useRelativePath` is true?

**Comment by evilebottnawi** [comment]
@nkrh Why? We should respect output path, `useRelativePath` only for public path

**Comment by nkrh** [comment]
Not sure why. WhenI set `useRelativePath` to false, the files are copied as expected but the URL is modified to `./plugin/test/dist/placeholder.png`. I need the URL not changed, is this possible?

**Comment by evilebottnawi** [comment]
@nkrh can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
@nkrh should be fixed, please upgrade to latest version https://github.com/webpack-contrib/file-loader/releases/tag/v1.1.9
