### ISSUE TITLE
[v1.1.8] paths are broken on Windows

### ISSUE THREAD

**Issue by IAmPicard** [webpack-contrib/file-loader#251]
Using ElectronJS with latest webpack; after updating to file-loader 1.1.8 fonts no longer load (404).

Going back to 1.1.7 fixes the issue. [This](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet) is the repo (but it's far form minimal, sorry); let me know what information I can provide to help you narrow it down.

```
{
	test: /\.(eot|svg|ttf|woff|woff2)$/,
	use: [{ loader: 'file-loader?name=font/[name]__[hash:base64:5].[ext]' }],
	include: defaultInclude
}
```

**Comment by michael-ciniawsky** [comment]
Could you post the 'malformed' `output` path aswell please ?

**Comment by IAmPicard** [comment]
With 1.1.7 I get `http://localhost:8080/font/icons__-xPow.woff2`

With 1.1.8 I get `http://localhost:8080/fonticons__-xPow.woff2`

**Comment by michael-ciniawsky** [comment]
Are you sure this it's a regression between `v1.1.7...v1.1.8` ? The path is correct on macOS with `v1.1.8` and that part is passed to `loaderUtils.interpolateName()` [here](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L15). Could you do me a favor and `console.log(url)` e.g [here](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L20) if the `/` is still there (on windows) after `name` was interpolated ? I would do it myself, but I don't have access to a windows machine

**Comment by kaiyoma** [comment]
I'm seeing this problem as well. I think it was the recent switch to `path.join` instead of `path.posix.join` (https://github.com/webpack-contrib/file-loader/commit/26e47ca). On Windows, the paths are going to be joined with backslashes and those paths are now ending up in the HTML/CSS, causing issues. I'm seeing incorrect/broken URLs in my app now. I just reverted to 1.1.7 and the problems went away, so I'm pretty sure it's that commit.

**Comment by michael-ciniawsky** [comment]
@kaiyoma Can you post your `file-loader` config please ? :)

**Comment by engPabloMartinez** [comment]
I'm having the same problem that @IAmPicard. 
With 1.1.8 I get http://localhost:8080/fontsfontawesome-webfont.woff2 (not loading the font)
With 1.1.7 I get http://localhost:8080/fonts/fontawesome-webfont.woff2 (loading the font)

It's on windows and my webpack config it's
{
    test: /\.(otf|eot|svg|ttf|woff2?)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
    use: 'file-loader?name=fonts/[name].[ext]'
  }

**Comment by michael-ciniawsky** [comment]
If someone has a few minutes :),  please try to change this line https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L35 back to

```diff
- outputPath = path.join(outputPath, relativePath, url);
+ outputPath = path.posix.join(outputPath, relativePath, url);
```

in `node/modules/file-loader` and confirm, that this fixes the current bug on windows 🙏

**Comment by kaiyoma** [comment]
@michael-ciniawsky Here's the relevant portion of my config:

```
    }, {
      test: /(fonts|icons).*\.(eot|svg|ttf|woff)(\?[a-z0-9=&.]+)?$/,
      loader: 'file-loader',
      options: {
        name: 'fonts/[name].[ext]',
      },
    }, {
      test: /images.*\.(gif|jpg|png|svg)$/,
      loader: 'file-loader',
      options: {
        name: 'images/[name].[ext]',
      },
    }, {
```

**Comment by aweber1** [comment]
@michael-ciniawsky I tried the line change that you suggested but it didn't work for me. However, I also then tried changing line 22: https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L22

```
from:
typeof options.outputPath === 'function' ? options.outputPath(url) : path.join(options.outputPath || '', url)

to:
typeof options.outputPath === 'function' ? options.outputPath(url) : path.posix.join(options.outputPath || '', url)

```

and that worked for my situation. loader config:
```
// Image loader
        {
          test: /\.(png|jpg|gif)$/,
          use: "url-loader?limit=50000&name=img/img-[hash:6].[ext]"
        },
```

sample original requested url is: `../img/banner.jpg` and it's found within a CSS file (loaded via css-loader).

the output url is: `/dist/img\img-[hash].jpg`
(where dist is my `publicPath` path set in the main `webpack.output.publicPath` property.

after making the change to line 22 above, the output url is as desired: `/dist/img/img-[hash].jpg`

**Comment by michael-ciniawsky** [comment]
Maybe `const join = process.platform !== 'win32'  ? path.join : path.posix.join` or simply just `path.posix.join` instead of `path.join`, but I wonder about this since the `path` module should already check the platform (https://nodejs.org/dist/latest-v9.x/docs/api/path.html#path_windows_vs_posix).

If `const join = process.platform !== 'win32'  ? path.join : path.posix.join` or `path.posix.join` works PR welcome and appreciated

**Comment by kaiyoma** [comment]
I don't know this codebase at all, but my understanding is that `path.join` is checking the platform - as you said - and _that_ is exactly the problem. You don't want backslashes appearing in URLs, so you actually want to explicitly use the `posix` version, regardless of what platform you're on.

**Comment by michael-ciniawsky** [comment]
@kaiyoma 👍 Thx 😅 I was looking at it from the wrong direction of course... Waiting for review, Release ETA (ASAP)

**Comment by etiennellipse** [comment]
We have this problem as well, it is completely messing up the URLs in our SPA since 1.1.8. We end up with the browser trying to load it relative from where the CSS is located, and it's not pretty.

```
.d-workspace::before {
  background-image: url(\SpaBase\img\white\myUsers.svg?dc2f27bb0ca44c9009104f6586882b6e);
}
```

**Comment by michael-ciniawsky** [comment]
Released in [`v1.1.9`](https://github.com/webpack-contrib/file-loader/releases/tag/v1.1.9) 🎉  

> ℹ️ If still regressions on windows please open a new issue

**Comment by kaiyoma** [comment]
LGTM!

**Comment by etiennellipse** [comment]
Works here, thanks!

**Comment by IAmPicard** [comment]
Works great in 1.1.9; thanks for the quick response.
