### ISSUE TITLE
useRelativePath broken after update from 1.1.6 to 1.1.9

### ISSUE THREAD

**Issue by lukaszsamson** [webpack-contrib/file-loader#257]
With the following options
```
options: {
              emitFile: false,
              name: '[name].[ext]',
              publicPath: 'assets/',
              useRelativePath: true
            }
```
and requiring `img/path/to/file.png`

In 1.1.6 the resulting URL is correct
`assets/img/path/to/file.png`
In 1.1.9  its
`assets/file.png`

**Comment by evilebottnawi** [comment]
@lukaszsamson can you create minimum reproducible test repo?

**Comment by lukaszsamson** [comment]
I don't have a minimum repro, but I tested it a bit more and the regression was introduced in 1.1.8

**Comment by evilebottnawi** [comment]
@lukaszsamson without test repo it is hard to indicate problem place

**Comment by Kernle32DLL** [comment]
@lukaszsamson maybe a cause of this? At least I stumbled across this yesterday and it seems oddly similar to your problem.
https://github.com/webpack-contrib/file-loader/pull/246

**Comment by evilebottnawi** [comment]
@Kernle32DLL right now we fix options how they should work, somebody can have invalid path configuration using bugs

**Comment by zemadz** [comment]
I've created a minimum repo to demonstrate this issue: https://github.com/zemadz/file-loader-relative-path-minimum-repro

There are two branches:
- master (with file-loader@1.1.8)
- working (with file-loader@1.1.7)

Run `npm run build` and see output at `build/js/index.js` or `npm test` to investigate the different behaviors.

**Comment by lukaszsamson** [comment]
#260 does not fix the issue

**Comment by michael-ciniawsky** [comment]
Released in [`v1.1.11`](https://github.com/webpack-contrib/file-loader/releases/tag/v1.1.11) 🎉

**Comment by ossinkine** [comment]
@lukaszsamson I've faced with the same issue. Since #260 does not fix the issue how did you fix this?

**Comment by evilebottnawi** [comment]
@ossinkine `useRelativePath` option was removed in major release

**Comment by lukaszsamson** [comment]
@ossinkine I stopped using this plugin in my config
