### ISSUE TITLE
Combination of outputPath and useRelativePath

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/file-loader#261]
When using the `file-loader` like this ...
```ts
{
    loader: 'file-loader',
    options: {
        name: '[name].[ext]',
        outputPath: 'output/',
        useRelativePath: true,
    },
}
```
... it would be nice if `useRelativePath` does not overrride `outputPath`, but instead `outputPath` will be prepended to the relative path's of the files.

**Comment by evilebottnawi** [comment]
@thasmo can you describe use case?

**Comment by thasmo** [comment]
@evilebottnawi, I'd like to keep the actual directory structure of the source files (`useRelativePath`) but still move them to another location within the output directory (`outputPath`). At the moment I can choose between the two.

**Comment by michael-ciniawsky** [comment]
@thasmo You could try using `name` (`options.name`) instead. https://github.com/webpack-contrib/file-loader#function

**webpack.config.js**
```js
{
   use: [
     {
         loader: 'file-loader'
         options: {
             name: 'subdir/[name].[ext]' // {String}
             name (file) { // {Function}
                 if (file === 'foo') return 'otherDir/[name].[ext]'

                 return 'subdir/[name].[ext]'
             }
         }
     }
   ]
}
```

**Comment by michael-ciniawsky** [comment]
```
outputPath + name
//  => dist/subdir/name.ext
```

**Comment by evilebottnawi** [comment]
@michael-ciniawsky why we have `useRelativePath` option, it is hard to imagine real use case

**Comment by michael-ciniawsky** [comment]
Yep, the loader options and there combinations are more then unintuitive atm, the best 'solution' is to keep usage of them as minimal as possible :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky for me `publicPath` and `outputPath` very logic, but `useRelativePath` - what the hell and why?

**Comment by thasmo** [comment]
Interesting. But what would this do?
```js
{
    loader: 'file-loader',
    options: {
        name: 'subdir/[name].[ext]',
        useRelativePath: true,
    },
}
```
I guess this will create a final path of `[webpack-output-path]/[file-loader-relative-path]/subdir/[name].[ext]`, right?

**Comment by amaschas** [comment]
I'm having the same issue. I need to move a bunch of images from one directory to another, but preserve the subdirectory structure. There's currently no good way to do this that I can determine.

So for instance:

src/
  images/
    foo/
      a.png
    bar/
     b.png

==>

dist/
  images/
    foo/
      a.png
    bar/
     b.png

**Comment by evilebottnawi** [comment]
@amaschas without config we can'y say nothign

**Comment by danburzo** [comment]
Reading more into the source code, this should work for me:

```js
// Font files
{
	test: /\.(woff|woff2|ttf|otf)$/,
	loader: 'file-loader',
	include: [/fonts/],
	options: {
		name: config.local ? '[name].[ext]' : '[hash].[ext]',
		outputPath: 'css/',
		publicPath: './'
	}
},
```

However, I don't know why (or where) the `./` is removed from the font file's path. I worked around it with `publicPath: '../css/'` for now...

**Comment by evilebottnawi** [comment]
@danburzo don't use `publicPath` if you do not understand why you need it, Webpack itself is able to properly build a public path

**Comment by danburzo** [comment]
I am just trying to work around an apparent limitation of `file-loader` though, as described in the comments above.

**Comment by thasmo** [comment]
Basically I want to copy `assets/images/**/*.jpg` to `public/static/images/**/*.jpg`; moving images from the `assets/images` directory to the `public/static/images` directory and preserving the directory structure, which is imo not possible at the moment.

**Comment by evilebottnawi** [comment]
Option `useRelativePath` was removed.

https://github.com/webpack-contrib/file-loader/pull/306

Don't use this option because it is dangerous and break your urls when you use multiple entry points, when you extract code (example `css`), when you load asset in initial and async chunk in difference places and there are a lot of edge cases when you break url. Optimization assets path should be done on `webpack` side and can be implemented in `webpack@5`, but it is not high priority because it doesn't save a lot of bytes.

**Comment by akoidan** [comment]
Let's assume `src/assets` is your assets directory: 

```javascript
{
  test: /(\.svg|\.jpg|\.gif|\.png|\.woff2?|\.eot|\.ttf|\.otf)$/,
  loader: 'file-loader',
  options: {
    name: f => {
      let dirNameInsideAssets = path.relative(path.join(__dirname, 'src', 'assets'), path.dirname(f));
      return `${dirNameInsideAssets}/[name].[ext]`;
    }
  }
}
```

If you have :
 - `src/assets/fonts/a.ttf`
 - `src/assets/images/cool-images/b.png`

For prod mode this conf would create files:
 - `./dist/fonts/a.ttf`
 - `./dist/images/cool-images/b.png`

For dev-server it will server those files withing the same path as the name

**Comment by vaniljs** [comment]
> Let's assume `src/assets` is your assets directory:
> 
> ```js
> const path = require('path');
> 
> 
> {
>   test: /(\.svg|\.jpg|\.gif|\.png|\.woff2?|\.eot|\.ttf|\.otf)$/,
>   loader: 'file-loader',
>   options: {
>     name: f => {
>       let dirNameInsideAssets = path.relative(path.join(__dirname, 'src', 'assets'), path.dirname(f));
>       return `${dirNameInsideAssets}/[name].[ext]`;
>     }
>   }
> }
> ```
> 
> If you have :
> 
> * `src/assets/fonts/a.ttf`
> * `src/assets/images/cool-images/b.png`
> 
> For prod mode this conf would create files:
> 
> * `./dist/fonts/a.ttf`
> * `./dist/images/cool-images/b.png`
> 
> For dev-server it will serve those files withing the same path as the name

Спасибо вам за такой замечательный скрипт!!!
Искал несколько дней решение для обработки относительных путей. 
Спасибо!

**Comment by vaniljs** [comment]
**akoidan** 
Thank you for such a great script!!!
I was looking for a solution for processing relative paths for several days. 
Thanks!
