### ISSUE TITLE
Re-use file-loader options logic

### ISSUE THREAD

**Issue by herrstucki** [webpack-contrib/file-loader#262]
Hi!

I maintain https://github.com/herrstucki/responsive-loader which currently has an open PR, implementing the same options as file-loader: https://github.com/herrstucki/responsive-loader/pull/56

Now: file-loader's options logic combining `context`, `outputPath`, `publicPath`, and `useRelativePath` is quite intricate. I think responsive-loader (or any file-emitting loader) should have the same options and also the same behavior. Copy & paste is the short-term solution but not very sustainable, since everyone would have to track changes to file-loader closely.

Is there some potential for making this reusable for different loaders? Maybe move it to https://github.com/webpack/loader-utils?

Thanks for any thoughts on this issue! 🙇

**Comment by evilebottnawi** [comment]
@herrstucki Hi. Thanks for issue. I agree we should move this logic to utils. Can you create PR in `loader-utils` and ping me?

**Comment by herrstucki** [comment]
Sure, I'll give it a shot when I have some time. Should _all_ file-loader options be moved?

**Comment by evilebottnawi** [comment]
@herrstucki `outputPath` and `publicPath` yes, `useRelativePath` is very buggy and very confused for me, let's don't move her

**Comment by evilebottnawi** [comment]
You can result https://github.com/webpack-contrib/url-loader logic for using `file-loader`, no need copy/paste code, sorry for delay, also `file-loader` does not accept features anymore, because it was deprecated for `webpack@5` in favor `asset` module type https://webpack.js.org/guides/asset-modules/
