### ISSUE TITLE
Version >= 1.1.8 breaks publicPath resolving [net::ERR_ABORTED]

### ISSUE THREAD

**Issue by Sky4CE** [webpack-contrib/file-loader#265]
If I upgrade file-loader to 1.1.8 or above i get this errors: 
![image](https://user-images.githubusercontent.com/9821633/38020314-8f42f1e8-3282-11e8-955d-26cf05b9fb5d.png)

my config is:
```
...
{ test: /\.svg$/, use: `file-loader?limit=65000&mimetype=image/svg+xml&publicPath=&name=fonts/[name].[ext]` },
{ test: /\.woff$/, use: `file-loader?limit=65000&mimetype=application/font-woff&publicPath=&name=fonts/[name].[ext]` },
{ test: /\.woff2$/, use: `file-loader?limit=65000&mimetype=application/font-woff2&publicPath=&name=fonts/[name].[ext]` },
{ test: /\.[ot]tf$/, use: `file-loader?limit=65000&mimetype=application/octet-stream&publicPath=&name=fonts/[name].[ext]` },
{ test: /\.eot$/, use: `file-loader?limit=65000&mimetype=application/vnd.ms-fontobject&publicPath=&name=fonts/[name].[ext]` }
...
```

**Comment by evilebottnawi** [comment]
@Sky4CE look you have invalid configuration, double `dist` directory. Can you create minimum reproducible test repo?

**Comment by Sky4CE** [comment]
@evilebottnawi, yes I see, but all versions prior 1.1.8 produce correct paths after webpack processing

**Comment by evilebottnawi** [comment]
@Sky4CE also you can have invalid server configuration, please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@Sky4CE first please update to latest version

**Comment by Sky4CE** [comment]
@evilebottnawi what do you mean? I have tried to update totlatest 1.1.11 and all version prior that. For me all versions above 1.1.7 do not work

**Comment by evilebottnawi** [comment]
@Sky4CE without minimum reproducible test repo, i can't help

**Comment by Sky4CE** [comment]
@evilebottnawi, indeed problem is not related to fonts. I guess to reproduce this I will need to put all my project config which is huge and it is not possible unfortunately. So problem is in publicPath property I guess. Need to investigate sources what have been changed..

**Comment by Sky4CE** [comment]
@evilebottnawi I manage to solve this. So for me to get latest version work I need to add `./` to `publicPath`:
```
...
{ test: /\.svg$/, use: `file-loader?limit=65000&mimetype=image/svg+xml&publicPath=./&name=fonts/[name].[ext]` },
{ test: /\.woff$/, use: `file-loader?limit=65000&mimetype=application/font-woff&publicPath=./&name=fonts/[name].[ext]` },
{ test: /\.woff2$/, use: `file-loader?limit=65000&mimetype=application/font-woff2&publicPath=./&name=fonts/[name].[ext]` },
{ test: /\.[ot]tf$/, use: `file-loader?limit=65000&mimetype=application/octet-stream&publicPath=./&name=fonts/[name].[ext]` },
{ test: /\.eot$/, use: `file-loader?limit=65000&mimetype=application/vnd.ms-fontobject&publicPath=./&name=fonts/[name].[ext]` }
...
```
Seems like previous versions had a bug so I need to explicitly add empty `publicPath=`, now it is more clear that I have to write `publicPath=./` I guess. Thanks anyway, Closing this.
