### ISSUE TITLE
Support [contenthash] in filenames

### ISSUE THREAD

**Issue by bhollis** [webpack-contrib/file-loader#267]
Webpack 4.3.0 adds direct support for `[contenthash]` - it'd be nice for `file-loader` to leverage it. Here's an example from another plugin: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/59/files

**Comment by evilebottnawi** [comment]
Move to `loader-utils` https://github.com/webpack/loader-utils/issues/112
