### ISSUE TITLE
file-loader ouputting corrupted images

### ISSUE THREAD

**Issue by avoliva** [webpack-contrib/file-loader#273]
Am using the latest `file-loader`. It's outputting the files to `images/css-urls` like specified but they're corrupted images. 

The config is searching through the sass files and replacing urls with new files that file-loader outputs. That part works, but the files are corrupted.

    const ExtractTextPlugin = require("extract-text-webpack-plugin");
    const extractSass = new ExtractTextPlugin("./bundle.css");

    var mainConfig = {
      entry: {
        "app": [
          "./app/main.ts",
          "./static/scss/main.scss",
        ],
        "vendor": "./app/vendor.ts",
        "polyfills": "./app/polyfills.ts",
      },
      output: {
        path: path.resolve(__dirname, "static"),
        filename: "[name].js"
      },
      resolve: {
        extensions: [".ts", ".js"],
      },
      devtool: "source-map",
      module: {
        rules: [{
          test: /.*\.(gif|png|jpe?g|svg)$/i,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[hash].[ext]',
                outputPath: 'images/css-urls/',
              }
            },
          ]
        }, {
          test: /\.(scss|css)$/,
          use: extractSass.extract({
            use: [{
              loader: "css-loader",
            }, {
              loader: "sass-loader",
            }],
            // use style-loader in development
            fallback: "style-loader"
          })
        }, {
          test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
          loader: "url-loader",
        }, {
          test: /\.ts$/,
          loaders: [
            {
              loader: "awesome-typescript-loader",
              options: { configFileName: root("./", "tsconfig.json") }
            } , "angular2-template-loader"
          ]
        }, {
          test: /\.html$/,
          loader: "html-loader"
        }]
      },
      plugins: [
        extractSass,

        new webpack.ContextReplacementPlugin(
          // The (\\|\/) piece accounts for path separators in *nix and Windows
          /angular(\\|\/)core(\\|\/)@angular/,
          root("./app"), // location of your src
          {} // a map of your routes
        ),

        new webpack.optimize.CommonsChunkPlugin({
          name: ["app", "vendor", "polyfills"]
        }),
      
      ]
    }

**Comment by evilebottnawi** [comment]
@avoliva `file-loader` do not anything with original content of file. You have invalid configuration `test: /.*\.(gif|png|jpe?g|svg)$/i,` and `test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,`, i.e. two loader handle same types. `url-loader` use `file-loader` as fallback when file size bigger than `urlLimit`.

**Comment by avoliva** [comment]
That worked, thanks.
