### ISSUE TITLE
I need to load css file not as usual css files

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/file-loader#275]
In our project we use styles in code throught style-loader
```js
{
                test: /\.css$/,
                use: [
                    {
                        loader: 'style-loader/useable',
                        options: {
                            hmr: true,
                            attrs: {
                                // nonce: hash,
                            },
                        },
                    },
                    {
                        loader: 'css-modules-flow-types-loader',
                        options: {
                            indent: '  ',
                            itemDelimiter: ';',
                        },
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            // importLoaders: 1,
                            localIdentName: '[name].[local]_[hash:7]',
                            sourceMap: false,
                        },
                    },
                    {
                        loader: 'postcss-loader',
                    },
                ],
            },
```
but we need the only file ```fonts.css``` to be copy to dist folder as asset with name [name].[hash].[ext]

How to do it?

**Comment by evilebottnawi** [comment]
@budarin `{ loader: "file-loader", options: { name: [name].[hash].[ext] } }`? If you need this for only `fonts.css` use `test` option

**Comment by budarin** [comment]
format of the name, in this case, I've mentioned only for desired output format

may question is: how only the fonts.css (not others) copy to assets (bearing in mind existing test: /\.css$/ section in webconfig)?

if I add test: 'fonts.css' it will be copied as asset and complied with style-loader

**Comment by evilebottnawi** [comment]
@budarin Тяжело понять что именно Вы желаете, возможно на нативной языке это будет проще. Спасибо!

**Comment by budarin** [comment]
Отлично! )

все .css файлы в проекте обрабатываются  style-loader и встраиваются в результирующий код.
Но у нас есть отдельный fonts.css, который необходимо браузеру загружать как отдельный ресурс
Если в конфиге webpack я попытаюсь отдельно его грузить при помощи file-loader при помощи ``` test: /.css$/ ``` - он будет обработан еще и style-loader по правилу ```test: /\.css$/``` - чего хотклось бы избежать

**Comment by evilebottnawi** [comment]
Вы моежет использовать `test: /fonts.css$/`, также хотелось бы узнать откуда береться `fonts.css`, копируется при помощи `CopyWebpackPlugin` или собирается. Возможно вы имеете ввиду это поведение https://github.com/webpack-contrib/style-loader#url, просто используйте `test: /fonts.css$/`.

**Comment by budarin** [comment]
Мочь то я могу ```test: /fonts.css$/``` но и style-loader может - и код fonts.css будет помещен в общий скрипт - чего абсолютно не нужно

fonts.css - создается руками из другого ресурса 

CopyWebpackPlugin  - копирует файлы без задания им имени в формате ```[name].[hash].[ext]```

**Comment by evilebottnawi** [comment]
@budarin Для доставания файла из css из js банда используйте https://github.com/webpack-contrib/mini-css-extract-plugin (`splitChunks.cacheGroups` позволяет достать любой модуль по имени в свой собственный js bundle и плагин для extract plugin уже достанет css из js бандла). 

Также вы можете сделать `[name].[hash].[ext]` с помощью `CopyWebpackPlugin` https://github.com/webpack-contrib/copy-webpack-plugin#template. 

Выбор решения зависит от такого как вы формируете файла, если средставми сборки webpack то первое решения для Вас, если это просто файл который откуда то копируется то стоит использовать второе решение.

**Comment by budarin** [comment]
спасибо за помощь - 2е решение меня вполне устроит!

PS: где-то было раньше описание ```require('!!file.....')``` синтаксиса для загрузки файлов при помощи лоадеров - нигде не нашел - оно могло бы избавить меня от CopyWebpackPlugin

**Comment by budarin** [comment]
Упс!

CopyWebpackPlugin не добавляет ресурс в assets-manifest.json ((( - не решает проблему

**Comment by evilebottnawi** [comment]
@budarin Возможно вы имеете ввиду это https://github.com/webpack/docs/wiki/loaders#loader-order. Проблема с манифестами уже в работе. Все что нам не дает решить ее, разница в api манифест плагинов, но работает над ней.

**Comment by budarin** [comment]
не понял про loader order - если речь идет о том, что срабатывает только тот лоадер, который 1й понял по test что это его ресур и обработал его а остальные лоадеры его уже не тестируют - возможно это решит вопрос

Про манифетс - планируется что CopyWebpackPlugin будет добавлять ресурсы в assets-manifest.json ?

**Comment by evilebottnawi** [comment]
@budarin Попробуейте `require("!!file-loader!./fonts.css")`

Да `CopyWebpackPlugin` будет в будущем добавлять файлы в манифесты (или реализует api для этой возможности).

**Comment by budarin** [comment]
![default](https://user-images.githubusercontent.com/8055157/39369711-ac81689a-4a45-11e8-9f4a-ce969cf97cf9.png)

**Comment by budarin** [comment]
я отключил ESLint на проекте и все прошло успешно - ```fonst.css``` был добавлен в ```assets-manifest.json```

только из приведенной ссылки совсем не понятно как настроить resolver чтобы он мог понять синтаксис ```!!file-loader!```

**Comment by evilebottnawi** [comment]
@budarin Я бы с удовльствием помог, но в данный момент нас двое на все `webpack-contrib` репозитории, у меня просто нет времени чтобы разбираться в этом, думаю вы можете попросить улучшить readme для более простого восприятия, или посмотреть на тестовые примеры или чужие конфигурации.

**Comment by budarin** [comment]
Спасибо большое за помощь!!
