### ISSUE TITLE
publicPath function does not get results from outputPath function

### ISSUE THREAD

**Issue by dannybloe** [webpack-contrib/file-loader#276]
Today I moved from webpack 2 to webpack 4 and upgraded file-loader from 0.11.2 to 1.1.7 and after spending a couple of hours trying to figure out why my paths in generated css files were not correct I noticed a bug (imho) that creeped into the code in [commit](https://github.com/webpack-contrib/file-loader/commit/98bf0521b3412a7e1782b45b0265f2aa51456c5f#diff-1fdf421c05c1140f6d71444ea2b27638). In 0.11.2 you can see that the **results** from a provided outputPath function is handed over to the publicPath function (if you configured both options as functions). However, after this commit this is no longer the case and having an outputPath function has become rather useless.

I think that line 67 (index.js) should be:
`publicPath = options.publicPath(outputPath);` instead of 
`publicPath = options.publicPath(url);`

Please fix this as I can no longer use this loader.

**Comment by evilebottnawi** [comment]
@dannybloe Please read README before post issue. `outputPath` is place where loader save assets, `publicPath` is path to assets in runtime code. `publicPath` should get `url` as argument. Thanks!

**Comment by evilebottnawi** [comment]
Also you don't describe use case for this. Looks you just have invalid configuration.

**Comment by dannybloe** [comment]
Why do you change this without documenting this anywhere? It used to work like this. Check the code from 0.11.2.

**Comment by evilebottnawi** [comment]
@dannybloe https://github.com/webpack-contrib/file-loader/releases/tag/v1.1.8, behaviour what you describe is invalid and it is just bug.

**Comment by evilebottnawi** [comment]
@dannybloe please describe why you need `outputPath`, in theory if you problem is real and not related to invalid configuration we can add second argument `outputPath`

**Comment by dannybloe** [comment]
Ok, I will try to explain. 

I have a sass file using something like this:
```
core.scss:
 div { background-image: url('/media/everythingelse.png'); }

branding.scss:
 div { background-image: url('/media/logo.png'); }
```

After having run webpack it has to be like this
```
dist/
	Web/
		core/
			everythingelse.png
			core.css
		branding/
			logo.png
			branding.css

```
So, in order to make this work I have this config:


```
const config = {
	entry: {
		core: [
			'./src/style/ss-base.scss'
		],
		branding: [
			'./src/style/branding/branding.scss'
		]
	},

	output: {
		path: path.resolve(__dirname, 'dist/Web'),
		...
	},


	module: {
		rules: [
			{ .. sass stuff ..},
			{ .. babel stuff .. },
			{
				test: /\.(png|jpg|jpeg|otf|eot|svg|ttf|ico|woff|woff2)(\?.*)?$/,
				use: [
					{
						loader: 'file-loader',
						options: {
							name: '[name].[ext]',
							publicPath(file) {
								// make it absolute otherwise it doesn't work
								const res = `../${ file }`;
								return res;
							},
							outputPath(file) {
								let res;
								if (file.indexOf('logo') >= 0 ||
									file.indexOf('login-backdrop') >= 0 ||
									file.indexOf('favicon') >= 0
								) {
									res = `branding/${ file }`;
								} else {
									res = `core/assets/${ file }`;
								}
								return res;
							}
						}
					}
				]
			},

		]
	}
```

Earlier this worked like a charm and core.css will have this:
`div { background-image: url('../core/everythingelse.png'); }`
and branding.css:
`div { background-image: url('../branding/logo.png'); }`

All other options I tried with file-loader and webpack 2 didn't work. This was the only construct that I got working. Until you changed the code ;-) And adding '..' was also a red flag but again, this was the only way how I could accomplish this.

So, maybe you have a better way of doing this.

**Comment by evilebottnawi** [comment]
@dannybloe very very very weird configuration :confused: Maybe you can create minimum reproducible test repo in readme add how it was when you use `webpack@2` and how it is now with `webpack@4` and latest `file-loader`?

**Comment by dannybloe** [comment]
Ok, created this simple test project. Run npm install and then npm run build. 
[test.zip](https://github.com/webpack-contrib/file-loader/files/1971081/test.zip)

Of course this is very simplified but we need to have a distinction in the dist folder between specific branding files and 'core' files. (customers can modify the branding files afterwards and just replace or add a couple of images. They are told not to touch anything in the core folder).

Now if you upgrade file-loader to the latest version, this doesn't work anymore.

**Comment by evilebottnawi** [comment]
@dannybloe thanks, i will investigate this in near future, feel free ping me if i will not answer in the next couple of days, a lot of work, sorry

**Comment by dannybloe** [comment]
Sure thing. Thanks anyway.. In the mean-time I'll dive more into webpack 4 and see if there is a more common way to do this.

**Comment by evilebottnawi** [comment]
It is expected behavior and not the bug, `outputPath` and `publicPath` is deference. First response for filesystem location, second for url in your files.
