### ISSUE TITLE
Not sure what the proper behaviour is for require.resolve

### ISSUE THREAD

**Issue by l2silver** [webpack-contrib/file-loader#279]
* Operating System: Mac
* Node Version: 8.11
* NPM Version: 6
* webpack Version: 4.5
* file-loader Version: 1.1.11

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

index.js

```
const PROTO_PATH = require.resolve(@symlinked_package/example)
```
##### CLI Command

```
webpack --config webpack.config.js --target=node --mode=development index.js --output lib/index.js
```

##### webpack.config.js

```
module.exports = {
  module: {
    rules: [
      { test: /\.ext$/, use: [{
        loader: 'file-loader',
        options: {
          name: '[name].[ext]',
          outputPath: 'ext/',
          publicPath: 'ext/',
        }}
      ]}
  ]},
}
```
### Expected Behaviour

lib/index.js
```
const PROTO_PATH = /*require.resolve*/(/*! @symlinked_package/example */ \"ext/example\");
```
### Actual Behaviour
```
const PROTO_PATH = /*require.resolve*/(/*! @symlinked_package/example */ \"../../packages/@symlinked_package/example\");
```
### How Do We Reproduce?

Run the above code.

**Comment by evilebottnawi** [comment]
@l2silver interesting use case, i will find solution in near future, thanks!

**Comment by l2silver** [comment]
@evilebottnawi thanks!

**Comment by l2silver** [comment]
Any updates on this issue?

**Comment by evilebottnawi** [comment]
@l2silver doesn't have time right now, sorry, feel free go ahead and search why it is happens

**Comment by evilebottnawi** [comment]
You should setup https://webpack.js.org/configuration/resolve/#resolve-modules in your case, it is expected
