### ISSUE TITLE
Can we have the name of the chunk in the filename template placeholder?

### ISSUE THREAD

**Issue by TrustNik** [webpack-contrib/file-loader#28]
Smth like:
`loader: "file-loader?name=[chunkname]_[name].[ext]"`

Or is there a workaround to achieve that?

**Comment by bcharp** [comment]
I'm interested too.

**Comment by brafdlog** [comment]
I had the same question for generating the chunk file name and this configuration worked:
chunkFilename: '[name].[chunkhash].js'

The [name] resolves to the chunk name correctly.

I am not sure this is your case because your example is a bit different but I will put this up here in case someone has the same question I had.

**Comment by Emiya0306** [comment]
+1

**Comment by booxood** [comment]
+1

**Comment by evilebottnawi** [comment]
@TrustNik @bcharp can you describe use case?

**Comment by cxyxc** [comment]
When my html files in different levels, I wish [chunkname] to differentiate different chunks to add different publicPath .

**Comment by jezeniel** [comment]
@evilebottnawi This would also be useful when you use webpack with django you need predictable filenames to load static files. On large projects there are instances that assets will have similar filenames.
This would serve as a namespace to prevent filename conflict.

**Comment by evilebottnawi** [comment]
@sokra Is it possible to implement this in `loader` or have workaround?

**Comment by d3viant0ne** [comment]
If someone wants to PR in a change & tests for this, we will consider it.

**Comment by micgro42** [comment]
This seems to be impossible on a fundamental level. The apparently correct approach (which worked for me, after several hours of searching) is to implement "multiple configurations".
Source: https://github.com/webpack/webpack/issues/6124#issuecomment-351647892
Doku: https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations
