### ISSUE TITLE
Output path with Windows path characters (and drive letters) causes the compilation to stuck

### ISSUE THREAD

**Issue by hugmanrique** [webpack-contrib/file-loader#281]
* Operating System: Windows
* Node Version: 9.8.0
* NPM Version: 6.0.0
* webpack Version: 4.9.1
* file-loader Version: 1.1.11

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```bash
  # Using webpack-command
  $ webpack --run-prod --progress
```

##### webpack.config.js

```js
const appDirectory = fs.realpathSync(process.cwd());
const outputPath = path.resolve(appDirectory, 'dist/assets');

const config = {
  // Add entrypoint that imports any asset that matches the rule below
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        use: {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath
          }
        }
      }
    ]
  }
};
```

### Expected Behavior

`file-loader` places all the modules that match the test regex on `outputPath`.

### Actual Behavior

`webpack` gets stuck at Emitting (95%)

### How Do We Reproduce?

- Place any `png` photo on the same dir as the webpack config above
- Set the entrypoint to that image:  `entry: 'image.png'`
- Run the command provided above
- Webpack will get stuck at 95%

The following characters are valid Windows dir names: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

Similar to https://github.com/webpack/webpack/issues/2908, but didn't mention this issue with file-loader.

**Comment by evilebottnawi** [comment]
@hugmanrique looks like problem in `webpack`. Can you provide reproducible test repo (not step)? Because i can't reproduce locally.

**Comment by hugmanrique** [comment]
Will do once I have some free time.

**Comment by tamimcsedu19** [comment]
I have the same problem.

**Comment by evilebottnawi** [comment]
Problem in webpack https://github.com/webpack/webpack/issues/2908, we can't solve this here, feel free to send a PR in webpack
