### ISSUE TITLE
regExp not working as described.

### ISSUE THREAD

**Issue by IngoVals** [webpack-contrib/file-loader#283]
* Operating System: Windows 10
* Node Version: v8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.9.1
* file-loader Version: 1.1.11

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```bash
  # paste the CLI command you're using. if this isn't applicable, it's safe to remove.
  $ npx webpack --mode development
```

##### webpack.config.js

```js
                test: /\.php$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            regExp: /\/php\/((?:[a-z0-9]+\/)*)[a-z0-9]+\.php$/,
                            name: '[1]-[name].[ext]',
                          }
                    }
                ]
```

### Expected Behavior

I'm trying to move my PHP files from src/php/ to the dist folder using the file-loader.
problem is I want to keep the relative file structure from within the php folder. So if they are top level there, they are top level in the php folder, they get top level in dist, if they are within a folder called /inc they appear in the same kind of folder.

Files are moved into the dist folder with the relevant file structure from within the PHP folder

### Actual Behavior

Files appear as [1]header.php, or [1]index.php etc.

**Comment by evilebottnawi** [comment]
@IngoVals don't use `file-loader` to moving files, use `CopyWebpackPlugin` or other plugins for this.

**Comment by evilebottnawi** [comment]
@IngoVals Can you create minimum reproducible test repo?

**Comment by IngoVals** [comment]
Thanks for the CopyWebpackPlugin suggestion, looks to be what I need. I was initially trying to use the html-loader and extract-loader to fulfill svg imports in PHP but I'm moving over to twig html needs so I still only needed to move the files.

I'll see if I can reproduce the result in a separate repo.

I'm wondering if it is the non-capturing group in the regex that is causing the issue.

**Comment by IngoVals** [comment]
https://github.com/IngoVals/fileloaderbugrepo

Just `npm install` and run `npm start` and notice the names of the php files in the dist folder.

**Comment by IngoVals** [comment]
Could we remove the "needs more info flag" ?

**Comment by IngoVals** [comment]
I tracked this down, in my regex i'm using linux style path delimiters ( forward slashes ) while I was running this on a windows machine. This results in the resourcePath having backward slashes.

This will of course not be system agnostic this way. I could change the regex to look for either forward or backward slash. But this is more a problem with loader-utils.

**Comment by IngoVals** [comment]
[Relevant issue on loader-util](https://github.com/webpack/loader-utils/pull/37)
