### ISSUE TITLE
It still seems to work with webpack 3, did something break?

### ISSUE THREAD

**Issue by light24bulbs** [webpack-contrib/file-loader#284]
If you released changes that broke webpack 3 compatibility, that is a major version bump, not a bug fix.  Everyone is using `^` in their package.json by default, so you may be breaking legacy apps by making breaking changes without using semver.

**Comment by renestalder** [comment]
I also wondered about the Webpack v4.0.0 requirement in the readme but no visible major bump. So is it required to use Webpack 4 to use the latest version of file loader?

**Comment by evilebottnawi** [comment]
Loader works find with `webpack@3` and `webpack@4`. What is problem?

**Comment by renestalder** [comment]
That the README says it requires a minimum of Webpack 4.

**Comment by evilebottnawi** [comment]
@renestalder see, feel free to send PR, readme is misleading
