### ISSUE TITLE
File-loader v1.1.11 is causing fonts to render differently to the source

### ISSUE THREAD

**Issue by benstaker** [webpack-contrib/file-loader#285]
* Operating System: Windows 10 64-bit
* Node Version: v6.12.2
* NPM Version: v3.10.10
* webpack Version: v2.7.0
* file-loader Version: v1.1.11

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js
...
     {
        test: /\.(eot|svg|ttf|woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
        include: [CoreConfig.paths.npm, CoreConfig.paths.public],
        use: [{ loader: 'file-loader', options: { name: '[name]-[hash].[ext]', publicPath: '/assets/' } }]
      },
...
```

### Expected Behavior

Our icons should not have a white line in the circle.

![image](https://user-images.githubusercontent.com/2591500/42585101-a642a152-852c-11e8-8307-44c71218f5e3.png)

### Actual Behavior

Icons have a white line in the circle.

![image](https://user-images.githubusercontent.com/2591500/42585037-7e3b85c0-852c-11e8-9144-f8566ca78a3c.png)

### Description

There seems to be some processing on the font files passed through file-loader that is causing the fonts to render differently. When resizing the font to 67px in Google Chrome it seems to render fine, but this is not ideal as we don't need it this large. Downgrading to **v1.1.10** has fixed the issue, so I suspect this was a recent change in **v1.1.11** that has caused this. See the diff between the original file and the served file below.

![image](https://user-images.githubusercontent.com/2591500/42585281-12d99fd2-852d-11e8-98e7-d58a4b7b9fc6.png)

**Comment by evilebottnawi** [comment]
@benstaker we don't modify content, just provide link to asset, looks the problem in not related to `file-loader`, check you plugins and other loaders

**Comment by benstaker** [comment]
@evilebottnawi this is not an issue with file-loader. Downgrading the package a minor version triggered a reset of the cache in `hard-source-webpack-plugin`. Thanks for your time.
