### ISSUE TITLE
Appending base directory/URL at run-time

### ISSUE THREAD

**Issue by squaresun** [webpack-contrib/file-loader#290]
* Operating System: Win 7 (64-bit)
* Node Version: v6.11.4
* NPM Version: 5.6.0
* webpack Version: 3.10.0
* file-loader Version: 1.1.11

This is a question about appending base directory/URL at run-time. For example, the base directory/URL is stored in a global var with string and it is defined when browser open the page. Is there any option or config managed to achieve this?

Since I don't want to replace all `require(./assets/img.png)` to `BASE_URL + require(./assets/img.png)` in my code, I am wondering if file-loader support this feature.

I've tried to modify this [line](https://github.com/webpack-contrib/file-loader/blob/8f18b1ecc750a3e9f0a5bc710427d2de8ef9e307/src/index.js#L63) by replacing `__webpack_public_path__ ` to my global var, and it works, but is there any better solution?

Thank you.

**Comment by evilebottnawi** [comment]
@squaresun Change url in runtime is not safe, but if you know what you do change `__webpack_public_path__` as you write above, it is good solution
