### ISSUE TITLE
What is the difference between file-loader and the copy-webpack-plugin?

### ISSUE THREAD

**Issue by givanse** [webpack-contrib/file-loader#291]
Both seem to achieve the same, except that the file-loader requires a newer Node. One is a loader and the other a plugin, but for copying static files does it matter?

**Comment by michael-ciniawsky** [comment]
The `file-loader` make the url available for programmtic usage, while the `copy-webpack-plugin` is basically the webpack wrapper/integration (memory file system, file watching etc) of the `cp` command to simply copy files from  A => B 🤷‍♂️ 

### `file-loader`

```js
import url from './file.png'

function Component (props) {
   return (
     <div>
       // dynamic
       <img src={url}>
     </div>
   )
}
```

Also some loaders may work in conjuction with the `file-loader`, e.g the `css-loader` transforms `url(./file.png)` => `require('./file.png')` internally, which requires to `file-loader` to work (it handles the `require('./file.png')` module request)

### `copy-webpack-plugin`

```js
function Component (props) {
   return (
     <div>
        // static (handcoded)
       <img src="path/to/dist/image.png">
     </div>
   )
}
```
