### ISSUE TITLE
webpack file-loader: file not found in bundle, but file exists where/as expected upon build

### ISSUE THREAD

**Issue by ddaaggeett** [webpack-contrib/file-loader#292]
[here](https://github.com/ddaaggeett/podware/issues/1#issue-347227754) is an issue i'm facing with webpack 4.16.3.

i am not sure why my browser would not be able to load bundled image assets after implementing webpack and file-loader properly with electron

**Comment by evilebottnawi** [comment]
@ddaaggeett please create minimum reproducible test repo

**Comment by ddaaggeett** [comment]
steps to reproduce:
1. `git clone https://github.com/ddaaggeett/podware.git`
    or
    `git clone git@github.com:ddaaggeett/podware.git`
2. `cd podware`
3. `git fetch origin file-loader`
4. `git checkout file-loader`
5. `npm install`
6. `npm start`
7. wait for webpack to build, then reload the electron app and you'll see the error: `net::ERR_FILE_NOT_FOUND`

[here](https://github.com/ddaaggeett/podware/tree/file-loader) is the repo branch we're speaking about.

relevant files include:
[package.json](https://github.com/ddaaggeett/podware/blob/file-loader/package.json)
[webpack.config.js](https://github.com/ddaaggeett/podware/blob/file-loader/webpack.config.js)
[Screenshots.jsx](https://github.com/ddaaggeett/podware/blob/file-loader/src/components/Screenshots.jsx)

**Comment by ddaaggeett** [comment]
i ended up fixing this issue [here](https://github.com/ddaaggeett/podware/issues/1#issuecomment-410491717), but would still like to know why file-loader would not be an acceptable method to load images...
