### ISSUE TITLE
Assets are not being read but successfully created to output directory

### ISSUE THREAD

**Issue by jairusd** [webpack-contrib/file-loader#297]
* Operating System: windows 10
* Node Version: 10.6.0
* NPM Version: 6.1.0
* webpack Version: 4.16.1
* file-loader Version: 2.0.0

This issue is for a:

- [x ] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

I'm trying to setup file loader to load images but it doesn't compile although it emits the file to the the output directory as expected.

https://stackoverflow.com/questions/52405621/setting-up-file-loader-in-webpack-produces-error-during-build-time

##### CLI Command

```bash
  # paste the CLI command you're using. if this isn't applicable, it's safe to remove.
  $ {webpack --mode development --watch}
```

##### webpack.config.js
https://gist.github.com/jairusd/c895a33c61bc65ed509c06ce91bfd812

### Expected Behavior
compiles successfully and outputs assets to target directory

### Actual Behavior
unsuccessful compilation but outputs assets to target directory

### How Do We Reproduce?

https://gitlab.com/jairus.jsx/react-initialzr
1. yarn
2. yarn start

**Comment by michael-ciniawsky** [comment]
```js
{
   test: /\.scss$/,
-   use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader', 'sass-loader']
+   use: [ MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader', 'sass-loader' ]
}
```

Use either the `style-loader` or the `MiniCSSExtractPlugin.loader`, both won't work together

```js
env === 'development' ? 'style-loader' : MiniCSSExtractPlugin.loader
```

**Comment by jairusd** [comment]
hi @michael-ciniawsky tried that too. Besides, project was already working without file-loader. It is when i plugged file-loader that I started getting this issue and that it is not reading image files. Can you please reevaluate this? Thanks a lot.

**Comment by michael-ciniawsky** [comment]
With my suggested changes 

### `yarn/npm run build:dev`
![output](https://user-images.githubusercontent.com/5419992/45787695-dc1f4600-bc76-11e8-9dfd-f0400a016b45.png)
![logs](https://user-images.githubusercontent.com/5419992/45787709-eb9e8f00-bc76-11e8-8231-9cdc6d3dc059.png)

`build:production` also seems to work as expected... `yarn start /npm start` fails but I don't know what exactly you are trying to do there, but it's definitely unrelated to the `file-loader`

> ⚠️ **Don't push `.env` files to public repos, add this file to `.gitignore`** :)

**Comment by michael-ciniawsky** [comment]
```
$ concurrently --kill-others "yarn serve:dev" "yarn build:dev"
$ webpack --mode development --watch
$ cross-env NODE_ENV=development nodemon src/server/index.js --exec babel-node
[0] [nodemon] 1.18.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `babel-node src/server/index.js`
[1]
[1] webpack is watching the files...
[1]
[0] /Users/Cini/Github/webpack/contrib/.temp/react-initialzr/src/assets/img/login.jpg:1
[0] (function (exports, require, module, __filename, __dirname) { ����
[0]                                                               ^
[0]
[0] SyntaxError: Invalid or unexpected token
[0]     at new Script (vm.js:73:7)
[0]     at createScript (vm.js:245:10)
[0]     at Object.runInThisContext (vm.js:297:10)
[0]     at Module._compile (internal/modules/cjs/loader.js:657:28)
[0]     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)

 ====> [0] at Object.newLoader [as .js] (/.temp/react-initialzr/node_modules/pirates
/lib/index.js:88:7) <=====

[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0] [nodemon] app crashed - waiting for file changes before starting...
```

[`pirates`](https://www.npmjs.com/package/pirates) is used by `babel-node` to my knowledge and it seems to be trying to require the assets when 'Properly hijacking require'. I get the server to run and serve the files once I build the files in `src/server` with `babel` CLI **beforehand** and remove the `--exec babel-node` flag from the scripts. But there are a lot of other bugs so don't expect it to actually work as intended. 

Reduce the complexity of your current code in terms of tooling and also maybe add SSR later on...
