### ISSUE TITLE
Loading fonts through css files (`@import...`) do not work - new font files do not get created at all

### ISSUE THREAD

**Issue by hAtul89** [webpack-contrib/file-loader#299]
Loading fonts (and files) from a css file do not work for me. And I reviwed every tutorial/post. 

	module: {
	rules: [	// Vue Files 
				{
					test: /\.vue$/,
					exclude: /node_modules/, 
					loader: 'vue-loader', 
					options: {
								loader: {
									scss: 'vue-style-loader!css-loader!sass-loader', 
									css: 'vue-style-loader!css-loader'
								}
					}
				},
				// JS files 
				{
					test: 		/\.js$/,
					exclude: 	/node_modules/,
					use: {
					  		loader: "babel-loader"
					}
				},
				// CSS / SASS files 
				{
					test: /\.(sa|sc|c)ss$/,
					// test: /\.scss$/,
						use: [
								{
									loader: MiniCssExtractPlugin.loader,
								},
								{
									loader: 'css-loader',
									options: {
											url: false,
											minimize: true,
											sourceMap: true
									}
								},
								{
									loader: 'postcss-loader'
								},
								{
									loader: 'sass-loader',
									options: {
											sourceMap: true, 
											minimize: true
									}
								}
						]
				},
				{
					test: /\.(png|gif|jpe|jpg|woff|woff2|eot|ttf|svg)(\?.*$|$)/,
					use: [
							{
								loader: 'file-loader',
					            options: {
						            // name: 		'[path][name].[ext]',
						            name: 		'[name].[ext]',
						            outputPath: './public/fonts/',
						            publicPath: './public/fonts/'
					            }
					         }
					]
				}

And this is my SCSS file where I load 6 icons/fonts libraries:  

    @import 'variable';
    
    // Colors
    @import 'colors/default';
    @import 'colors/green';

    // This is for the icons
    @import '../assets/icons/font-awesome/css/fontawesome-all.css';
    @import '../assets/icons/simple-line-icons/css/simple-line-icons.css';
    @import '../assets/icons/weather-icons/css/weather-icons.min.css';
    @import '../assets/icons/themify-icons/themify-icons.css'; 
    @import '../assets/icons/flag-icon-css/flag-icon.min.css';
    @import "../assets/icons/material-design-iconic-font/css/material-design-iconic-font.min.css";
    
    
    // This is the core files
    @import 'core/core';
    @import 'widgets/widgets';
    @import 'responsive';
  

When running `npm run dev` (or others) I don't get any error mentioning fonts. 

When loading my website I get these URLS refrences in the "network" pannel: 

    https://mywebsite.potato.com/public/webfonts/fa-regular-400.woff
    https://mywebsite.potato.com/public/fonts/Simple-Line-Icons.ttf?-i3a2kk

pointing on font files that don't even exist in my directory (or at least do't get created..) 
And I did specify a `publicPath` so I expect the new CSS compiled file will point to the publicPath.. and the `outputPath` doesn't seem to respond. no file is getting created in my folder `./public/fonts/`

[![enter image description here][1]][1]

Tried following: 
https://chriscourses.com/blog/loading-fonts-webpack 
https://medium.com/@raviroshan.talk/webpack-understanding-the-publicpath-mystery-aeb96d9effb1
and doesn't seem to work. 

Adding CSS screentshot 

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/8RIwr.png
  [2]: https://i.stack.imgur.com/2mNGp.png

**Comment by hAtul89** [comment]
> Remove `outputPath` and `publicPath` for `file-loader`

This was my first try, and it didn't work (gave the exact same result).  
That's why I added the publicPath and outputPath so it might maybe understand where to create the files and how to reference them in the generated CSS.

**Comment by evilebottnawi** [comment]
@hAtul89 please provide minimum reproducible test repo, look you have invalid `publicPath` in config

**Comment by hAtul89** [comment]
> @hAtul89 please provide minimum reproducible test repo, look you have invalid `publicPath` in config

Here you go
https://github.com/hAtul89/no-files

**Comment by PlayMa256** [comment]
Create a reproducible and simple example, we are not able to run the ui interface properly, it does not load

**Comment by hAtul89** [comment]
@PlayMa256  @evilebottnawi  

Done. 
I have added a new dummy `index.php` file you can open loading the `css` and `js` files.

**Comment by hAtul89** [comment]
Resolved: 

```
								loader: 'css-loader',
								options: {
										url: false,

```

Was the problem.. 
Just needed to remove the url. Haven't noticed it was set..

**Comment by hAtul89** [comment]
Resolved: 

```
								loader: 'css-loader',
								options: {
										url: false,

```

Was the problem.. 
Just needed to remove the url. Haven't noticed it was set..
