### ISSUE TITLE
Use abolute path webpack

### ISSUE THREAD

**Issue by dersar00** [webpack-contrib/file-loader#300]
Hello!
I'm using React as frontend in my Phoenix app, and I want to use absolute path for example to display some image that's present in other place in my machine. My project tree below:
```
.
├── css
│   ├── app.css
│   ├── file_component.css
│   ├── phoenix.css
│   └── uppy.min.css
├── js
│   ├── app.js
│   ├── components
│   │   ├── files
│   │   │   ├── comp1.js
│   │   │   └── comp2.js
│   └── socket.js
├── node_modules
├── package-lock.json
├── package.json
├── static
│   ├── favicon.ico
│   ├── images
│   │   ├── empty_image.png
│   │   └── phoenix.png
│   └── robots.txt
├── text.txt
└── webpack.config.js
```
If I try to use for example `img` tag in my `comp1.js` I can add to src attribute only files from `images` library, so my `src` looks like `image/empty_image.png`.
How I can use absolute path instead it?

General info:
    - OS: ubuntu 18.04
    - npm: v5.6.0
    - node: v9.5.0
    - webpack: v4.19.1
    - file_loader: v2.0.0

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Without configuration i can't help
