### ISSUE TITLE
Improve `options.regExp` documentation

### ISSUE THREAD

**Issue by leonardoanalista** [webpack-contrib/file-loader#31]
Hi,

I am trying to match and use it on the loader: E.g.:

```
      {
        test: /(.*)\/assets\/img\/(.*)\.(svg|png|gif|jpg|jpg)$/,
        loader: 'file?name=/assets/[0]/img/[name].[ext]'
      },
```

Looking at: https://github.com/webpack/file-loader/blob/master/test/correct-filename.test.js
I can't find an example of:

"[N] the N-th match obtained from matching the current file name against the query param regExp"

Is this possible?

cheers
Leonardo

**Comment by anselmdk** [comment]
I don't think this is currently supported, I think the readme is taken from https://github.com/webpack/loader-utils

I'd love for this to work as well, as I'd like to place images in sub directories.

**Comment by danahartweg** [comment]
Was looking through this today, and it did have me stumped initially as well. What you have to do is supply an additional param of ```regExp``` on the query string with the regex you want to match against the source file path.

In my case, my source path is something like ```src/moduleName/images/image.png```, and my build directory is ```build/modules/moduleName```. To have the file loader place the images in ```build/modules/moduleName/images```, the regex and naming I used is: ```regExp=src\/(.+?)\/&name=[1]/images/[hash].[ext]```.

The regex isn't perfect, but without spending hours on it, I was unable to generate a matcher that would extract all groups between slashes that started after a particular string.

Anyway, hope this helps someone place files in a subdirectory inside their module entry point!

**Comment by Benno007** [comment]
That didn't work for me... trying to get the query string applied in the file for cache busting icon fonts. Just kept coming out as font.eot?[1] :(
```
{
                test: /\.(eot|ttf|woff|woff2|svg)/i,
                loader: 'url-loader?regExp=\\.[ext]\\?(.+)&limit=1&name=assets/[name].[ext]?[1]
}
```

**Comment by shri3k** [comment]
@Benno007 don't think `url-loader` has this option yet. I'd be happy to be proven wrong though.

**Comment by pixeldrew** [comment]
After just stumbling with this myself.

You want to use the regExp option, it doesn't use the regExp from the test. [0] in regex is the whole capture, you want the second capture [2].

The regex your using is a little greedy, imagine the name of your import is 'img/animage.jpg'.  The regex will get 'img/animage'
 
The name templage [2]/img/[name].[ext] would then output the file as img/animage/img/animage.jpg

**Comment by evilebottnawi** [comment]
@pixeldrew @leonardoanalista @danahartweg we can implement `customInterpolateName` from https://github.com/webpack/loader-utils/blob/ddf64e49c5871c7229a5a536656a711479c08516/lib/interpolateName.js#L89 and it is allow to using custom function to set name. Will it help to solve your problem?

**Comment by pixeldrew** [comment]
I can't see how having that option would hurt. I was able to fix my issue, perhaps some clearer documentation would also help.
