### ISSUE TITLE
webpack doesn't generate output folder(dist in my case) after upgrading to file-loader@3.0.0

### ISSUE THREAD

**Issue by pzmosquito** [webpack-contrib/file-loader#311]
* Operating System: MacOS 10.13.6
* Node Version: 10.14.1
* NPM Version: 6.5.0
* webpack Version: 4.28.0
* file-loader Version: 3.0.0

### Expected Behavior

webpack should generate output folder(`dist` in my case) normally

### Actual Behavior

webpack did not generate output folder(`dist` in my case)

### Code

```js
export default {
    mode: "production",
    resolve: {
        extensions: ["*", ".js", ".jsx", ".json"]
    }
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                include: path.resolve(__dirname, "src"),
                use: ["babel-loader"]
            },
            {
                test: /\.(jpe?g|png|gif|ico)$/i,
                use: ["file-loader"]
            }
        ]
    }
};
```

### How Do We Reproduce?

I use `babel-node` to load the config: `babel-node build.js`

below are `build.js`
```js
import webpack from "webpack";
import config from "webpack.config";

webpack(config).run();
```

**Comment by evilebottnawi** [comment]
@pzmosquito no changes with emit, please provide minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@pzmosquito tests works good https://github.com/webpack-contrib/file-loader/pull/312, looks something wrong with your configuration

**Comment by evilebottnawi** [comment]
Please try https://github.com/webpack-contrib/file-loader/releases/tag/v3.0.1, feel free to feedback

**Comment by evilebottnawi** [comment]
Find a problem

**Comment by pzmosquito** [comment]
@evilebottnawi I was trying to come up with a minimum code that is similar to my set up, but update to 3.0.1 worked for me. Did you just find another problem for 3.0.1?

**Comment by evilebottnawi** [comment]
@pzmosquito yep, not related to you, very rare use case, good news what works as expected
