### ISSUE TITLE
Update documentation to reflect Webpack v4

### ISSUE THREAD

**Issue by alanyinjs** [webpack-contrib/file-loader#314]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The doc for file-loader has referred to the style recommended by Webpack 3 in multiple places where instead of using `use`, and specify `loader` and `options` inside the `use` object, `loader` and `options` have been used directly inside rules.
![screen shot 2018-12-26 at 11 58 59 pm](https://user-images.githubusercontent.com/25688258/50446683-5c3a0380-096a-11e9-8448-605608366311.png)

### Your Proposal for Changes
Just an example of how the above could possibly be changed: 
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]',
            },
          },
        ],
      },
    ],
  },
};
```

**Comment by evilebottnawi** [comment]
@alanyinjs both examples valid for `webpack@3`, `webpack@4` and `webpack@5`,  you need `use` property when you want using multiple loaders, like:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'other-loader',
            options: {
              // ...options
            },
          },
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]',
            },
          },
        ],
      },
    ],
  },
};
```

**Comment by evilebottnawi** [comment]
@alanyinjs hm, let's update docs
