### ISSUE TITLE
Mp3 File isnt being built

### ISSUE THREAD

**Issue by liamcharmer** [webpack-contrib/file-loader#317]
ERROR in ./assets/sounds/rain-bg.mp3 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file) 

```
config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        }),
         config.module.rules.push({
            test: /\.(ogg|mp3|wav)$/i,
            loader: 'file-loader'
          })
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
in short you don't have loader for `mp3` extensions, looks your code is not monified webpack config
