### ISSUE TITLE
Wrong Symlink for folder mode_modules/bin/file-loader/

### ISSUE THREAD

**Issue by jmas** [webpack-contrib/file-loader#318]
* Operating System: macos / linux
* Node Version: latest
* NPM Version: any
* webpack Version: 3.0.0
* file-loader Version: 2.0.0 **!!!**

### Expected Behavior / Situation

Do not create Symlink for folder `mode_modules/bin/file-loader/`.

### Actual Behavior / Situation

Symlink for folder `mode_modules/bin/file-loader/` is created.

### Modification Proposal

Our build and files sync system is down when it see folder in `node_modules/bin/file-loader/`. Any reasons for creating folder there?

### How to fix?

Remove line https://github.com/webpack-contrib/file-loader/blob/v2.0.0/package.json#L10

**Comment by evilebottnawi** [comment]
Already fixed https://github.com/webpack-contrib/file-loader/blob/master/package.json and published, just reinstall `node_modules` (`rm -r node_modules package-lock.json && npm cache clear -f && npm i`)
