### ISSUE TITLE
How to load SVG images?

### ISSUE THREAD

**Issue by UlpiusCode** [webpack-contrib/file-loader#319]
How I can load SVG images in html and background: url()?

Thanks a lot!

**Comment by evilebottnawi** [comment]
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif|test)$/,
        use: [
          {
            loader: 'file-loader',
            options: {},
          },
        ],
      },
    ],
  },
};
```

Also it is bug tracker, not QA service, please use `stackoverflow` or `gitter` for questions, thanks

**Comment by UlpiusCode** [comment]
Ok, this rules is for "png, jpg, gif", but for svg? I can use file-loader foar loading svg images? if not then what can I use?

**Comment by evilebottnawi** [comment]
@UlpiusCode i fixed snippet above, just add `svg` in list

**Comment by Jandyk** [comment]
ok I understand, but  this example is right? 
```
{
      test: /\.(png|jpg|svg|gif)$/i,
      use: [{
             loader: 'url-loader',
             options: {
                  name: '[path][name].[ext]?hash=[hash:20]',
                  limit: 8192
             }
      }]
}
```
