### ISSUE TITLE
Infinite recompilation with `output.path` and `webpack --watch`

### ISSUE THREAD

**Issue by StanAngeloff** [webpack-contrib/file-loader#322]
* Operating System: Linux/Ubuntu 16.04
* Node Version: `v8.15.1`
* NPM Version: `6.9.0`
* webpack Version: `4.29.6`
* file-loader Version: `3.0.1`

### Expected Behavior

When using `output.path` in `webpack.config.js` I expect `webpack --watch` to react to file changes only once.

### Actual Behavior

`file-loader` puts `webpack --watch` in a constant re-compilation cycle.

### Code

```sh
#!/bin/sh

# Put this in script.sh in an empty directory and execute via $ sh script.sh

echo '{}' > package.json

npm i --save-dev webpack@4 webpack-cli@3 file-loader@3

cat > webpack.config.js <<-'EOF'
module.exports = {
    mode: 'development',
    entry: './images/pixel.png',
    output: {
        path: __dirname,
    },
    module: {
        rules: [
            {
                test: /\.png/,
                loaders: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: path => '/compiled/[name].[ext]?[hash]',
                        }
                    },
                ],
            },
        ],
    },
};
EOF

mkdir -p images/
touch images/pixel.png

NODE_ENV=development ./node_modules/.bin/webpack -w --progress --hide-modules
```

### How Do We Reproduce?

Run the script above which will install all Node dependencies, create the necessary `webpack.config.js` file and run the `--watch` sub-command.

Note how output is constantly printed and erased below the line `Entrypoint main = main.js`

If `output.path` or `module.rules.0.loaders.0.options.name` is omitted, this bug does not manifest itself.

__Originally reported as part of https://github.com/JeffreyWay/laravel-mix/issues/1942__

**Comment by evilebottnawi** [comment]
Problem solved?

**Comment by StanAngeloff** [comment]
I'm not sure, the original issue in Laravel Mix is still outstanding, I just can't get to a minimal reproducible state :(

**Comment by evilebottnawi** [comment]
@StanAngeloff i think problem deeply than in `file-loader`, plugin or loader add new file to graph so webpack recompile, we it is happens again and webpack recompile, starts to debug with plugins
