### ISSUE TITLE
Trying to load json file using file-loader  , it work before build but when create build it just load the path of file instead of content 

### ISSUE THREAD

**Issue by shafiqkhuidad** [webpack-contrib/file-loader#324]
* Operating System:Window 10
* Node Version: v10.15.3
* NPM Version:6.4.1
* webpack Version:4.30.0
* file-loader Version:3.0.1

### Expected Behavior

should log values inside x.json file 

### Actual Behavior

it log name of the generated json file in the build 
### Code
i have created simple demo , here is the link to code repo
https://github.com/shafiqkhuidad/WebpackLoaders-Demo
### How Do We Reproduce?

* clone repo 
* npm install 
* npm run build 
* node x.js 
* cd build & node index.bundle.js

**Comment by evilebottnawi** [comment]
It is expected, because `file-loader` generate file and doesn't parse content. You don't need `file-loader` for `json` in `webpack@4`. Also using `file-loader` increase you bundle size because tree shaking doesn't work

**Comment by shafiqkhuidad** [comment]
@evilebottnawi thanks , i want to use same json file before and after build

**Comment by shafiqkhuidad** [comment]
![image](https://user-images.githubusercontent.com/21343093/56210714-d99b9800-606f-11e9-9cc4-62fba2da2212.png)
 
if you see here the index.bundle.js file have reference to that json file . 
i have json file-loader it just append the content of json file like that : 
![image](https://user-images.githubusercontent.com/21343093/56210899-3008d680-6070-11e9-9f99-107c2a0a4b2a.png)
but i want to load this json content from file.

**Comment by evilebottnawi** [comment]
Use `javascript/auto` or `json` https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L60

**Comment by shafiqkhuidad** [comment]
i have already try this option it doesn't work for me . It append the json file into bundle.js , i don't want this .
i want to copy json file to build folder and then the generated build(bundle.js) file should use that copied file ?

**Comment by evilebottnawi** [comment]
It is impossible, use multicompile mode

**Comment by shafiqkhuidad** [comment]
Thanks @evilebottnawi , can you please share some link or example of multiple mode ?

**Comment by evilebottnawi** [comment]
@shafiqkhuidad looks on documentation
