### ISSUE TITLE
Add a flag to enable ES module syntax

### ISSUE THREAD

**Issue by joseprio** [webpack-contrib/file-loader#338]
### Feature Proposal
At the moment the generated JS module uses the commonJS syntax. It would be useful to have an option that would use the ES module syntax instead.

### Feature Use Case
Old commonJS syntax prevents module concatenation in Webpack. It may help tree shaking in some cases too.

**Comment by joseprio** [comment]
Happy to create a pull request if needed.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by evilebottnawi** [comment]
Done in master, release will be soon
