### ISSUE TITLE
Add note about JSX usage

### ISSUE THREAD

**Issue by kswope** [webpack-contrib/file-loader#35]
Just spent the last few hours (more than a few?) on this problem and it was entirely avoidable but I haven't seen any docs on it.

If you are using JSX (and therefor probably babel-loader) you do not need to use file-loader or url-loader for img tags in the JSX, its somehow already handled by babel.  I somehow knew JSX was handled by babel-loader, but I have no idea how that came about, but as a bonus it handles the stuff of file-loader.

I eventually figured this out because I was doing this, which seems to be the right way to do it

```
<img src={require('../../assets/images/image.png')} />
```

But having png files handled by both babel-loader and file-loader meant the browser was displaying a broken image, which I eventually downloaded and opened, and instead of ugly binary, it was this :)

```
module.exports = __webpack_public_path__ + "265a6261bff86f8c7bc3c98c5eba3583.png"

```

**Comment by legendary-mich** [comment]
@kswope 
I had the same issue. I'm using ts-loader, though. It would be great if title of this issue was more to the point. For example: "require () creates two files instead of one". Then, I would have a chance to find this answer knowingly, and not like it is right now, by accident.

Thanks for Sharing, though. :)

**Comment by tobycox** [comment]
Ah thank god I found this. I agree it would be great to change the title of the issue for future people who are banging their heads against this.
I was searching for things like "broken images webpack" and "broken images file-loader".
Hopefully these breadcrumbs will lead people here...

**Comment by SpaceK33z** [comment]
Anyone wants to update the readme with PR?

**Comment by oieduardorabelo** [comment]
I was having this problem today and, downgrading to `file-loader": "0.11.2"`, worked as expected for me.

```javascript
"babel-core": "6.26.0",
"babel-loader": "7.1.2",
"babel-preset-react-app": "3.0.2",
"file-loader": "0.11.2" // using 1.0.0, doesn't work 
```

**Comment by evilebottnawi** [comment]
@oieduardorabelo known issue, should be fixed after https://github.com/webpack-contrib/file-loader/pull/183
