### ISSUE TITLE
Strange filename for urls with hash

### ISSUE THREAD

**Issue by 719media** [webpack-contrib/file-loader#350]
- Operating System: 
- Node Version: 13.2
- NPM Version: 6.13.1
- webpack Version: 4.41.2
- file-loader Version: 5.0.2

### Expected Behavior

Same output for compilation

### Actual Behavior

```
-  src: url(/assets/dev/fonts/fa-solid-900.eot?#iefix) format("embedded-opentype"), url(/assets/dev/fonts/fa-solid-900.woff2) format("woff2"), url(/assets/dev/fonts/fa-solid-900.woff) format("woff"), url(/assets/dev/fonts/fa-solid-900.ttf) format("truetype"), url(/assets/dev/fonts/fa-solid-900.svg#fontawesome) format("svg");
+  src: url("[object Module]?#iefix") format("embedded-opentype"), url(/assets/dev/fonts/fa-solid-900.woff2) format("woff2"), url(/assets/dev/fonts/fa-solid-900.woff) format("woff"), url(/assets/dev/fonts/fa-solid-900.ttf) format("truetype"), url("[object Module]#fontawesome") format("svg");
```

### Code

```js
{
    test: /\.(eot|ttf|svg)$/,
    loader: 'file-loader',
  },
```

### How Do We Reproduce?

Just use font awesome in your build. Like
```
@import "~@fortawesome/fontawesome-free/scss/fontawesome";
@import "~@fortawesome/fontawesome-free/scss/solid";
```

**Comment by evilebottnawi** [comment]
Update css-loader to latest version or disable ES modules https://github.com/webpack-contrib/file-loader#esmodule

**Comment by evilebottnawi** [comment]
If it not solve your problem please open new issue in css-loader with reproducible test repo

**Comment by 719media** [comment]
Adding esModule: false to the loader worked. I'm not exactly sure why that has that effect, but I appreciate the help.

**Comment by lerit** [comment]
@evilebottnawi 
update css-loader not resolve this issue:"css-loader": "^3.5.3"
only work with:esModule: false 
```
 <img  src="~assets/abc.jpg" />
```
current file-loader:v6.0.0
