### ISSUE TITLE
nosupport .ttc Format font file

### ISSUE THREAD

**Issue by imsole** [webpack-contrib/file-loader#359]
Sorry, there's no demo address here; just want to make sure that. TTC font file loading is not supported

**Comment by anikethsaha** [comment]
can you share your webpack config ?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Just add `ttc` to `test` property

**Comment by imsole** [comment]
I made a mistake before. That's good

```
  chainWebpack: config => {
    config.module
      .rule('file')
      .test(/\.TTC$/)
      .use('file-loader')
      .loader('file-loader')
      .end();
  },
```
