### ISSUE TITLE
enhance publicPath and emitFile option

### ISSUE THREAD

**Issue by wusiquan** [webpack-contrib/file-loader#360]
Feature Proposal
hope `publicPath` option  support `async` function and `emitFile` option support function type, a function return bool, for user to decide whether to emit File.

Feature Use Case
images uploaded to static server or cdn, related code could write in `publicPath` directly.
Once a file has been uploaded, eg. check the start substring of publicPath in `emitFile` function, could not been emitted or it would add size of package

**Comment by evilebottnawi** [comment]
Sorry it is out of scope `file-loader`, you can create plugin for doing it
