### ISSUE TITLE
Path variables does not work inside publicPath

### ISSUE THREAD

**Issue by acqsk** [webpack-contrib/file-loader#361]
Path variables for example [ext] does not work inside output.publicPath :-(

("@babel/core": "^7.7.7")

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
