### ISSUE TITLE
Path variables does not work inside publicPath

### ISSUE THREAD

**Issue by acqsk** [webpack-contrib/file-loader#362]
- Operating System: Windows 10 + Ubuntu WSL
- Node Version: 10.18.1
- NPM Version: 6.13.6
- webpack Version: 4.41.5
- file-loader Version: 5.0.2

### Expected Behavior

publicPath: ('[ext]' === 'js' || '[ext]' === 'css') ? "{$basePath}/dist/" : "./",  => [ext] will return file extenstion

### Actual Behavior

publicPath: ('[ext]' === 'js' || '[ext]' === 'css') ? "{$basePath}/dist/" : "./",  => [ext] will return string '[ext]'

### Code

https://gist.github.com/acqsk/45014a9cfd592a2b5bd9fbbbc8d94af3

### How Do We Reproduce?

npm run build

**Comment by evilebottnawi** [comment]
Because publicPath doesn't support patterns please read https://webpack.js.org/configuration/output/#outputpublicpath and  https://webpack.js.org/guides/public-path/

**Comment by acqsk** [comment]
@evilebottnawi but till now, It was working. Something was changed?

**Comment by evilebottnawi** [comment]
output.publicPath is option for webpack, not for file-loader

**Comment by acqsk** [comment]
> output.publicPath is option for webpack, not for file-loader

@evilebottnawi thanks for info, but till upgrade packages, the [ext] inside publicPath was working. How can I make the same without [ext]? I need to modify the path of files, which I will inject into html (with HtmlWebpackPlugin).
