### ISSUE TITLE
More documentation around esModules and their behavior please

### ISSUE THREAD

**Issue by tstirrat15** [webpack-contrib/file-loader#370]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
In v5 `esModules` became a default. That broke my application, and making it `false` fixed it, but I have no idea why, and the documentation isn't clear on this note.

* What does an `esModule` mean in the context of `file-loader`?
* How would it be imported and used? Is it meant for end consumption (i.e. being a loader by itself), or is it more meant for chaining?
* When would the features `esModule` enables (like tree-shaking) be used? We're primarily using `file-loader` for image references, and it isn't clear where or how tree-shaking would happen when your imports are singular.

### Your Proposal for Changes
Answers to questions above. I'm happy to (re)write them into the documentation.

**Comment by evilebottnawi** [comment]
> What does an esModule mean in the context of file-loader?

From docs:

> By default, file-loader generates JS modules that use the ES modules syntax. There are some cases in which using ES modules is beneficial, like in the case of module concatenation and tree shaking.

> How would it be imported and used? Is it meant for end consumption (i.e. being a loader by itself), or is it more meant for chaining?

Always yes.

> When would the features esModule enables (like tree-shaking) be used? We're primarily using file-loader for image references, and it isn't clear where or how tree-shaking would happen when your imports are singular.

How tree-shaking works is out of the repo.

You can find a lot of articles about tree shaking and `import`/`export`

**Comment by tstirrat15** [comment]
> Always yes.

Is that yes to end consumption or is that yes to chaining? I think that would answer my question.

**Comment by rightaway** [comment]
Are we able to use `import()` function or only `import` statement? I get `src="[object Promise]"` as the output when I use `import()` even though I have `esModule: true`.

**Comment by evilebottnawi** [comment]
@rightaway update html-loader to latest version

**Comment by rightaway** [comment]
I'm not using html-loader. You mean file-loader? I'm using latest 6.0.0. This is in a Vue template file btw.
