### ISSUE TITLE
Jpeg-2000 support

### ISSUE THREAD

**Issue by AmberWilliams** [webpack-contrib/file-loader#376]
- Operating System: MacOs
- Node Version: v12.4.0
- NPM Version: 6.9.0
- webpack Version: 4.41.18? (used through Gatsby)
- file-loader Version: not using it at the moment

### Feature Proposal
Be able to use `.jp2` (Jpeg-2000) images in bundled source code

### Feature Use Case
Image optimization for Safari users

**Comment by evilebottnawi** [comment]
Just add `jp2` to `test`

**Comment by evilebottnawi** [comment]
Please create this issue in `Gatsby`
