### ISSUE TITLE
copying images with picture tag

### ISSUE THREAD

**Issue by one618** [webpack-contrib/file-loader#379]
On production file loader is only loading the jpg image, is there is any way to copy both pictures insde picture element ?

```
<picture>
  <source type="image/webp" srcset="images/hero.webp">
  <source type="image/jpeg" srcset="images/hero.jpg">
  <img src="images/hero.jpg" alt="">
</picture>
```

so only the jpg will be copied after i build and here is my configuration

```
const images = {
  test: /\.(gif|png|jpe?g|svg)$/i,
  exclude: /fonts/,
  use: [
    'file-loader?name=images/[name].[hash].[ext]',
    config.env === 'production' ? imageLoader : null,
  ].filter(Boolean),
};
```

**Comment by evilebottnawi** [comment]
We don't touch html content, and you ignore the issue template, so I can't help sorry

**Comment by evilebottnawi** [comment]
maybe you need to change ` test: /\.(gif|png|jpe?g|svg|webp)$/i,`

**Comment by one618** [comment]
Ok i;m sorry but do you know where should i post my question ?
