### ISSUE TITLE
RFC: uglify option

### ISSUE THREAD

**Issue by TroyTae** [webpack-contrib/file-loader#380]
### Feature Proposal

How about add uglify option?
Now `interpolateName` provides hash function.
But we can use just 'A' or '~' and get lighter bundle file.
If webpack team has a will on this, I wanna apply this module: https://github.com/TroyTae/uglify-set

### Summary specification

name: uglify 
type: Boolean
default: false

**Comment by evilebottnawi** [comment]
Please open an issue here https://github.com/webpack/loader-utils, we should solve it for `interpolateName`, not for loader

**Comment by TroyTae** [comment]
@evilebottnawi 
I think we need to do this work in loader.
Because we have to use different uglify method according to target.
For example, file name can use number at first word, but css class name cannot use like this.

**Comment by evilebottnawi** [comment]
@TroyTae No, it should be in `interpolateName`, you will can use `[ugly-name].[ext]` placeholder for this case

**Comment by TroyTae** [comment]
@evilebottnawi 
Ok then I'll make a issue in `loader-util`.
Maybe we need to split value of option.
Boolean -> String('filename' | 'css' | '~~~')
