### ISSUE TITLE
Pass additional assetInfo object when calling emitFile

### ISSUE THREAD

**Issue by bschlenk** [webpack-contrib/file-loader#382]
- Operating System: MacOS
- Node Version: 12.6.1
- NPM Version: 6.14.7
- webpack Version: 4.29.6
- file-loader Version: 3.0.1

### Feature Proposal

Webpack loader's [emitFile](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L59) call takes a 4th param that can provide additional info about an asset, like whether it is immutable or not. `file-loader` should pass in `{ immutable: true }` when the file name includes `[contenthash]` so that other plugins can benefit from this info.

The new `assetInfo` param was added in https://github.com/webpack/webpack/issues/9038.

### Feature Use Case

I'm writing a plugin that uses this info to determine what cache-control headers a file can be given.

**Comment by evilebottnawi** [comment]
Let's do it

**Comment by evilebottnawi** [comment]
Fixed by https://github.com/webpack-contrib/file-loader/pull/383
