### ISSUE TITLE
Breaking change desc in 5.0.0 can be improved

### ISSUE THREAD

**Issue by tomaszs** [webpack-contrib/file-loader#390]
Currently it states:

https://github.com/webpack-contrib/file-loader/releases/tag/v5.0.0

```
switch to ES modules by default (the option esModule is true by default)
```

While restoring previous behaviour is described in the source code. Above description could be changed to:

```
switch from CommonJS to ES modules. You can go back to CommonJS with:

options: {
              esModule: false
            },
```

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
