### ISSUE TITLE
Breaking change desc in 5.0.0 can be improved

### ISSUE THREAD

**Issue by tomaszs** [webpack-contrib/file-loader#391]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Currently it states:

https://github.com/webpack-contrib/file-loader/releases/tag/v5.0.0

```
switch to ES modules by default (the option esModule is true by default)
```

It does not say what is the impact (change from CommonJS to ES modules), and how to switch it back.

### Your Proposal for Changes

Above description could be changed to:

```
switch from CommonJS to ES modules. You can go back to CommonJS with:

options: {
              esModule: false
            },
```

**Comment by evilebottnawi** [comment]
What is confusing? We describe what was and what became

**Comment by tomaszs** [comment]
Was:

- no info what the change causes (what if I leave it?)
- no info how to revert to CommonJS (backwards compatibility)

Is:

- there is information what it means: change from CommonJS to ES modules
- instruction how to revert the breaking change (switch back to CommonJS)

**Comment by evilebottnawi** [comment]
Feel free to send a PR to docs if you want, sorry we don't have time on this, also we have `6.1.1`, most of developers already migrate on this and no one have the problem, sorry again

**Comment by tomaszs** [comment]
You mean only I reported it. It does not mean no one has the problem. But I agree it is minor especially since it is about a release one year old. Anyways, it'd still take much less time than what we both have invested in this report

**Comment by evilebottnawi** [comment]
@tomaszs feel free to send a PR
