### ISSUE TITLE
Support for loader chaning

### ISSUE THREAD

**Issue by Relypete** [webpack-contrib/file-loader#394]
### Feature Proposal
I'd like to chain another custom loader in front of `file-loader`. However, `file-loader` will always return `export default <path>`, even when chaining is used. This is suboptimal since this output cannot be used directly as input for the next loader which is only interested in the `<url>` part. I propose a loader option that ensures the loader will return the url without `export default`.

**Comment by evilebottnawi** [comment]
Yep, this is how the loader works, nfortunately it will never work like that. Also:
- `file-loader`/`url-loader`/`raw-loader` are deprecated for webpack@5 in favor https://webpack.js.org/guides/asset-modules/ (only custom publicPath is not supported, we are working on it)
- Not `raw` loader should always return JS code

So my recommendation - create own loader, logic is simple
