### ISSUE TITLE
OTS parsing error: invalid version tag | Failed to decode downloaded font: http://localhost:3000/static/7542ab376339625d813fe71d074ee925.woff

### ISSUE THREAD

**Issue by geroylaurence** [webpack-contrib/file-loader#399]
![image](https://user-images.githubusercontent.com/48232303/103724385-2c20a300-500f-11eb-87a3-ea79e9bcb264.png)

  I got this warning on my project and my imported custom font is not applying as  well.
  
  I'm using webpack version4 and I'm merging from webpack3, on my old version of webpack (ver3) my file-loader integrations is fully working. I need help

**Comment by alexander-akait** [comment]
You have broken fonts, check file and please use the issue template (closing because it was ignored)

**Comment by geroylaurence** [comment]
> You have broken fonts, check file and please use the issue template (closing because it was ignored)

Hi, thank you for response, yes the file seems to be broken as I notice it, but can you somehow suggest or tell me possible cause of that? that font file you seeing from the screenshot is generated from webpack4, somehow I suspect it generates a broken file on transpiling my assets to the build folder.

Before, I was using webpack ver3 and file-loader, and also using this custom font, and it's working fine, now I'm just switching from webpack 3 to webpack 4 and these happened. I appriciate the help

**Comment by alexander-akait** [comment]
You can have broken plugin or loader, I don't know, you don't provide it because ignore the issue template (where it was described and requested)
