### ISSUE TITLE
Allow access to [parent] variable

### ISSUE THREAD

**Issue by natew** [webpack-contrib/file-loader#52]
I'd really want access to the name of the parent require. So if I require a module `bootstrap` and it does:

`require('abc.css')`

I can then control the output of that file and have it be:

`somedir/bootstrap/abc.css`

I'd imagine it's something like:

`?name=somedir/[parent]/[name].css`

**Comment by natew** [comment]
Another thing that would be helpful is naming based on the parent file as well as parent module. So maybe:

- `[parentFile]`
- `[parentModule]`

**Comment by evilebottnawi** [comment]
@natew we use https://github.com/webpack/loader-utils#interpolatename for interpolate filename. What mead `parent*`? How we can determinate `parent`?
