### ISSUE TITLE
Module are relative to __webpack_require__.p instead of __webpack_public_path__

### ISSUE THREAD

**Issue by SBoudrias** [webpack-contrib/file-loader#53]
I'm using 0.8.5

My image is compiled as `module.exports = __webpack_require__.p + "60247a30f60ff8bf38641abc039d435a.png"` inside the generated source code. But there's no `publicPath` setup in the webpack config.

Given this, I would've expected the path to be relative to `__webpack_public_path__` (reading the code of this plugin is also what I'm lead to believe https://github.com/webpack/file-loader/blob/master/index.js#L17).

I'm wondering if a step further down the compilation is actually changing `__webpack_public_path__` to `__webpack_require__.p`

**Comment by luqin** [comment]
+1

**Comment by samsch** [comment]
In my code, where I've used `__webpack_public_path__` directly, it gets compiled to `__webpack_require__.p`. The value for `__webpack_require__.p` defaults to "", so in my front end code I set `__webpack_public_path__` to the public url of the webpack output folder.

**Comment by michael-ciniawsky** [comment]
Please test with the latest (`npm i -D file-loader`) or the current beta (` npm i -D file-loader@beta`) again and reopen if still regressions (+ include your `webpack.config.js`then please :))
