### ISSUE TITLE
How to skip files rebuild  everytime the app runs in dev mode?

### ISSUE THREAD

**Issue by keyserfaty** [webpack-contrib/file-loader#55]
Is there anyway I can skip the files being rebuild every time the build runs? I don't see why I would want that in files that haven't change. Am I missing something?
Thanks :+1:

**Comment by evilebottnawi** [comment]
@keyserfaty why your need this feature? Webpack v2 and above using cache for loaders by default and don't emit files if they not changed.

**Comment by buzinas** [comment]
@evilebottnawi I use webpack 3 already, and what you're saying doesn't happen at all.

Every time I touch a css file which has a reference to a `.png` file (for background, for example), the file-loader emits the png file again and again.

Most of the files in my project takes 200~500ms to rebuild when watching, but some of them which have many PNG files referenced on it, sometimes it takes > 5s, it's awful.

**Comment by evilebottnawi** [comment]
@buzinas hm, yes, I'll try to find a solution, but I think it's related more to `css-loader`, than `file-loader`

**Comment by michael-ciniawsky** [comment]
```diff
+ const cache = {}

 if (options.emitFile === undefined || options.emitFile) {
   // Don't emit the file again
+ if (cache[outputPath]) return

+ cache[outputPath] = true
  this.emitFile(outputPath, content);
 }
```

?

**Comment by michael-ciniawsky** [comment]
Please test and try out #213

**Comment by buzinas** [comment]
Why was this closed even though it wasn't fixed?

**Comment by michael-ciniawsky** [comment]
It's not possible to fix this within `file-loader` the e.g `compiler.(Input|Output)FileSystem` etc need to handle this instead. `file-loader`  just pushes the file contents to `module.assets`  and takes care of the rewriting the file paths, no convenient way to fix this here

**Comment by evilebottnawi** [comment]
@buzinas Yes should be fixed in webpack, feel free to create issue in `webpack` :+1:
