### ISSUE TITLE
[feature] Don't emit assets which haven't changed since the last build

### ISSUE THREAD

**Issue by sirlancelot** [webpack-contrib/file-loader#63]
_Problem:_ When Webpack is running in watch mode with a cache object, static files are always emitted, regardless of whether the source file has changed.

_Expected:_ If the source file hasn't changed, don't emit the asset.

Would fix #55

**Comment by sirlancelot** [comment]
On Webpack v2.2.0-rc.3 this is still a problem. Is it possible to only emit changed files using this loader?

**Comment by buzinas** [comment]
Can anyone give me some directions on how to implement this? I'm happy to create a PR for that.

**Comment by evilebottnawi** [comment]
Close. Duplicate https://github.com/webpack-contrib/file-loader/issues/63.

**Comment by sirlancelot** [comment]
@evilebottnawi do you mean Duplicate of #55? ;)

**Comment by evilebottnawi** [comment]
@sirlancelot oh, sorry, yes
