### ISSUE TITLE
Causes Webpack to build empty JS bundle with OccurrenceOrderPlugin

### ISSUE THREAD

**Issue by impguard** [webpack-contrib/file-loader#65]
When I'm using this loader with the OcurrenceOrderPlugin, my outputted JS bundle becomes empty.

Here's my config file:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
    devtool: 'cheap-module-source-map',
    entry: {
        javascript: path.resolve(__dirname, 'src/index.jsx'),
        html: path.resolve(__dirname, 'src/index.html')
    },
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['', '.js', '.jsx'],
    },
    plugins: [
        new webpack.optimize.OccurrenceOrderPlugin(),
    ],
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.html$/,
                loader: 'file',
                query: {
                    name: '[name].[ext]'
                }
            }
        ]
    }
}
```

If I remove the usage of the loader and the entry point for it, my compiles js is ~700kB. If I add it back in, it compiles down to 1 kB and is effectively empty (no contents besides code pointing to the source map).

I wasn't sure if this is a file-loader problem or a webpack problem, but I couldn't find any similar issues there, so I presume it is file-loader related.

**Comment by evilebottnawi** [comment]
@impguard Is the problem still there? can your create minimum reproducible test repo?
