### ISSUE TITLE
File loader freezes webpack

### ISSUE THREAD

**Issue by bensampaio** [webpack-contrib/file-loader#82]
I decided to use file loader to copy the images I reference in my SCSS into my public assets folder. So I added the following to my webpack config file:

``` js
module: {
  loaders: [
    /* babel and css loaders */
    {
      loader: 'file?name=[name].[ext]!img',
      test: /\.(jpe?g|png|gif|svg)$/i,
    }
  ]
}
```

The first time I tried to run webpack with that configuration it stopped in: 67% 686/714 build modules. The process continued running but didn't move from that point and there were no error messages. I also tried to set `output.publicPath` but nothing changed.

Besides the file loader, I am using babel to transpile ES2015 and React and the css, sass and postcss loaders.

What am I doing wrong?

**Comment by SpaceK33z** [comment]
I'm using file-loader with sass-loader in many projects, but I don't have this issue. Could you provide a repo that reproduces this problem?

**Comment by michael-ciniawsky** [comment]
@bensampaio see @SpaceK33z comment and reopen if have time to setup a repo to test 😛

**Comment by bensampaio** [comment]
Later on I realised this problem was related to `sass-loader`: https://github.com/webpack-contrib/sass-loader/issues/100. It was just a coincidence that the problem started happening after I added the `file-loader`.
