### ISSUE TITLE
[feature] enable dynamic tune emitPath of file

### ISSUE THREAD

**Issue by Delagen** [webpack-contrib/file-loader#89]
```
if (config.emitPath) {
        // support functions as emitPathto generate them dynamically
        url=    typeof config.emitPath=== "function" 
                 ? config.emitPath(url) 
                 : url;
    }
```

before emit

**Comment by evilebottnawi** [comment]
@Delagen can your explain use case?

**Comment by Delagen** [comment]
@evilebottnawi for example to tune paths, that not child of context folder, or resolved somewhere else. I fork local copy of this module to strip node_modules from generated urls

**Comment by evilebottnawi** [comment]
@Delagen why your strip `node_modules` from generated urls? In production or dev?

**Comment by Delagen** [comment]
@evilebottnawi I want to strip module path from production bundles, but save original filenames

**Comment by evilebottnawi** [comment]
@Delagen can your provide minimum reproducible test repo? Without configuration it's hard to say how you can solve this problem and how it will be solved correctly

**Comment by Delagen** [comment]
For example:
tree
```
src
node_modules/common-lib
```
webpack context is `src`

when file required from common-lib

it placed as _/node_modules/common-lib/..../file.html for example
and as more as `../../../` in relative path from webpack context, the more _/_/_ in urls

**Comment by evilebottnawi** [comment]
@Delagen it is expected behavior, just use `name` options for production env (for avoid this situation), for dev env it is normal.

**Comment by Delagen** [comment]
@evilebottnawi I want to preserve some path info in production environment.
Filename can be the same, but I don't want to include hash in filename

**Comment by evilebottnawi** [comment]
@Delagen also your can use `outputPath` as function (https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L58) and do what your want with paths

**Comment by Delagen** [comment]
@evilebottnawi ok, but it's be tricky to detect needed files and what to do with urls in generated code?

**Comment by evilebottnawi** [comment]
@Delagen sorry for delay on answer, problem still exists? `outputPath` and `publicPath` can be `function` and you can control and `url` and `place` where emit file(s). But i recommend don't do it in dev env (development experience) and use `[name]`, `[path]` and etc in prod env.

**Comment by Delagen** [comment]
@evilebottnawi Works now
