### ISSUE TITLE
[path] or [name] problem ?

### ISSUE THREAD

**Issue by monochrome-yeh** [webpack-contrib/file-loader#90]
### Issue

I couldn't solve nested image folder when scss load url()

I've been always gotten `assets/resources/assets/img/f/f2/example.png?eeeeeeeeee` this kind of `path`;

if I only used `[name]`, it will return:
`assets/example.png?eeeeeeeeee`

however I desire it will be `assets/img/f/f2/example.png?eeeeeeeeee`
- nodejs v6.6.0
- webpack 1.13.2
- file-loader 0.8.5
### Scss example

``` css
.example {
    background-image: url( "../img/f/f2/example.png" );

    // tried
    // background-image: url( "~img/f/f2/example.png" ); 
}
```
### Folder structure

```
├── public
│   ├── assets
│   │   ├── css
│   │   ├── fonts
│   │   ├── img
│   │   └── js // Entry js file in this folder
├── resources
│   ├── assets
│   │   ├── img // images resource 
│   │   │   ├── a
│   │   │   ├── b
│   │   │   ├── c
│   │   │   ├── d
│   │   │   ├── e
│   │   │   ├── f
│   │   │   │   └── f2
│   │   │   ├── g
│   │   │   └── h
│   │   ├── js
│   │   └── scss
```

``` javascript
let config = {
    ...
    output: {
        path: path.resolve( __dirname, 'public/assets/' ),
        publicPath: '/assets/',
        filename: 'js/[name].js',
    },
    module: {
        loaders: [
            {
                test: /\.(jpe?g|png|gif|svg)(\?v=\d+\.\d+\.\d+)?$/i,
                loader: 'file-loader?name=[path][name].[ext]?[hash:10]',
                exclude: /(node_modules|bower_components)/
            },
            {
                test: /\.scss$/,
                // loader: ExtractTextPlugin.extract( 'css!resolve-url!sass' ), // tried
                // loader: ExtractTextPlugin.extract( 'css!postcssl!sass?sourceMap' ), // tried
                // loader: ExtractTextPlugin.extract( 'css?root=.!sass' ), // tried
                loader: ExtractTextPlugin.extract( 'css!sass' ) // tried
                exclude: /(node_modules|bower_components)/
            }
        ]
    },
    plugins: [
        // 打包css
        new ExtractTextPlugin( 'css/[name].css', {
            allChunks: true,
            // publicPath: '.' // tried
        } )
    ],
    resolve: {
            root: [
                // path.resolve( '..' ) //tried
            ],
            alias: {
                // 'img': path.resolve( './resources/assets/img' ) // tried
            },
            ...
        },
```
### Note

I've referred many solutions to solve this problem, (whether using url-loader or file-loader)
however there aren't nested folders in image folder.
I could pass through 1 level folder easily, but that isn't in my case :(

How can I get correct path ?

I would appreciate if you can solve this problem.

**Comment by monochrome-yeh** [comment]
revised description.

**Comment by monochrome-yeh** [comment]
I've referred many solution to solve this problem,
however there aren't nested folders in image folder.
I could pass through 1 level folder easily, but that isn't in my case :(

**Comment by JQChan** [comment]
Have you solve this problem?

**Comment by monochrome-yeh** [comment]
@JQChan , I haven't solved this problem yet.
Do you have any suggestion to me?
I would appreciate your reply, if you could give me some idea.

**Comment by borela** [comment]
Try this:
```
{
  test: /\.(jpe?g|png|gif|svg)(\?v=\d+\.\d+\.\d+)?$/i,
  exclude: /(node_modules|bower_components)/,
  loader: 'file',
  query: {
    regExp: '\\b(assets.+)',
    name: '[1]?[hash:10]',
  },
},
```

**Comment by luchsamapparat** [comment]
I found another solution which gives you more options to manipulate the URL. You can add a `customInterpolateName` property to your webpack config which allows you to define your own templates.

Here is a *very* simple example:

webpack.config.js
```js
module.exports = {
  customInterpolateName: function (url, name, options) {
    // access loaderContext via this (e.g. loaderContext.context)
    url.replace('[myAssetPath]', '/some/path/');
  },
  module: {
    loaders: [
      {
        test: /\.(gif|jpg|png)$/,
        loader: 'file',
        query: {
          name: '/[myAssetPath]/[name].[ext]'
        }
      }
    ]
  }
}
```

**Comment by monochrome-yeh** [comment]
@luchsamapparat thanks dude, although it seems has a heavy loading, however it's good to me to solve this problem :)

**Comment by monochrome-yeh** [comment]
I've seen webpack2, it seems that could be works.
FYI: https://gist.github.com/sokra/27b24881210b56bbaff7#loaders-configuration

but I didn't try it.

**Comment by nsteenbeek** [comment]
I had to do a return to get it working:

    ```javascript
customInterpolateName: function (loaderContext, name, options) {
    return loaderContext.replace('[myAssetPath]', '/some/path/');
}
```

**Comment by luchsamapparat** [comment]
yes, of course. sorry, fixed it

**Comment by appsolutegeek** [comment]
This seems really exactly what I need, I need to manipulate the [path] built in template variable. Tried the following

```
module.exports = {
  customInterpolateName: function (url, name, options) {
    // access loaderContext via this (e.g. loaderContext.context)
    return url.replace('[myAssetPath]', '/some/blablbaalalalalalalalalla/');
  },
```

But I get 

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

I am using webpack 2.

**Comment by monochrome-yeh** [comment]
@appsolutegeek 
I haven't encountered this situation with webpack2.2 yet,
it might be another case what we need to care.

**Comment by appsolutegeek** [comment]
@monochrome-yeh , Thanks. Yes, i think it would be helpful, I was trying to fix an issue with the [path] variable that is parsed. See my other github issue here https://github.com/webpack-contrib/file-loader/issues/124#issuecomment-278453104

Basically, the [path] is returning a longer path, I would like to have it pruned.

And I was hoping this was a way to do that

Thanks again.

**Comment by evilebottnawi** [comment]
@monochrome-yeh Is the problem still there? Did `customInterpolateName` option solved your problem? Can your create minimum reproducible test repo?

**Comment by jrs320** [comment]
yes,yes,yes, I have the same problem，this issue is very useful for me, thanks
