### ISSUE TITLE
bug: babel-loader + file-loader = corrupted files

### ISSUE THREAD

**Issue by jadekler** [webpack-contrib/file-loader#93]
Related: https://github.com/webpack/file-loader/issues/77

When babel-loader is present and I try to add file-loader for `.jpg` files, it results in corrupted files. Removing file-loader for `.jpg` files or changing file-loader to look for `.JPG` files (presumedly babel-loader looks at `.jpg` files) fixes the issue.

**Comment by SpaceK33z** [comment]
That's weird, but I don't think we can do anything in file-loader to fix this issue.

@hzoo / @danez, do you happen to know why babel-loader would handle `.jpg` files? And if babel-loader is at fault here or we should change something in file-loader?

**Comment by danez** [comment]
That is weird. babel-loader should not handle `.jpg`s and I cannot find any reference of jpg in the codebase. But as it also seems to happen with ts-loader as in #77 i might suspect webpack to mix up loaders, but probably also very unlikely. I can try tonight creating a test case and try reproducing it.

**Comment by SpaceK33z** [comment]
Thanks @danez. I just tried to reproduce this in a project of mine, and discovered something interesting:

In webpack v2 (didn't test in v1), the image *does* work if you use `import`. However, if you use `require`, the image is corrupted.

**Comment by evilebottnawi** [comment]
@jadekler problem still exists?

**Comment by allanesquina** [comment]
Hey guys, I'm running into this issue after updating to version `1.0.0`. I was using the version `^0.9.0`. 
The output files are much bigger than the originals.
Here's my config:

```javascript
 module: {
      rules: [
        ...
        {
          test: /\.(svg|jpe?g|png|ttf|woff2?)$/,
          exclude: /node_modules/,
          use: {
            loader: 'file-loader',
            options: {
                name: 'assets/img/[name]-[hash:8].[ext]',
            },
          },
        },
        ...

```

**Comment by JonWallsten** [comment]
I have the same issue. But without babel.
https://github.com/angular/angular-cli/issues/8891
