### ISSUE TITLE
understanding: query parameter name

### ISSUE THREAD

**Issue by db-developer** [webpack-contrib/file-loader#98]
From webpack:
`{
        test: /\.(png|jpe?g|gif|svg|ico)$/,
        loader: 'file-loader',
    query: "name=img\\[name].[ext]"
}`
Will produce: 
`<img _ngcontent-qih-1="" src="img\angular.png">`

Whereas:
`{
        test: /\.(png|jpe?g|gif|svg|ico)$/,
        loader: 'file-loader',
    query: "name=img/[name].[ext]"
}`

Will produce: 
`<img src=img/angular.png>`

The primer obviously is windows specific, the later simply does not work at all.

Using [path] does not solve the issue, because "src" or "dist" become part of the image url, which is not really helpful.
What I'm trying to do is, packageing webpack results within a WAR file for deployment.

**Comment by db-developer** [comment]
Okay, this seems to be a bug:

Whenever query contains a slash, the returned img is missing attribute quotation marks.
<img src=whereever/whatever> instead of <img src="whereever/whatever">

webpack-1.13.2.tgz
file-loader-0.9.0.tgz
windows 10
node 06.06.00
target: tomcat 8 war

Btw - trying to insert quotation marks manually (see below) results in a webpack process which never returns :-)
`{
  test: /\.(png|jpe?g|gif|svg|ico)$/,
    loader: 'file-loader',
      query: {
        name: '"./[name].[ext]"'
      }
}`

**Comment by michael-ciniawsky** [comment]
@db-developer Maybe a bug in [loader-utils](https://github.com/webpack/loader-utils), which is responsible for interpolation of `[path|name|ext]`
